
const FB_INFOSEC_VERSION = &h10
const FB_INFOSEC_NAME = ".fbctinf"
const FB_INFOSEC_OBJNAME = "__fb_ct.inf"

enum FB_INFOSEC
	FB_INFOSEC_EOL = 0
	FB_INFOSEC_LIB
	FB_INFOSEC_PTH
	FB_INFOSEC_CMD
end enum
