' ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
'< _tobac.bas modul generated by utility                     GladeToBac V3.0.1 >
'< Modul _tobac.bas erzeugt von                                                >
'< Generated at / Generierung am                             2011-09-18, 17:46 >
' -----------------------------------------------------------------------------
'< Main/Haupt Program name: FB_Calc.bas                                        >
'<  Email:  Thomas{ dot ]Freiherr[ AT ]gmx[ dot }net                           >
'<    WWW:  www.freebasic-portal.de                                            >
' -----------------------------------------------------------------------------
'< declare names, signal handlers, load GUI-XML                   do not edit! >
'< deklariert Namen, Signale, laedt GUI-XML                  nicht veraendern! >
' vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

TYPE GUIData
  AS GtkBuilder PTR XML
  AS GObject PTR _
  winMain, EntDisplay, but7, but4, but1, but0, but2, but5, but8, but9,  _
  but6, but3, but_plus, but_gleich, but_minus, but_mult, but_div, but_clear,  _
  butD, butPM
END TYPE
DIM SHARED AS GUIData GUI

GUI.XML = gtk_builder_new()

SCOPE
  DIM AS GError PTR meld
  IF 0 = gtk_builder_add_from_file(GUI.XML, "FB_Calc.ui", @meld) THEN
    WITH *meld
      ?"Fehler/Error (GTK-Builder):"
      ?*.message
    END WITH
    END 2
  END IF
END SCOPE

WITH GUI
  .winMain = gtk_builder_get_object(.XML, "winMain")
  .EntDisplay = gtk_builder_get_object(.XML, "EntDisplay")
  .but7 = gtk_builder_get_object(.XML, "but7")
  .but4 = gtk_builder_get_object(.XML, "but4")
  .but1 = gtk_builder_get_object(.XML, "but1")
  .but0 = gtk_builder_get_object(.XML, "but0")
  .but2 = gtk_builder_get_object(.XML, "but2")
  .but5 = gtk_builder_get_object(.XML, "but5")
  .but8 = gtk_builder_get_object(.XML, "but8")
  .but9 = gtk_builder_get_object(.XML, "but9")
  .but6 = gtk_builder_get_object(.XML, "but6")
  .but3 = gtk_builder_get_object(.XML, "but3")
  .but_plus = gtk_builder_get_object(.XML, "but_plus")
  .but_gleich = gtk_builder_get_object(.XML, "but_gleich")
  .but_minus = gtk_builder_get_object(.XML, "but_minus")
  .but_mult = gtk_builder_get_object(.XML, "but_mult")
  .but_div = gtk_builder_get_object(.XML, "but_div")
  .but_clear = gtk_builder_get_object(.XML, "but_clear")
  .butD = gtk_builder_get_object(.XML, "butD")
  .butPM = gtk_builder_get_object(.XML, "butPM")
END WITH

#INCLUDE "on_number_clicked.bas"
#INCLUDE "on_operation_clicked.bas"

