<?php
/***************************************************************************
 *                       lang_faq.php [portuguese_brazil]
 *                            -------------------
 *   begin                : Wednesday Oct 3, 2001
 *   copyright            : (C) 2002 Grupo Suporte phpBB
 *   email                : forum@suportephpbb.org
 *
 *   $Id$
 *
 ****************************************************************************/

/****************************************************************************
 * Traduzido por:
 * Equipe phpBB - <http://www.suportephpbb.org>
 ****************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/

$faq[] = array("--","Questões de <i>Entrar</i> e <i>Registrar</i>");
$faq[] = array("Porque eu não consigo <i>Entrar</i> nos fóruns?", "Registrou-se? Você deve <u>Registrar-se</u> para poder <u>Entrar</u>. Foi expulso dos fóruns? Surgirá uma mensagem de aviso se isso aconteceu. Caso haja uma expulsão você deve contactar o 'webmaster' ou o Administrador do fórum e perguntar o porquê da expulsão caso não saiba a razão. Caso esteja registrado e não esteja expulso e mesmo assim não consiga <u>Entrar</u>, verifique novamente se o seu <u>Nome de Usuário</u> e <u>Senha</u> são os corretos. Normalmente é esse o problema. Caso não saiba mesmo o que esta acontecendo e não seja nenhuma das razões acima descritas contate o Administrador do fórum porque pode acontecer de alguma configuração do sistema está errada.");
$faq[] = array("Porque eu tenho que me <i>Registrar</i> no fórum?", "Pode não ser necessário. Isso está inteiramente ao critério do Administrador dos fóruns se é necessário o registro dos usuários para poderem postas as suas mensagens. Contudo, o registro lhe dá acesso a funções adicionais e possivelmente fóruns que não estão disponíveis a visitantes. Alguns exemplos são o uso e definição de imagens <u>Avatar</u> , uso de <u><b>M</b>ensagens <b>P</b>articulares</u>, enviar e receber <u>e-mail</u> entre usuários, participar de <u>Grupos de Usuários</u>, etc. São necessários apenas alguns segundos para se fazer o registro, por isso recomenda-se que o faça.");
$faq[] = array("Porque quando entro no fórum já estou logado?", "Se não marcar a opção <u>Permanecer Logado automaticamente em cada visita</u> antes de realizar o <u>Login</u>, o sistema não o irá loga-lo da próxima vez que visite o fórum. Isto evita o uso abusivo da sua conta por outra pessoa. Para se manter logado e não precisar escrever o seu <u>Nome de Usuários</u> e <u>Senha</u> assinale essa caixa quando se logar. Esta opção no entanto não é recomendável caso acesse o fórum em um computador usado por outros usuários, ou seja, bibliotecas, cyber cafés, departamento em universidade, etc.");
$faq[] = array("Como posso ocultar o meu <i>Nome</i> de <i>Usuário</i> da lista de  <i>Usuários On-line</i>?", "No seu <u>Perfil</u> há uma opção <u>Ocultar meu indicador de Ligado</u>. Se assinalar <u>Sim</u> apenas você e o Administrador poderão ver que você se encontra online. Passará a ser considerado pelo sistema do phpBB 2 como um <u>Usuário Invisível</u>.");
$faq[] = array("Perdi a minha <i>Senha</i>!", "Peça outra senha! Apesar da sua <u>Senha</u> não poder ser recuperada pela Administração do fórum pode no entanto ser feito como que se nunca a tivesse registrado, ou seja, como que se estivesse a se logar pela primeira vez. Para fazer isto clique em <u>Entrar</u> e de seguida em <u>Esqueci-me da Senha</u>, e se seguir as instruções voltará a logar-se em momentos");
$faq[] = array("Me registei mas não consigo <i>Entrar</i>!", "Primeiro verifique se o <u>Nome de Usuário</u> e <u>Senha</u> estão corretos. Caso se encontrem bem então uma entre duas coisas poderão estar a acontecer - se o a função de COPPA se encontra ativa nos fóruns e você tem menos de 13 anos de idade, terá que seguir as instruções que receba. Se isto não é o caso, pode ser que seu registro precisa ser ativado? Alguns administradores preferem que o registro dos seus novos usuários seja ativado através de um e-mail, antes que possa efetivamente <u>Entrar</u> nos fóruns. Caso isso aconteça, quando se registrou foi informado se a ativação seria ou não necessária. Se recebeu um e-mail então siga as suas instruções. Se não recebeu o e-mail, será que o endereço de e-mail é válido? Uma das razões para a ativação ser feita é para reduzir o número abusos do sistema por usuários <i>disfarçados</i> ou passando pelo anonimato. Se tem a certeza que o endereço de e-mail que forneceu é válido e correto tente então contactar o Administrador do fórum.");
$faq[] = array("Me registei no passado mas não consigo mais <i>Entrar</i>?!", "As razões mais prováveis são; escreveu um <u>Nome de Usuário</u> ou <u>Senha</u> incorretos (verifique o e-mail que lhe terá sido enviado quando se registrou inicialmente), ou o administrador poderá ter removido o seu registro por algum motivo. É comum administradores removerem registros de usuários que nunca colocaram mensagens, de forma a reduzir o tamanho do banco de dados. Tente registrar-se novamente e envolver-se nos assuntos dos fóruns.");


$faq[] = array("--","Preferências e Configuração de Usuários");
$faq[] = array("Como mudo a minha configuração?", "Toda a sua configuração (após o <u>Registrar</u>-se) é guardada no banco de dados. Para a alterar clique em <u>Perfil</u> (normalmente no topo das páginas, dependendo do tema em uso). A partir daí você pode alterar a sua configuração.");
$faq[] = array("As datas e horas não são os corretas!", "As horas provavelmente estão corretas, contudo pode acontecer você ver as horas de um fuso horário diferente de onde você normalmente se encontra ou inicialmente ajustou. Se é esse o caso, você deve mudar no seu <u>Perfil</u> a opção para o <u>Fuso Horário</u> de forma a abranger a sua área, ou seja, Londres, Paris, Nova Iorque, Sidney, ou onde se encontre. Note que a mudança do fuso horário bem como a maior parte das opções de perfil só é permitida a usuários registrados. Se ainda não é o seu caso chegou uma boa altura e razão para o fazer!");
$faq[] = array("Mudei o <i>Fuso Horário</i> mas a hora continua errada!", "Se tem a certeza que o <u>Fuso Horário</u> que escolheu é o correto mas a hora não é a real, é possível que seja devido a mudança horária para ajustamento de hora diurna e noturna (ou hora de Verão/Inverno). O phpBB não se encontra programado para efetuar essas mudanças automaticamente, como tal devem ser ajustadas manualmente pelos usuários.");
$faq[] = array("O meu idioma não se encontra na lista!", "A razão mais provável é o Administrador não ter instalado esse idioma ou o phpBB ainda não ter sido traduzido para o mesmo. Peça ao Administrador que instale esse 'pacote de idioma' e, caso não exista, você poderá criar uma nova tradução. Para mais informação consultar a página oficial do <b>Grupo phpBB</b> (o atalho se encontra ao final destas páginas)");
$faq[] = array("Como posso mostrar uma imagem abaixo do meu <i>Nome de Usuário</i>?", "Deve haver duas imagens na parte inferior de cada Nome de Usuário quando se vê as mensagens - a primeira representa o rank em que o usuário se encontra, normalmente em forma de blocos ou estrelas indicando a quantidade de mensagens que o usuário tenha e respectiva designação no rank, ou o estatuto desse usuário nos fóruns. Abaixo desses ranks poderá existir uma imagem maior conhecida como Avatar, que é normalmente única ou pertencente a cada usuário. Está ao cargo do Administrador dos fóruns permitir ou não o uso de <u>Avatars</u> bem como a forma em como os usuários possam os usar. Se você não consegue colocar o seu, então possivelmente é decisão do Administrador dos fóruns tendo configurado o sistema para não o permitir. Pergunte-lhe a razão (temos a certeza que existe uma boa justificativa!)");
$faq[] = array("Como posso mudar o meu <i>rank</i>?", "De uma forma geral o usuário normal não pode alterar diretamente o seu rank (os ranks aparecem abaixo do Nome de Usuário em tópicos e no 'Perfil' dependendo do tema em uso). A maior parte dos ranks em fóruns indicam o número de mensagens que você tenha colocado ou indicam certo tipo de usuário, ou seja, moderadores e administradores poderão ter um rank especial. Por favor não abuse dos fóruns colocando mensagens desnecessárias apenas para aumentar o seu nível de rank pois o Moderador ou Administrador poderão tomar alguma atitude contra, caso verifiquem que haja abuso.");
$faq[] = array("Quando clico no icone de <i>e-Mail</i> de um usuário me aparece uma mensagem para <i>Entrar</i>!", "Lamentamos mas apenas usuários registrados poderão enviar <u>e-mail</u> a pessoas através do formulário exclusivo do fórum (caso o administrador tenha ativado essa função). Isso é para evitar o uso malicioso do sistema de e-mail por usuários anônimos.");


$faq[] = array("--","Questões na colocação de mensagens");
$faq[] = array("Como posso colocar uma mensagem num fórum?", "Fácil, clique no botão respectivo tanto no fórum como no tópico onde se encontre (dependendo do tema em uso, normalmente os botões têm a designação de <u>Nova Mensagem</u>, <u>Novo Tópico</u> ou <u>Responder</u>). Talvez seja necessário o seu registro nos fóruns para poder postar mensagens. Existe uma lista de ações que lhe são permitidas, haja registro ou não, na parte inferior do lado direito da página de cada fórum (<u>Enviar Mensagens Novas: <b>Permitido.</b>, Votar em Enquetes: <b>Permitido.</b>, etc.</u>)");
$faq[] = array("Como posso <i>editar</i> ou <i>remover</i> uma mensagem?", "A menos que seja um administrador de fórum você apenas pode <u>editar</u> ou <u>remover</u> as suas próprias mensagens. Pode editar uma mensagem (por vezes apenas por um período limitado após ser colocada) clicando no icone <u>editar</u> na parte superior dessa mensagem (dependendo do tema em uso).  Caso alguém tenha já respondido a essa mensagem você encontrará um pequeno texto ao fundo, mencionando que foi editada e eventualmente quantas vezes. Isto não aparece apenas caso essa mensagem não tenha ainda respostas. Também não aparecerá caso a alteração seja efetuada por algum Administrador ou Moderador (possivelmente eles deixarão uma mensagem dizendo o que foi alterado e o motivo). Note que usuários normais não podem remover uma mensagem após alguém já ter colocado uma resposta.");
$faq[] = array("Como adiciono uma <i>assinatura</i> a uma mensagem?", "Para adicionar uma assinatura a uma mensagem deverá primeiro criar uma no seu <u>Perfil</u> no respectivo local. Uma vez criada poderá instruir o fórum, também em <u>Perfil</u>, marque a opção <u>Anexar sempre a minha assinatura</u> às mensagens ou colocá-la apenas quando assim o desejado, assinalando <u>Adicionar Assinatura</u> na lista de opções abaixo de cada campo de nova mensagem.");
$faq[] = array("Como posso <i>adicionar uma enquete</i>?", "Criar uma enquete é fácil. Quando se posta um tópico novo (ou edita a primeira mensagem de um tópico, caso tenha permissão para tal) encontra na parte inferior à caixa principal da mensagem um painel com o título <u>Adicionar uma Enquete</u> (se você não vê isto é porque provavelmente não possui permissão para criar enquetes ou o tópico não é de sua autoria). Deverá escrever um título para a enquete no local apropriado e em seguida colocar pelo menos duas <u>Opções de escolha</u> (para adicionar uma opção escreva o que pretende e clique no botão <u>Adicionar esta opção</u>. Deverá também estipular um limite tempo para a enquete, sendo 0 ilimitado. Poderá acontecer de haver um limite no número de opções de escolha, estando esse limite ao critério e configuração do Administrador dos fóruns.");
$faq[] = array("Como posso <i>editar</i> ou <i>remover</i> uma <i>enquete</i>?", "Da mesma forma que as mensagens as votações apenas poderão ser editadas pelo seu autor, um moderador ou o Administrador dos fóruns. Para editar uma enquete clique no icone <u>Editar</u> da primeira mensagem do tópico (esta mensagem é a que tem a enquete associada ao tópico). Caso ninguém tenha submetido voto, os seus autores podem remover a votação ou editar as suas opções de escolha. Contudo, se os usuários já colocaram votos apenas moderadores e administradores podem editar ou remover essa enquete. Isto é para evitar com que sejam alteradas as opções de escolha em enquetes em andamento.");
$faq[] = array("Porque não consigo entrar num fórum?", "O acesso a alguns fóruns poderá estar limitado apenas a determinados usuários ou grupos. Para verificar, ler, colocar mensagens, etc., você deve necessitar autorização especial. Apenas o moderador desse fórum e um Administrador podem permitir esse acesso. Contate-os caso ache necessário.");
$faq[] = array("Porque não posso votar?", "Apenas usuários registrados podem submeter os seus votos (para impedir duplicação nos resultados). Caso você possua registro mas mesmo assim não consegue votar então possivelmente não lhe foi atribuída permissão para tal.");


$faq[] = array("--","Formatos e tipos de Tópicos");
$faq[] = array("O que é <i>BBCode</i>?", "BBCode é uma implementação especial de HTML. Se pode ou não pode usar BBCode nos fóruns está ao critério do Administrador. (caso lhe seja permitido pode controlar o seu uso em <u>Desativar BBCode nesta mensagem</u>). O BBCode por si mesmo é similar em estilo ao HTML, as TAGs são introduzidas entre colchetes [and] em vez de <nobr>&lt; and &gt;</nobr> e proporcionam um maior controle do que e como algo é apresentado. Para mais informações sobre BBCode veja o guia respectivo, acessível na página de postagem das mensagens nos fóruns.");
$faq[] = array("Posso usar <i>HTML</i>?", "Depende se o Administrador o permita, ele tem o controle completo sobre isso. Se lhe é permitido usar HTML provavelmente apenas alguns códigos lhe são acessíveis. Isto é uma medida de <i>segurança</i> para evitar que pessoas abusem do fórum usando códigos que possam destruir o seu formato ou causar outros problemas. Caso o HTML esteja ativo você pode desativá-lo em cada mensagem assinalando <u>Desativar HTML nesta mensagem</u>.");
$faq[] = array("O que são <i>Smilies</i>?", "Smilies, ou Emoticons são pequenas representações gráficas que podem ser usadas para expressar algum sentimento usando poucos caracteres, ou seja, :) quer dizer feliz, :( quer dizer triste. Uma lista completa de <u>Smilies</u> pode ser vista no formulário junto à caixa de cada mensagem. Tente evitar o uso excessivo dos Smilies já que podem tornar uma mensagem ilegível podendo o Administrador ou um moderador remove-los ou apagar toda a mensagem.");
$faq[] = array("Posso <i>inserir imagens</i>?", "As imagens podem ser adicionadas nas suas mensagens. Contudo, não há presentemente alguma forma de publicar imagens diretamente ao phpBB. Como tal você terá que usar uma imagem armazenada num servidor publicamente acessível, ou seja, http://www.algum-lugar-seu.conhecido.net/minha-imagem.gif. Não pode usar no fórum imagens guardadas no seu próprio PC (a menos que esse possua um servidor publicamente acessível) nem imagens armazenadas sob mecanismos que requeiram autenticação, como por exemplo caixas de correio eletrônico de Hotmail ou Yahoo, páginas protegidas por senha, etc. Para mostrar a imagem pode se usar tanto o BBCode [img] como o código apropriado de HTML (se ativo).");
$faq[] = array("O que são <i>Anúncios</i>?", "Os Anúncios contém normalmente informação importante e você deve lê-los logo que eles surjam. Os Anúncios são automaticamente colocados no topo de cada página do fórum em que são postados. Se você possa ou não fazer uso dessa função depende das permissões que lhe foram dadas, configuradas pelo Administrador.");
$faq[] = array("O que é um tópico <i>Fixo</i>?", "Tópicos fixos aparecem abaixo de anúncios nos fóruns e apenas na primeira página. São vulgarmente importantes e como tal devem ser lidos logo que possível. Da mesma forma que os Anúncios está ao critério do Administrador dos fóruns determinar que permissões são necessárias para postar mensagens Fixas em cada fórum.");
$faq[] = array("O que é um tópico <i>Bloqueado</i>?", "Os tópicos Bloqueados são dessa forma colocados por um moderador ou o Administrador dos fóruns. Quando um tópico se encontra bloqueado não é mais permitido aos usuários colocar respostas e qualquer eventual enquete existente encerra-se automaticamente. Os tópicos podem ser bloqueados por várias razões.");


$faq[] = array("--","Níveis de usuários e Grupos");
$faq[] = array("O que são <i>Administradores</i>?", "Administradores são pessoas com o nível máximo de controle sobre todos os aspectos dos fóruns. Podem controlar toda a operação dos fóruns, incluindo criar, editar ou remover fóruns, determinar permissões, expulsar usuários, criar grupos de usuários ou moderadores, etc. Eles possuem igualmente todos os poderes de moderador em todos os fóruns existentes.");
$faq[] = array("O que são <i>Moderadores</i>?", "Moderadores são usuários (ou grupos de usuários) cujo trabalho é supervisionar diariamente o funcionamento dos fóruns que lhes estejam designados. Eles tem o poder de editar ou remover mensagens, bloquear, desbloquear, mover, remover e subdividir tópicos nos fóruns onde são moderadores. Geralmente os moderadores fiscalizam mensagens que possam ir <i>para além do assunto em discussão</i> ou o uso de material abusivo ou ofensivo.");
$faq[] = array("O que são <i>Grupos de Usuários</i>?", "<u>Grupos de Usuários</u> são uma forma dos administradores dos fóruns agrupar usuários. Cada usuário pode pertencer a vários grupos (isto difere da maioria dos outros tipos de Quadros de Mensagens) e a cada grupo podem ser dados direitos de acesso individuais. Isto torna mais fácil aos administradores destinar vários usuários como moderadores de um determinado fórum ou dar-lhes acesso a um fórum privado, etc.");
$faq[] = array("Como me associo a um <i>Grupo de Usuários</i>?", "Para se associar a um Grupo de Usuários clique no atalho de Grupos no topo da página (dependendo do tema do fórum), podendo então ver todos os Grupos. Nem todos os Grupos possuem um <i>acesso aberto</i>, alguns são fechados e alguns poderão inclusive encontrar-se invisíveis. Se o Grupo se encontra aberto você poderá então solicitar que seja membro clicando no botão apropriado. O moderador do Grupo de Usuários precisa aprovar o seu pedido, podendo perguntar-lhe a razão do mesmo. Por favor não insistir perante a um Moderador de Grupo caso o seu pedido seja recusado. Eles têm as usas razões.");
$faq[] = array("Como posso tornar-me <i>Moderador</i> de um Grupo?", "Os Grupos de Usuários são inicialmente criados pelo Administrador dos fóruns o qual também encarrega alguém de ser Moderador. Se está interessado em criar um Grupo de Usuários o seu primeiro ponto de contato será portanto o Administrador dos Fóruns, ao qual deverá contata-lo com uma <b>M</b>ensagem <b>P</b>articular circunstanciada.");


$faq[] = array("--","<b>M</b>ensagens <b>P</b>articulares");
$faq[] = array("Não consigo enviar <i><b>M</b>ensagens <b>P</b>articulares</i>!", "Há três razões para que tal possa acontecer; você não está registrado nos fóruns e/ou não se encontra logado, o Administrador terá desabilitado a possibilidade de envio de Mensagens Particulares para todos os fóruns ou impede-o a si por algum motivo de enviar mensagens. Se é este o último caso você deverá perguntar ao Administrador qual a razão, caso não a saiba.");
$faq[] = array("Recebo <i><b>M</b>ensagens <b>P</b>articulares</i> indesejáveis!", "Futuramente, adicionaremos a possibilidade da existência de uma lista de usuários a ser ignorados ao sistema de Mensagens Particulares. Por enquanto, caso você continue a receber mensagens particulares não solicitadas a partir de alguém em particular, informe o Administrador, que poderá inviabilizar qualquer usuário de enviar Mensagens particulares.");
$faq[] = array("Recebi de alguém neste fórum mensagens de <i>e-mail</i> com assuntos irrelevantes ou abusivos!", "Embora o sistema de e-mail neste fórum possua funções de segurança que tentam detectar usuários que enviem esse tipo de mensagens lamentamos que tal tenha acontecido. Você deve reportar o acontecido ao Administrador dos fóruns com uma cópia completa do e-mail recebido, sendo muito importante que inclua os cabeçalhos (nesses encontram-se os detalhes do usuário que enviou o e-mail). O Administrador poderá então agir em conformidade.");

//
// These entries should remain in all languages and for all modifications
//
$faq[] = array("--","Questões em relação ao programa phpBB 2");
$faq[] = array("Quem escreveu o phpBB?", "Este software (na sua forma original, sem modificações) é produzido, publicado e com direitos reservados por <a href=\"http://www.phpbb.com/\" target=\"_blank\">phpBB Group</a>. Está disponível sob a licensa 'GNU General Public Licence' e pode ser distribuído gratuitamente. Verificar o atalho para detalhes");
$faq[] = array("Porque não há a função X?", "Este software foi escrito e licenciado por phpBB Group. Se acredita que alguma função pode ser adicionada visite a nossa página oficial em phpbb.com e veja o que o Grupo phpBB pode dizer sobre o assunto. Por favor não coloque mensagens com pedido de funções no fórum em phpbb.com, o Grupo usa sourceforge para resolver situações relacionadas com funções novas. Por favor, leia cuidadosamente esse fórum para ver se  alguma posição já foi tomada por nós sobre a tal função em questão, seguindo então o procedimento lá mencionado.");
$faq[] = array("A quem deva eu contatar sobre questões abusivas e/ou legais relacionadas com este fórum?", "Você deverá contatar o Administrador dos fóruns. Se não conseguir saber quem seja contate então um dos moderadores perguntando a quem deva expor o assunto. No caso de mesmo assim não obter resposta deve contatar o dono do domínio (faça um 'verifição de whois') ou, caso o fórum se encontre a funcionar num serviço grátis (por exemplo, yahoo, free.fr, f2s.com, etc.), a gerência ou o departamento de abusos desse serviço. Por favor notar que phpBB Group não possui absolutamente nenhum controle e não pode de qualquer maneira ser responsável sobre quando, onde e por quem este fórum é usado. Não há razão em contatar o phpBB Group em relação a qualquer questão legal (interrupção e desistência, de responsabilidade, comentário difamatório, etc.) não diretamente relacionado com o 'site' phpbb.com ou o software discreto de phpBB por si próprio. Caso envie algum e-mail a phpBB Group sobre o uso de terceiros deste software, poderá receber uma resposta concisa ou não receber resposta de todo.");

//
// This ends the FAQ entries
//

?>