#pragma once

#define _INC_CPLEXT
#define CPLPAGE_MOUSE_BUTTONS 1
#define CPLPAGE_MOUSE_PTRMOTION 2
#define CPLPAGE_MOUSE_WHEEL 3
#define CPLPAGE_KEYBOARD_SPEED 1
#define CPLPAGE_DISPLAY_BACKGROUND 1
