'' FreeBASIC binding for mingw-w64-v3.3.0

#pragma once

#define _INC_CPLEXT
const CPLPAGE_MOUSE_BUTTONS = 1
const CPLPAGE_MOUSE_PTRMOTION = 2
const CPLPAGE_MOUSE_WHEEL = 3
const CPLPAGE_KEYBOARD_SPEED = 1
const CPLPAGE_DISPLAY_BACKGROUND = 1
