#pragma once

#include once "windows.bi"
#include once "objbase.bi"
#include once "mmsystem.bi"

#define __WINE_DMUSIC_FILEFORMATS_H
#define COM_NO_WINDOWS_H
#define DMUS_FOURCC_GUID_CHUNK mmioFOURCC(asc("g"), asc("u"), asc("i"), asc("d"))

type DMUS_VARIATIONT_TYPES as enumDMUS_VARIATIONT_TYPES
type DMUS_EMBELLISHT_TYPES as enumDMUS_EMBELLISHT_TYPES
type DMUS_PATTERNT_TYPES as enumDMUS_PATTERNT_TYPES

type enumDMUS_VARIATIONT_TYPES as long
enum
	DMUS_VARIATIONT_SEQUENTIAL = &h0
	DMUS_VARIATIONT_RANDOM = &h1
	DMUS_VARIATIONT_RANDOM_START = &h2
	DMUS_VARIATIONT_NO_REPEAT = &h3
	DMUS_VARIATIONT_RANDOM_ROW = &h4
end enum

type enumDMUS_EMBELLISHT_TYPES as long
enum
	DMUS_EMBELLISHT_NORMAL = &h0000
	DMUS_EMBELLISHT_FILL = &h0001
	DMUS_EMBELLISHT_BREAK = &h0002
	DMUS_EMBELLISHT_INTRO = &h0004
	DMUS_EMBELLISHT_END = &h0008
	DMUS_EMBELLISHT_MOTIF = &h0010
	DMUS_EMBELLISHT_ALL = &hFFFF
end enum

type enumDMUS_PATTERNT_TYPES as long
enum
	DMUS_PATTERNT_RANDOM = &h0
	DMUS_PATTERNT_REPEAT = &h1
	DMUS_PATTERNT_SEQUENTIAL = &h2
	DMUS_PATTERNT_RANDOM_START = &h3
	DMUS_PATTERNT_NO_REPEAT = &h4
	DMUS_PATTERNT_RANDOM_ROW = &h5
end enum

type DMUS_IO_SEQ_ITEM as _DMUS_IO_SEQ_ITEM
type LPDMUS_IO_SEQ_ITEM as _DMUS_IO_SEQ_ITEM ptr
type DMUS_IO_CURVE_ITEM as _DMUS_IO_CURVE_ITEM
type LPDMUS_IO_CURVE_ITEM as _DMUS_IO_CURVE_ITEM ptr
type DMUS_IO_TEMPO_ITEM as _DMUS_IO_TEMPO_ITEM
type LPDMUS_IO_TEMPO_ITEM as _DMUS_IO_TEMPO_ITEM ptr
type DMUS_IO_SYSEX_ITEM as _DMUS_IO_SYSEX_ITEM
type LPDMUS_IO_SYSEX_ITEM as _DMUS_IO_SYSEX_ITEM ptr
type DMUS_CHORD_PARAM as DMUS_CHORD_KEY
type LPDMUS_CHORD_PARAM as DMUS_CHORD_KEY ptr
type DMUS_RHYTHM_PARAM as _DMUS_RHYTHM_PARAM
type LPDMUS_RHYTHM_PARAM as _DMUS_RHYTHM_PARAM ptr
type DMUS_TEMPO_PARAM as _DMUS_TEMPO_PARAM
type LPDMUS_TEMPO_PARAM as _DMUS_TEMPO_PARAM ptr
type DMUS_MUTE_PARAM as _DMUS_MUTE_PARAM
type LPDMUS_MUTE_PARAM as _DMUS_MUTE_PARAM ptr
type DMUS_IO_TIMESIG as _DMUS_IO_TIMESIG
type LPDMUS_IO_TIMESIG as _DMUS_IO_TIMESIG ptr
type DMUS_IO_STYLE as _DMUS_IO_STYLE
type LPDMUS_IO_STYLE as _DMUS_IO_STYLE ptr
type DMUS_IO_VERSION as _DMUS_IO_VERSION
type LPDMUS_IO_VERSION as _DMUS_IO_VERSION ptr
type DMUS_IO_PATTERN as _DMUS_IO_PATTERN
type LPDMUS_IO_PATTERN as _DMUS_IO_PATTERN ptr
type DMUS_IO_STYLEPART as _DMUS_IO_STYLEPART
type LPDMUS_IO_STYLEPART as _DMUS_IO_STYLEPART ptr
type DMUS_IO_PARTREF as _DMUS_IO_PARTREF
type LPDMUS_IO_PARTREF as _DMUS_IO_PARTREF ptr
type DMUS_IO_STYLENOTE as _DMUS_IO_STYLENOTE
type LPDMUS_IO_STYLENOTE as _DMUS_IO_STYLENOTE ptr
type DMUS_IO_STYLECURVE as _DMUS_IO_STYLECURVE
type LPDMUS_IO_STYLECURVE as _DMUS_IO_STYLECURVE ptr
type DMUS_IO_STYLEMARKER as _DMUS_IO_STYLEMARKER
type LPDMUS_IO_STYLEMARKER as _DMUS_IO_STYLEMARKER ptr
type DMUS_IO_STYLERESOLUTION as _DMUS_IO_STYLERESOLUTION
type LPDMUS_IO_STYLERESOLUTION as _DMUS_IO_STYLERESOLUTION ptr
type DMUS_IO_STYLE_ANTICIPATION as _DMUS_IO_STYLE_ANTICIPATION
type LPDMUS_IO_STYLE_ANTICIPATION as _DMUS_IO_STYLE_ANTICIPATION ptr
type DMUS_IO_MOTIFSETTINGS as _DMUS_IO_MOTIFSETTINGS
type LPDMUS_IO_MOTIFSETTINGS as _DMUS_IO_MOTIFSETTINGS ptr
type DMUS_IO_CHORD as _DMUS_IO_CHORD
type LPDMUS_IO_CHORD as _DMUS_IO_CHORD ptr
type DMUS_IO_SUBCHORD as _DMUS_IO_SUBCHORD
type LPDMUS_IO_SUBCHORD as _DMUS_IO_SUBCHORD ptr
type DMUS_IO_COMMAND as _DMUS_IO_COMMAND
type LPDMUS_IO_COMMAND as _DMUS_IO_COMMAND ptr
type DMUS_IO_TOOL_HEADER as _DMUS_IO_TOOL_HEADER
type LPDMUS_IO_TOOL_HEADER as _DMUS_IO_TOOL_HEADER ptr
type DMUS_IO_PORTCONFIG_HEADER as _DMUS_IO_PORTCONFIG_HEADER
type LPDMUS_IO_PORTCONFIG_HEADER as _DMUS_IO_PORTCONFIG_HEADER ptr
type DMUS_IO_PCHANNELTOBUFFER_HEADER as _DMUS_IO_PCHANNELTOBUFFER_HEADER
type LPDMUS_IO_PCHANNELTOBUFFER_HEADER as _DMUS_IO_PCHANNELTOBUFFER_HEADER ptr
type DMUS_IO_BUFFER_ATTRIBUTES_HEADER as _DMUS_IO_BUFFER_ATTRIBUTES_HEADER
type LPDMUS_IO_BUFFER_ATTRIBUTES_HEADER as _DMUS_IO_BUFFER_ATTRIBUTES_HEADER ptr
type DMUS_IO_BAND_TRACK_HEADER as _DMUS_IO_BAND_TRACK_HEADER
type LPDMUS_IO_BAND_TRACK_HEADER as _DMUS_IO_BAND_TRACK_HEADER ptr
type DMUS_IO_BAND_ITEM_HEADER as _DMUS_IO_BAND_ITEM_HEADER
type LPDMUS_IO_BAND_ITEM_HEADER as _DMUS_IO_BAND_ITEM_HEADER ptr
type DMUS_IO_BAND_ITEM_HEADER2 as _DMUS_IO_BAND_ITEM_HEADER2
type LPDMUS_IO_BAND_ITEM_HEADER2 as _DMUS_IO_BAND_ITEM_HEADER2 ptr
type DMUS_IO_INSTRUMENT as _DMUS_IO_INSTRUMENT
type LPDMUS_IO_INSTRUMENT as _DMUS_IO_INSTRUMENT ptr
type DMUS_IO_WAVE_HEADER as _DMUS_IO_WAVE_HEADER
type LPDMUS_IO_WAVE_HEADER as _DMUS_IO_WAVE_HEADER ptr
type DMUS_IO_WAVE_TRACK_HEADER as _DMUS_IO_WAVE_TRACK_HEADER
type LPDMUS_IO_WAVE_TRACK_HEADER as _DMUS_IO_WAVE_TRACK_HEADER ptr
type DMUS_IO_WAVE_PART_HEADER as _DMUS_IO_WAVE_PART_HEADER
type LPDMUS_IO_WAVE_PART_HEADER as _DMUS_IO_WAVE_PART_HEADER ptr
type DMUS_IO_WAVE_ITEM_HEADER as _DMUS_IO_WAVE_ITEM_HEADER
type LPDMUS_IO_WAVE_ITEM_HEADER as _DMUS_IO_WAVE_ITEM_HEADER ptr
type DMUS_IO_CONTAINER_HEADER as _DMUS_IO_CONTAINER_HEADER
type LPDMUS_IO_CONTAINER_HEADER as _DMUS_IO_CONTAINER_HEADER ptr
type DMUS_IO_CONTAINED_OBJECT_HEADER as _DMUS_IO_CONTAINED_OBJECT_HEADER
type LPDMUS_IO_CONTAINED_OBJECT_HEADER as _DMUS_IO_CONTAINED_OBJECT_HEADER ptr
type DMUS_IO_SEGMENT_HEADER as _DMUS_IO_SEGMENT_HEADER
type LPDMUS_IO_SEGMENT_HEADER as _DMUS_IO_SEGMENT_HEADER ptr
type DMUS_IO_TRACK_HEADER as _DMUS_IO_TRACK_HEADER
type LPDMUS_IO_TRACK_HEADER as _DMUS_IO_TRACK_HEADER ptr
type DMUS_IO_TRACK_EXTRAS_HEADER as _DMUS_IO_TRACK_EXTRAS_HEADER
type LPDMUS_IO_TRACK_EXTRAS_HEADER as _DMUS_IO_TRACK_EXTRAS_HEADER ptr
type DMUS_IO_REFERENCE as _DMUS_IO_REFERENCE
type LPDMUS_IO_REFERENCE as _DMUS_IO_REFERENCE ptr
type DMUS_IO_CHORDMAP as _DMUS_IO_CHORDMAP
type LPDMUS_IO_CHORDMAP as _DMUS_IO_CHORDMAP ptr
type DMUS_IO_CHORDMAP_SUBCHORD as _DMUS_IO_CHORDMAP_SUBCHORD
type LPDMUS_IO_CHORDMAP_SUBCHORD as _DMUS_IO_CHORDMAP_SUBCHORD ptr
type DMUS_IO_PERS_SUBCHORD as _DMUS_IO_CHORDMAP_SUBCHORD
type LPDMUS_IO_PERS_SUBCHORD as _DMUS_IO_CHORDMAP_SUBCHORD ptr
type DMUS_IO_CHORDENTRY as _DMUS_IO_CHORDENTRY
type LPDMUS_IO_CHORDENTRY as _DMUS_IO_CHORDENTRY ptr
type DMUS_IO_NEXTCHORD as _DMUS_IO_NEXTCHORD
type LPDMUS_IO_NEXTCHORD as _DMUS_IO_NEXTCHORD ptr
type DMUS_IO_CHORDMAP_SIGNPOST as _DMUS_IO_CHORDMAP_SIGNPOST
type LPDMUS_IO_CHORDMAP_SIGNPOST as _DMUS_IO_CHORDMAP_SIGNPOST ptr
type DMUS_IO_PERS_SIGNPOST as _DMUS_IO_CHORDMAP_SIGNPOST
type LPDMUS_IO_PERS_SIGNPOST as _DMUS_IO_CHORDMAP_SIGNPOST ptr
type DMUS_IO_SCRIPT_HEADER as _DMUS_IO_SCRIPT_HEADER
type LPDMUS_IO_SCRIPT_HEADER as _DMUS_IO_SCRIPT_HEADER ptr
type DMUS_IO_SIGNPOST as _DMUS_IO_SIGNPOST
type LPDMUS_IO_SIGNPOST as _DMUS_IO_SIGNPOST ptr
type DMUS_IO_MUTE as _DMUS_IO_MUTE
type LPDMUS_IO_MUTE as _DMUS_IO_MUTE ptr
type DMUS_IO_TIMESIGNATURE_ITEM as _DMUS_IO_TIMESIGNATURE_ITEM
type LPDMUS_IO_TIMESIGNATURE_ITEM as _DMUS_IO_TIMESIGNATURE_ITEM ptr
type DMUS_IO_VALID_START as _DMUS_IO_VALID_START
type LPDMUS_IO_VALID_START as _DMUS_IO_VALID_START ptr
type DMUS_IO_PLAY_MARKER as _DMUS_IO_PLAY_MARKER
type LPDMUS_IO_PLAY_MARKER as _DMUS_IO_PLAY_MARKER ptr
type DMUS_IO_SEGMENT_TRACK_HEADER as _DMUS_IO_SEGMENT_TRACK_HEADER
type LPDMUS_IO_SEGMENT_TRACK_HEADER as _DMUS_IO_SEGMENT_TRACK_HEADER ptr
type DMUS_IO_SEGMENT_ITEM_HEADER as _DMUS_IO_SEGMENT_ITEM_HEADER
type LPDMUS_IO_SEGMENT_ITEM_HEADER as _DMUS_IO_SEGMENT_ITEM_HEADER ptr
type DMUS_IO_SCRIPTTRACK_EVENTHEADER as _DMUS_IO_SCRIPTTRACK_EVENTHEADER
type LPDMUS_IO_SCRIPTTRACK_EVENTHEADER as _DMUS_IO_SCRIPTTRACK_EVENTHEADER ptr
type DMUS_IO_LYRICSTRACK_EVENTHEADER as _DMUS_IO_LYRICSTRACK_EVENTHEADER
type LPDMUS_IO_LYRICSTRACK_EVENTHEADER as _DMUS_IO_LYRICSTRACK_EVENTHEADER ptr
type DMUS_IO_PARAMCONTROLTRACK_OBJECTHEADER as _DMUS_IO_PARAMCONTROLTRACK_OBJECTHEADER
type LPDMUS_IO_PARAMCONTROLTRACK_OBJECTHEADER as _DMUS_IO_PARAMCONTROLTRACK_OBJECTHEADER ptr
type DMUS_IO_PARAMCONTROLTRACK_PARAMHEADER as _DMUS_IO_PARAMCONTROLTRACK_PARAMHEADER
type LPDMUS_IO_PARAMCONTROLTRACK_PARAMHEADER as _DMUS_IO_PARAMCONTROLTRACK_PARAMHEADER ptr
type DMUS_IO_PARAMCONTROLTRACK_CURVEINFO as _DMUS_IO_PARAMCONTROLTRACK_CURVEINFO
type LPDMUS_IO_PARAMCONTROLTRACK_CURVEINFO as _DMUS_IO_PARAMCONTROLTRACK_CURVEINFO ptr
type DSOUND_IO_DSBUFFERDESC as _DSOUND_IO_DSBUFFERDESC
type LPDSOUND_IO_DSBUFFERDESC as _DSOUND_IO_DSBUFFERDESC ptr
type DSOUND_IO_DSBUSID as _DSOUND_IO_DSBUSID
type LPDSOUND_IO_DSBUSID as _DSOUND_IO_DSBUSID ptr
type DSOUND_IO_3D as _DSOUND_IO_3D
type LPDSOUND_IO_3D as _DSOUND_IO_3D ptr
type DSOUND_IO_DXDMO_HEADER as _DSOUND_IO_DXDMO_HEADER
type LPDSOUND_IO_DXDMO_HEADER as _DSOUND_IO_DXDMO_HEADER ptr
type DSOUND_IO_DXDMO_DATA as _DSOUND_IO_DXDMO_DATA
type LPDSOUND_IO_DXDMO_DATA as _DSOUND_IO_DXDMO_DATA ptr

type _DMUS_IO_SEQ_ITEM
	mtTime as MUSIC_TIME
	mtDuration as MUSIC_TIME
	dwPChannel as DWORD
	nOffset as short
	bStatus as UBYTE
	bByte1 as UBYTE
	bByte2 as UBYTE
end type

type _DMUS_IO_CURVE_ITEM
	mtStart as MUSIC_TIME
	mtDuration as MUSIC_TIME
	mtResetDuration as MUSIC_TIME
	dwPChannel as DWORD
	nOffset as short
	nStartValue as short
	nEndValue as short
	nResetValue as short
	bType as UBYTE
	bCurveShape as UBYTE
	bCCData as UBYTE
	bFlags as UBYTE
	wParamType as WORD
	wMergeIndex as WORD
end type

type _DMUS_IO_TEMPO_ITEM
	lTime as MUSIC_TIME
	dblTempo as double
end type

type _DMUS_IO_SYSEX_ITEM
	mtTime as MUSIC_TIME
	dwPChannel as DWORD
	dwSysExLength as DWORD
end type

type _DMUS_RHYTHM_PARAM
	TimeSig as DMUS_TIMESIGNATURE
	dwRhythmPattern as DWORD
end type

type _DMUS_TEMPO_PARAM
	mtTime as MUSIC_TIME
	dblTempo as double
end type

type _DMUS_MUTE_PARAM
	dwPChannel as DWORD
	dwPChannelMap as DWORD
	fMute as WINBOOL
end type

type _DMUS_IO_TIMESIG field = 2
	bBeatsPerMeasure as UBYTE
	bBeat as UBYTE
	wGridsPerBeat as WORD
end type

type _DMUS_IO_STYLE field = 2
	timeSig as DMUS_IO_TIMESIG
	dblTempo as double
end type

type _DMUS_IO_VERSION field = 2
	dwVersionMS as DWORD
	dwVersionLS as DWORD
end type

type _DMUS_IO_PATTERN field = 2
	timeSig as DMUS_IO_TIMESIG
	bGrooveBottom as UBYTE
	bGrooveTop as UBYTE
	wEmbellishment as WORD
	wNbrMeasures as WORD
	bDestGrooveBottom as UBYTE
	bDestGrooveTop as UBYTE
	dwFlags as DWORD
end type

type _DMUS_IO_STYLEPART field = 2
	timeSig as DMUS_IO_TIMESIG
	dwVariationChoices(0 to 31) as DWORD
	guidPartID as GUID
	wNbrMeasures as WORD
	bPlayModeFlags as UBYTE
	bInvertUpper as UBYTE
	bInvertLower as UBYTE
	bPad(0 to 2) as UBYTE
	dwFlags as DWORD
end type

type _DMUS_IO_PARTREF field = 2
	guidPartID as GUID
	wLogicalPartID as WORD
	bVariationLockID as UBYTE
	bSubChordLevel as UBYTE
	bPriority as UBYTE
	bRandomVariation as UBYTE
	wPad as WORD
	dwPChannel as DWORD
end type

type _DMUS_IO_STYLENOTE field = 2
	mtGridStart as MUSIC_TIME
	dwVariation as DWORD
	mtDuration as MUSIC_TIME
	nTimeOffset as short
	wMusicValue as WORD
	bVelocity as UBYTE
	bTimeRange as UBYTE
	bDurRange as UBYTE
	bVelRange as UBYTE
	bInversionID as UBYTE
	bPlayModeFlags as UBYTE
	bNoteFlags as UBYTE
end type

type _DMUS_IO_STYLECURVE field = 2
	mtGridStart as MUSIC_TIME
	dwVariation as DWORD
	mtDuration as MUSIC_TIME
	mtResetDuration as MUSIC_TIME
	nTimeOffset as short
	nStartValue as short
	nEndValue as short
	nResetValue as short
	bEventType as UBYTE
	bCurveShape as UBYTE
	bCCData as UBYTE
	bFlags as UBYTE
	wParamType as WORD
	wMergeIndex as WORD
end type

type _DMUS_IO_STYLEMARKER field = 2
	mtGridStart as MUSIC_TIME
	dwVariation as DWORD
	wMarkerFlags as WORD
end type

type _DMUS_IO_STYLERESOLUTION field = 2
	dwVariation as DWORD
	wMusicValue as WORD
	bInversionID as UBYTE
	bPlayModeFlags as UBYTE
end type

type _DMUS_IO_STYLE_ANTICIPATION field = 2
	mtGridStart as MUSIC_TIME
	dwVariation as DWORD
	nTimeOffset as short
	bTimeRange as UBYTE
end type

type _DMUS_IO_MOTIFSETTINGS field = 2
	dwRepeats as DWORD
	mtPlayStart as MUSIC_TIME
	mtLoopStart as MUSIC_TIME
	mtLoopEnd as MUSIC_TIME
	dwResolution as DWORD
end type

type _DMUS_IO_CHORD
	wszName as wstring * 16
	mtTime as MUSIC_TIME
	wMeasure as WORD
	bBeat as UBYTE
	bFlags as UBYTE
end type

type _DMUS_IO_SUBCHORD
	dwChordPattern as DWORD
	dwScalePattern as DWORD
	dwInversionPoints as DWORD
	dwLevels as DWORD
	bChordRoot as UBYTE
	bScaleRoot as UBYTE
end type

type _DMUS_IO_COMMAND
	mtTime as MUSIC_TIME
	wMeasure as WORD
	bBeat as UBYTE
	bCommand as UBYTE
	bGrooveLevel as UBYTE
	bGrooveRange as UBYTE
	bRepeatMode as UBYTE
end type

type _DMUS_IO_TOOL_HEADER
	guidClassID as GUID
	lIndex as LONG
	cPChannels as DWORD
	ckid as FOURCC
	fccType as FOURCC
	dwPChannels(0 to 0) as DWORD
end type

type _DMUS_IO_PORTCONFIG_HEADER
	guidPort as GUID
	dwPChannelBase as DWORD
	dwPChannelCount as DWORD
	dwFlags as DWORD
end type

type _DMUS_IO_PCHANNELTOBUFFER_HEADER
	dwPChannelBase as DWORD
	dwPChannelCount as DWORD
	dwBufferCount as DWORD
	dwFlags as DWORD
end type

type _DMUS_IO_BUFFER_ATTRIBUTES_HEADER
	guidBufferID as GUID
	dwFlags as DWORD
end type

type _DMUS_IO_BAND_TRACK_HEADER
	bAutoDownload as WINBOOL
end type

type _DMUS_IO_BAND_ITEM_HEADER
	lBandTime as MUSIC_TIME
end type

type _DMUS_IO_BAND_ITEM_HEADER2
	lBandTimeLogical as MUSIC_TIME
	lBandTimePhysical as MUSIC_TIME
end type

type _DMUS_IO_INSTRUMENT
	dwPatch as DWORD
	dwAssignPatch as DWORD
	dwNoteRanges(0 to 3) as DWORD
	dwPChannel as DWORD
	dwFlags as DWORD
	bPan as UBYTE
	bVolume as UBYTE
	nTranspose as short
	dwChannelPriority as DWORD
	nPitchBendRange as short
end type

type _DMUS_IO_WAVE_HEADER
	rtReadAhead as REFERENCE_TIME
	dwFlags as DWORD
end type

type _DMUS_IO_WAVE_TRACK_HEADER
	lVolume as LONG
	dwFlags as DWORD
end type

type _DMUS_IO_WAVE_PART_HEADER
	lVolume as LONG
	dwVariations as DWORD
	dwPChannel as DWORD
	dwLockToPart as DWORD
	dwFlags as DWORD
	dwIndex as DWORD
end type

type _DMUS_IO_WAVE_ITEM_HEADER
	lVolume as LONG
	lPitch as LONG
	dwVariations as DWORD
	rtTime as REFERENCE_TIME
	rtStartOffset as REFERENCE_TIME
	rtReserved as REFERENCE_TIME
	rtDuration as REFERENCE_TIME
	mtLogicalTime as MUSIC_TIME
	dwLoopStart as DWORD
	dwLoopEnd as DWORD
	dwFlags as DWORD
	wVolumeRange as WORD
	wPitchRange as WORD
end type

type _DMUS_IO_CONTAINER_HEADER
	dwFlags as DWORD
end type

type _DMUS_IO_CONTAINED_OBJECT_HEADER
	guidClassID as GUID
	dwFlags as DWORD
	ckid as FOURCC
	fccType as FOURCC
end type

type _DMUS_IO_SEGMENT_HEADER
	dwRepeats as DWORD
	mtLength as MUSIC_TIME
	mtPlayStart as MUSIC_TIME
	mtLoopStart as MUSIC_TIME
	mtLoopEnd as MUSIC_TIME
	dwResolution as DWORD
	rtLength as REFERENCE_TIME
	dwFlags as DWORD
	dwReserved as DWORD
	rtLoopStart as REFERENCE_TIME
	rtLoopEnd as REFERENCE_TIME
	rtPlayStart as REFERENCE_TIME
end type

type _DMUS_IO_TRACK_HEADER
	guidClassID as GUID
	dwPosition as DWORD
	dwGroup as DWORD
	ckid as FOURCC
	fccType as FOURCC
end type

type _DMUS_IO_TRACK_EXTRAS_HEADER
	dwFlags as DWORD
	dwPriority as DWORD
end type

type _DMUS_IO_REFERENCE
	guidClassID as GUID
	dwValidData as DWORD
end type

type _DMUS_IO_CHORDMAP
	wszLoadName as wstring * 20
	dwScalePattern as DWORD
	dwFlags as DWORD
end type

type _DMUS_IO_CHORDMAP_SUBCHORD
	dwChordPattern as DWORD
	dwScalePattern as DWORD
	dwInvertPattern as DWORD
	bChordRoot as UBYTE
	bScaleRoot as UBYTE
	wCFlags as WORD
	dwLevels as DWORD
end type

type _DMUS_IO_CHORDENTRY
	dwFlags as DWORD
	wConnectionID as WORD
end type

type _DMUS_IO_NEXTCHORD
	dwFlags as DWORD
	nWeight as WORD
	wMinBeats as WORD
	wMaxBeats as WORD
	wConnectionID as WORD
end type

type _DMUS_IO_CHORDMAP_SIGNPOST
	dwChords as DWORD
	dwFlags as DWORD
end type

type _DMUS_IO_SCRIPT_HEADER
	dwFlags as DWORD
end type

type _DMUS_IO_SIGNPOST
	mtTime as MUSIC_TIME
	dwChords as DWORD
	wMeasure as WORD
end type

type _DMUS_IO_MUTE
	mtTime as MUSIC_TIME
	dwPChannel as DWORD
	dwPChannelMap as DWORD
end type

type _DMUS_IO_TIMESIGNATURE_ITEM
	lTime as MUSIC_TIME
	bBeatsPerMeasure as UBYTE
	bBeat as UBYTE
	wGridsPerBeat as WORD
end type

type _DMUS_IO_VALID_START
	mtTime as MUSIC_TIME
end type

type _DMUS_IO_PLAY_MARKER
	mtTime as MUSIC_TIME
end type

type _DMUS_IO_SEGMENT_TRACK_HEADER
	dwFlags as DWORD
end type

type _DMUS_IO_SEGMENT_ITEM_HEADER
	lTimeLogical as MUSIC_TIME
	lTimePhysical as MUSIC_TIME
	dwPlayFlags as DWORD
	dwFlags as DWORD
end type

type _DMUS_IO_SCRIPTTRACK_EVENTHEADER
	dwFlags as DWORD
	lTimeLogical as MUSIC_TIME
	lTimePhysical as MUSIC_TIME
end type

type _DMUS_IO_LYRICSTRACK_EVENTHEADER
	dwFlags as DWORD
	dwTimingFlags as DWORD
	lTimeLogical as MUSIC_TIME
	lTimePhysical as MUSIC_TIME
end type

type _DMUS_IO_PARAMCONTROLTRACK_OBJECTHEADER
	dwFlags as DWORD
	guidTimeFormat as GUID
	dwPChannel as DWORD
	dwStage as DWORD
	dwBuffer as DWORD
	guidObject as GUID
	dwIndex as DWORD
end type

type _DMUS_IO_PARAMCONTROLTRACK_PARAMHEADER
	dwFlags as DWORD
	dwIndex as DWORD
end type

type _DMUS_IO_PARAMCONTROLTRACK_CURVEINFO
	mtStartTime as MUSIC_TIME
	mtEndTime as MUSIC_TIME
	fltStartValue as single
	fltEndValue as single
	dwCurveType as DWORD
	dwFlags as DWORD
end type

type _DSOUND_IO_DSBUFFERDESC
	dwFlags as DWORD
	nChannels as WORD
	lVolume as LONG
	lPan as LONG
	dwReserved as DWORD
end type

type _DSOUND_IO_DSBUSID
	busid(0 to 0) as DWORD
end type

type _DSOUND_IO_3D
	guid3DAlgorithm as GUID
	ds3d as DS3DBUFFER
end type

type _DSOUND_IO_DXDMO_HEADER
	dwEffectFlags as DWORD
	guidDSFXClass as GUID
	guidReserved as GUID
	guidSendBuffer as GUID
	dwReserved as DWORD
end type

type _DSOUND_IO_DXDMO_DATA
	data(0 to 0) as DWORD
end type
