#ifndef __WXCLASSES_BI__
#define __WXCLASSES_BI__

type Virtual_Dispose as sub cdecl()

type _GridCellAutoWrapStringEditor as any
type _HtmlWindow as any
type _HtmlListBox as any
type _ListItemAttr as any
type _MDIParentFrame as any
type _Printout as any
type _TreeItemId as any
type _TreeItemData as any
type _TreeItemAttr as any
type _ArrayTreeItemIds as any
type _VListBox as any
type _VScrolledWindow as any
type _VisualAttributes as any

type _acceleratorentry as any
type _activateevent as any
type _app as any
type _ArrayInt as any
type _ArrayString as any
type _artprovider as any
type _bitmap as any
type _bitmapbutton as any
type _boxsizer as any
type _brush as any
type _button as any
type _CalendarDateAttr as any
type _caret as any
type _checkbox as any
type _childfocusevent as any
type _choice as any
type _choicedialog as any
type _clientdata as any
type _clipboard as any
type _closeevent as any
type _colour as any
type _colourdialog as any
type _combobox as any
type _commandevent as any
type _config as any
type _contextmenuevent as any
type _control as any
type _cursor as any
type _dataformat as any
type _dataobject as any
type _dc as any
type _dialog as any
type _dirdialog as any
type _display as any
type _displaychangedevent as any
type _dnd as any
type _docmanager as any
type _doctemplate as any
type _document as any
type _DropSource as any
type _DropTarget as any
type _eraseevent as any
type _event as any
type _evthandler as any
type _filedataobject as any
type _filedialog as any
type _FileDropTarget as any
type _findreplacedialog as any
type _flexgridsizer as any
type _focusevent as any
type _font as any
type _fontdialog as any
type _FontEnumerator as any
type _fontmisc as any
type _frame as any
type _gauge as any
type _gdicmn as any
type _gdiobject as any
type _global as any
type _grid as any
type _gridbagsizer as any
type _GridCellWorker as any
type _gridctrl as any
type _gridsizer as any
type _GridCellEditor as any
type _GridTableBase as any
type _GridCellAttrProvider as any
type _GridCellNumberEditor as any
type _GridCellBoolEditor as any
type _GridCellChoiceEditor as any
type _GridCellStringRenderer as any
type _GridCellBoolRenderer as any
type _GridCellRenderer as any
type _GridCellAutoWrapStringRenderer as any
type _helpevent as any
type _html as any
type _htmlhelpctrl as any
type _htmllbox as any
type _icon as any
type _iconizeevent as any
type _idleevent as any
type _image as any
type _imagelist as any
type _imghandler as any
type _initdialogevent as any
type _keyevent as any
type _laywin as any
type _listbook as any
type _listbox as any
type _listctrl as any
type _locale as any
type _local_events as any
type _log as any
type _maximizeevent as any
type _mdi as any
type _memorydc as any
type _menu as any
type _menubar as any
type _menuitem as any
type _messagedialog as any
type _miniframe as any
type _mousecapturechangedevent as any
type _mouseevent as any
type _moveevent as any
type _navigationkeyevent as any
type _ncpaintevent as any
type _notebook as any
type _notebooksizer as any
type _object as any
type _paintevent as any
type _palette as any
type _palettechangedevent as any
type _panel as any
type _pen as any
type _printdata as any
type _printdialog as any
type _printer as any
type _printpreview as any
type _progdlg as any
type _querynewpaletteevent as any
type _radiobox as any
type _radiobutton as any
type _region as any
type _Rect as any
type _sashwindow as any
type _scrollbar as any
type _scrolledwindow as any
type _setcursorevent as any
type _showevent as any
type _sizeevent as any
type _sizer as any
type _sizeritem as any
type _slider as any
type _spinbutton as any
type _spinctrl as any
type _splashscreen as any
type _splitterwindow as any
type _staticbitmap as any
type _staticbox as any
type _staticboxsizer as any
type _staticline as any
type _statictext as any
type _statusbar as any
type _styledtextctrl as any
type _syscolourchangedevent as any
type _systemsettings as any
type _tabctrl as any
type _textctrl as any
type _textdialog as any
type _TextDataObject as any
type _TextDropTarget as any
type _tipdialog as any
type _tipwindow as any
type _togglebutton as any
type _toolbar as any
type _tooltip as any
type _treectrl as any
type _updateuievent as any
type _validator as any
type _view as any
type _vlbox as any
type _vscroll as any
type _window as any
type _windowcreateevent as any
type _windowdestroyevent as any
type _wizard as any
type _wizardpagesimple as any
type _wxdatetime as any
type _wxstring as any
type _xmlresource as any

type wxCalendarHitTestResult as integer
type wxSystemFeature as integer
type wxTextCtrlHitTestResult as integer
type wxDCBase as any
type wxLayoutAlignment as integer
type wxLanguageInfo as any
type wxTextAttrAlignment as integer
type wxColourDatabase as any
type wxScrollBar as any
type wxUpdateUIEvent as any
type wxEvent as any
type wxHtmlFilterPlainText as any
type wxPreviewCanvas as any
type wxString as any
type wxTreeItemData as any
type wxWindowDisabler as any
type wxFindDialogEvent as any
type wxInitDialogEvent as any
type wxIcon as any
type wxHtmlFontCell as any
type wxHtmlSelection as any
type wxPreviewFrame as any
type wxHtmlTag as any
type wxMenuItem as any
type wxSashEdge as any
type wxImage as any
type wxIconBundle as any
type wxStaticBitmap as any
type wxEncodingConverter as any
type wxComboBox as any
type wxGridCellCoords as any
type wxHtmlFilter as any
type wxLayoutAlgorithm as any
type wxGridCellAttrProvider as any
type wxTipProvider as any
type wxLocale as any
type wxFontMapper as any
type wxNotebook as any
type wxBrushList as any
type wxGridCellAttr as any
type wxSize as integer
type wxListItem as any
type wxDragResult as integer
type wxFontEnumerator as integer
type wxIdleMode as integer
type wxNotebookSizer as integer
type wxFont as any
type wxCalendarDateBorder as integer
type wxArrayString as any
type wxTreeCtrl as any
type wxBufferedDC as any
type wxMenuBase as any
type wxFindReplaceData as any
type wxStaticLine as any
type wxValidator as any
type wxMouseEvent as any
type wxEraseEvent as any
type wxCloseEvent as any
type wxHtmlOpeningStatus as integer
type wxSashDragStatus as integer
type wxTreeEvent as integer
type wxGridCellCoordsArray as integer
type wxImageHistogram as integer
type wxView as integer
type wxWizardPage as integer
type wxDocument as integer
type wxHtmlEasyPrinting as integer
type wxLayoutOrientation as integer
type wxTextUrlEvent as integer
type wxPageSetupDialogData as integer
type wxPrintDialogData as integer
type wxPrinter as integer
type wxObject as integer
type wxFontEncoding as integer
type wxHtmlWinParser as integer
type wxHtmlParser as integer
type wxImageList as integer
type wxRadioBox as integer
type wxArtClient as integer
type wxDC as integer
type wxPrinterError as integer
type wxGridSizer as integer
type wxFlexGridSizer as integer
type wxCalendarCtrl as integer
type wxAcceleratorTable as integer
type wxImageHistogramEntry as integer
type wxRegionIterator as integer
type wxCaret as integer
type wxControl as integer
type wxHtmlHelpFrame as integer
type wxHtmlWidgetCell as integer
type wxTraceMask as integer
type wxDocTemplate as integer
type wxColourData as integer
type wxAcceleratorEntry as integer
type wxHtmlTagsModule as integer
type wxLog as integer
type wxRegionContain as integer
type wxSystemScreenType as integer
type wxMask as integer
type wxGridSizeEvent as integer
type wxActivateEvent as integer
type wxSizeEvent as integer
type wxIconizeEvent as integer
type wxIdleEvent as integer
type wxLogLevel as integer
type wxMaximizeEvent as integer
type wxMoveEvent as integer
type wxQueryNewPaletteEvent as integer
type wxWindowVariant as integer
type wxWindowCreateEvent as integer
type wxBrush as integer
type wxGridRangeSelectEvent as integer
type wxCalculateLayoutEvent as integer
type wxListEvent as integer
type wxStaticText as integer
type wxUpdateUIMode as integer
type wxInputStream as integer
type wxOutputStream as integer
type wxArrayInt as integer
type wxGauge as integer
type wxPrintout as integer
type wxMDIChildFrame as integer
type wxListItemAttr as integer
type wxTreeItemAttr as integer
type wxChoice as integer
type wxHelpSearchMode as integer
type wxGDIObject as integer
type wxDataObject as integer
type wxTextDataObject as integer
type wxFileDataObject as integer
type wxHtmlEntitiesParser as integer
type wxButton as integer
type wxBitmapButton as integer
type wxSpinButton as integer
type wxKeyEvent as integer
type wxPenList as integer
type wxNavigationKeyEvent as integer
type wxWindowDestroyEvent as integer
type wxFontData as integer
type wxClientData as integer
type wxStringClientData as integer
type wxPrintData as integer
type wxHtmlListBox as integer
type wxListBox as integer
type wxCheckListBox as integer
type wxSashEvent as integer
type wxVListBox as integer
type wxListbook as integer
type wxMiniFrame as integer
type wxPrintPreviewBase as integer
type wxFrame as integer
type wxQueryLayoutInfoEvent as integer
type wxStaticBox as integer
type wxHtmlURLType as integer
type wxSplashScreen as integer
type wxColour as integer
type wxFileSystem as integer
type wxPaintDC as integer
type wxListView as integer
type wxBufferedPaintDC as integer
type wxPrintPreview as integer
type wxApp as integer
type wxListCtrl as integer
type wxLayoutConstraints as integer
type wxSizer as integer
type wxBoxSizer as integer
type wxStaticBoxSizer as integer
type wxCursor as integer
type wxTreeItemId as integer
type wxGridBagSizer as integer
type wxGBPosition as integer
type wxGBSpan as integer
type wxHtmlContainerCell as integer
type wxNcPaintEvent as integer
type wxPaintEvent as integer
type wxSashEdgePosition as integer
type wxFileDropTarget as integer
type wxTextDropTarget as integer
type wxDropTarget as integer
type wxFSFile as integer
type wxClipboard as integer
type wxChar as integer
type wxConfigBase as integer
type wxPageSetupData as integer
type wxCalendarEvent as integer
type wxSetCursorEvent as integer
type wxCalendarDateAttr as integer
type wxRect as integer
type wxTextCtrl as integer
type wxBusyInfo as integer
type wxPen as integer
type wxMenu as integer
type wxDropSource as integer
type wxGBSizerItem as integer
type wxRadioButton as integer
type wxSizerItem as integer
type wxToggleButton as integer
type wxXmlResource as integer
type wxFontDialog as integer
type wxDirDialog as integer
type wxColourDialog as integer
type wxDialog as integer
type wxDateTime as integer
type wxDataFormat as integer
type wxPageSetupDialog as integer
type wxPrintDialog as integer
type wxSystemMetric as integer
type wxToolTip as integer
type wxBitmapList as integer
type wxNativeFontInfo as integer
type wxHtmlFilterHTML as integer
type wxEvtHandler as integer
type wxHtmlTagHandler as integer
type wxImageHandler as integer
type wxShowEvent as integer
type wxGridCellWorker as integer
type wxWizard as integer
type wxWindow as integer
type wxHtmlWindow as integer
type wxSashLayoutWindow as integer
type wxMDIClientWindow as integer
type wxSashWindow as integer
type wxScrolledWindow as integer
type wxSplashScreenWindow as integer
type wxSplitterWindow as integer
type wxTipWindow as integer
type wxVScrolledWindow as integer
type wxArrayTreeItemIds as integer
type wxList as integer
type wxDataObjectSimple as integer
type wxWindowID as integer
type wxArtID as integer
type wxClipboardLocker as integer
type wxSystemColour as integer
type wxCheckBoxState as integer
type wxCaretSuspend as integer
type wxWindowDC as integer
type wxGridCellBoolEditor as integer
type wxGridCellFloatEditor as integer
type wxGridCellNumberEditor as integer
type wxGridCellTextEditor as integer
type wxGridCellEditor as integer
type wxLanguage as integer
type wxSpinCtrl as integer
type wxBitmapType as integer
type wxListbookEvent as integer
type wxNotebookEvent as integer
type wxMemoryDC as integer
type wxGridCellAutoWrapStringRenderer as integer
type wxGridCellEnumRenderer as integer
type wxGridCellDateTimeRenderer as integer
type wxGridCellBoolRenderer as integer
type wxGridCellFloatRenderer as integer
type wxGridCellNumberRenderer as integer
type wxGridCellStringRenderer as integer
type wxGridCellRenderer as integer
type wxPoint as integer
type wxFindReplaceDialog as integer
type wxFileDialog as integer
type wxSingleChoiceDialog as integer
type wxMultiChoiceDialog as integer
type wxMessageDialog as integer
type wxProgressDialog as integer
type wxTextEntryDialog as integer
type wxHtmlLinkInfo as integer
type wxToolBarToolBase as integer
type wxNotebookBase as integer
type wxSlider as integer
type wxRegion as integer
type wxBackgroundStyle as integer
type wxPalette as integer
type wxGridEditorCreatedEvent as integer
type wxGridEvent as integer
type wxDisplayChangedEvent as integer
type wxMouseCaptureChangedEvent as integer
type wxPaletteChangedEvent as integer
type wxSysColourChangedEvent as integer
type wxWizardPageSimple as integer
type wxGridCellAutoWrapStringEditor as integer
type wxGridCellEnumEditor as integer
type wxGridCellChoiceEditor as integer
type wxGridTableBase as integer
type wxCheckBox as integer
type wxHtmlHelpController as integer
type wxCommandProcessor as integer
type wxHtmlProcessor as integer
type wxHtmlRenderingInfo as integer
type wxTreeItemIcon as integer
type wxClientDC as integer
type wxNotebookPage as integer
type wxTextCoord as integer
type wxFontList as integer
type wxHelpEvent as integer
type wxPanel as integer
type wxVisualAttributes as integer
type wxSpinEvent as integer
type wxHtmlCell as integer
type wxTextAttr as integer
type wxBitmap as integer
type wxContextMenuEvent as integer
type wxEventType as integer
type wxToolBar as integer
type wxCommandEvent as integer
type wxDocManager as integer
type wxHtmlColourCell as integer
type wxStatusBar as integer
type wxFocusEvent as integer
type wxChildFocusEvent as integer
type wxListCtrlCompare as integer
type wxDropFilesEvent as integer
type wxGrid as integer
type wxMDIParentFrame as integer
type wxHtmlWordCell as integer
type wxSystemFont as integer
type wxMenuBar as integer
type wxStyledTextCtrl as integer
type wxMemoryBuffer as integer
type wxStyledTextEvent as integer

#endif