''
''
'' defs -- header translated with help of SWIG FB wrapper
''
'' NOTICE: This file is part of the FreeBASIC Compiler package and can't
''         be included in other distributions without authorization.
''
''
#ifndef __wxc_defs_bi__
#define __wxc_defs_bi__

#ifdef __FB_WIN32__
 #define WXCALL stdcall
#else
 #define WXCALL
#endif

enum 
	wxUNKNOWN_PLATFORM
	wxCURSES
	wxXVIEW_X
	wxMOTIF_X
	wxCOSE_X
	wxNEXTSTEP
	wxMAC
	wxMAC_DARWIN
	wxBEOS
	wxGTK
	wxGTK_WIN32
	wxGTK_OS2
	wxGTK_BEOS
	wxGEOS
	wxOS2_PM
	wxWINDOWS
	wxMICROWINDOWS
	wxPENWINDOWS
	wxWINDOWS_NT
	wxWIN32S
	wxWIN95
	wxWIN386
	wxMGL_UNIX
	wxMGL_X
	wxMGL_WIN32
	wxMGL_OS2
	wxMGL_DOS
	wxWINDOWS_OS2
	wxUNIX
	wxX11
end enum

type wxCoord as integer
type wxFloat32 as single
type wxFloat64 as double
type wxDouble as double

#define wxBIG_ENDIAN 4321
#define wxLITTLE_ENDIAN 1234
#define wxPDP_ENDIAN 3412
#define wxBYTE_ORDER 1234

enum wxGeometryCentre
	wxCENTRE = &h0001
	wxCENTER = wxCENTRE
end enum

#define wxCENTER_FRAME &h0000
#define wxCENTRE_ON_SCREEN &h0002
#define wxCENTER_ON_SCREEN &h0002

enum wxOrientation
	wxHORIZONTAL = &h0004
	wxVERTICAL = &h0008
	wxBOTH = (wxVERTICAL or wxHORIZONTAL)
end enum

enum wxDirection
	wxLEFT = &h0010
	wxRIGHT = &h0020
	wxUP = &h0040
	wxDOWN = &h0080
	wxTOP = wxUP
	wxBOTTOM = wxDOWN
	wxNORTH = wxUP
	wxSOUTH = wxDOWN
	wxWEST = wxLEFT
	wxEAST = wxRIGHT
	wxALL = (wxUP or wxDOWN or wxRIGHT or wxLEFT)
end enum

enum wxAlignment
	wxALIGN_NOT = &h0000
	wxALIGN_CENTER_HORIZONTAL = &h0100
	wxALIGN_CENTRE_HORIZONTAL = wxALIGN_CENTER_HORIZONTAL
	wxALIGN_LEFT = wxALIGN_NOT
	wxALIGN_TOP = wxALIGN_NOT
	wxALIGN_RIGHT = &h0200
	wxALIGN_BOTTOM = &h0400
	wxALIGN_CENTER_VERTICAL = &h0800
	wxALIGN_CENTRE_VERTICAL = wxALIGN_CENTER_VERTICAL
	wxALIGN_CENTER = (wxALIGN_CENTER_HORIZONTAL or wxALIGN_CENTER_VERTICAL)
	wxALIGN_CENTRE = wxALIGN_CENTER
	wxALIGN_MASK = &h0f00
end enum

enum wxStretch
	wxSTRETCH_NOT = &h0000
	wxSHRINK = &h1000
	wxGROW = &h2000
	wxEXPAND = wxGROW
	wxSHAPED = &h4000
	wxADJUST_MINSIZE = &h8000
	wxTILE = &hc000
end enum

enum wxBorder
	wxBORDER_DEFAULT = 0
	wxBORDER_NONE = &h00200000
	wxBORDER_STATIC = &h01000000
	wxBORDER_SIMPLE = &h02000000
	wxBORDER_RAISED = &h04000000
	wxBORDER_SUNKEN = &h08000000
	wxBORDER_DOUBLE = &h10000000
	wxBORDER_MASK = &h1f200000
end enum

#define wxVSCROLL &h80000000
#define wxHSCROLL &h40000000
#define wxCAPTION &h20000000
#define wxNO_3D &h00800000
#define wxUSER_COLOURS &h00800000
#define wxALWAYS_SHOW_SB &h00800000
#define wxCLIP_CHILDREN &h00400000
#define wxCLIP_SIBLINGS &h20000000
#define wxTRANSPARENT_WINDOW &h00100000
#define wxTAB_TRAVERSAL &h00080000
#define wxWANTS_CHARS &h00040000
#define wxRETAINED &h00020000
#define wxBACKINGSTORE &h00020000
#define wxPOPUP_WINDOW &h00020000
#define wxNO_FULL_REPAINT_ON_RESIZE &h00010000
#define wxWS_EX_VALIDATE_RECURSIVELY &h00000001
#define wxWS_EX_BLOCK_EVENTS &h00000002
#define wxWS_EX_TRANSIENT &h00000004
#define wxFRAME_EX_CONTEXTHELP &h00000004
#define wxDIALOG_EX_CONTEXTHELP &h00000004
#define wxSTAY_ON_TOP &h8000
#define wxICONIZE &h4000
#define wxMINIMIZE &h4000
#define wxMAXIMIZE &h2000
#define wxSYSTEM_MENU &h0800
#define wxMINIMIZE_BOX &h0400
#define wxMAXIMIZE_BOX &h0200
#define wxTINY_CAPTION_HORIZ &h0100
#define wxTINY_CAPTION_VERT &h0080
#define wxRESIZE_BORDER &h0040
#define wxDIALOG_NO_PARENT &h0001
#define wxFRAME_NO_TASKBAR &h0002
#define wxFRAME_TOOL_WINDOW &h0004
#define wxFRAME_FLOAT_ON_PARENT &h0008
#define wxFRAME_SHAPED &h0010
#define wxRESIZE_BOX &h0200
#define wxTHICK_FRAME &h0040
#define wxDIALOG_MODAL &h0020
#define wxDIALOG_MODELESS &h0000
#define wxFRAME_NO_WINDOW_MENU &h0100
#define wxDEFAULT_FRAME_STYLE (&h0800 or &h0040 or &h0400 or &h0200 or &h20000000 or &h00400000)
#define wxDEFAULT_DIALOG_STYLE &h20000000
#define wxED_CLIENT_MARGIN &h0004
#define wxED_BUTTONS_BOTTOM &h0000
#define wxED_BUTTONS_RIGHT &h0002
#define wxED_STATIC_LINE &h0001
#define wxEXT_DIALOG_STYLE (&h20000000 or &h0004 or &h0001)
#define wxMB_DOCKABLE &h0001
#define wxMENU_TEAROFF &h0001
#define wxCOLOURED &h0800
#define wxFIXED_LENGTH &h0400
#define wxLB_SORT &h0010
#define wxLB_SINGLE &h0020
#define wxLB_MULTIPLE &h0040
#define wxLB_EXTENDED &h0080
#define wxLB_OWNERDRAW &h0100
#define wxLB_NEEDED_SB &h0200
#define wxLB_ALWAYS_SB &h0400
#define wxLB_HSCROLL &h40000000
#define wxLB_INT_HEIGHT &h0800
#define wxPROCESS_ENTER &h0400
#define wxPASSWORD &h0800
#define wxCB_SIMPLE &h0004
#define wxCB_SORT &h0008
#define wxCB_READONLY &h0010
#define wxCB_DROPDOWN &h0020
#define wxRA_LEFTTORIGHT &h0001
#define wxRA_TOPTOBOTTOM &h0002
#define wxRB_GROUP &h0004
#define wxRB_SINGLE &h0008
#define wxGA_PROGRESSBAR &h0010
#define wxGA_SMOOTH &h0020
#define wxSL_NOTIFY_DRAG &h0000
#define wxSL_TICKS &h0010
#define wxSL_AUTOTICKS &h0010
#define wxSL_LABELS &h0020
#define wxSL_LEFT &h0040
#define wxSL_TOP &h0080
#define wxSL_RIGHT &h0100
#define wxSL_BOTTOM &h0200
#define wxSL_BOTH &h0400
#define wxSL_SELRANGE &h0800
#define wxSP_ARROW_KEYS &h1000
#define wxSP_WRAP &h2000
#define wxSP_NOBORDER &h0000
#define wxSP_NOSASH &h0010
#define wxSP_BORDER &h0020
#define wxSP_PERMIT_UNSPLIT &h0040
#define wxSP_LIVE_UPDATE &h0080
#define wxSP_3DSASH &h0100
#define wxSP_3DBORDER &h0200
#define wxSP_FULLSASH &h0400
#define wxSP_3D (&h0200 or &h0100)
#define wxSP_SASH_AQUA &h0800
#define wxNB_FIXEDWIDTH &h0010
#define wxNB_TOP &h0000
#define wxNB_LEFT &h0020
#define wxNB_RIGHT &h0040
#define wxNB_BOTTOM &h0080
#define wxNB_MULTILINE &h0100
#define wxTC_RIGHTJUSTIFY &h0010
#define wxTC_FIXEDWIDTH &h0020
#define wxTC_TOP &h0000
#define wxTC_LEFT &h0020
#define wxTC_RIGHT &h0040
#define wxTC_BOTTOM &h0080
#define wxTC_MULTILINE &h0100
#define wxTC_OWNERDRAW &h0200
#define wxTB_3DBUTTONS &h0010
#define wxTB_FLAT &h0020
#define wxTB_DOCKABLE &h0040
#define wxTB_NOICONS &h0080
#define wxTB_TEXT &h0100
#define wxTB_NODIVIDER &h0200
#define wxTB_NOALIGN &h0400
#define wxST_SIZEGRIP &h0010
#define wxST_NO_AUTORESIZE &h0001
#define wxPD_CAN_ABORT &h0001
#define wxPD_APP_MODAL &h0002
#define wxPD_AUTO_HIDE &h0004
#define wxPD_ELAPSED_TIME &h0008
#define wxPD_ESTIMATED_TIME &h0010
#define wxPD_REMAINING_TIME &h0040
#define wxDD_NEW_DIR_BUTTON &h0080
#define wxYES &h00000002
#define wxOK &h00000004
#define wxNO &h00000008
#define wxYES_NO (&h00000002 or &h00000008)
#define wxCANCEL &h00000010
#define wxYES_DEFAULT &h00000000
#define wxNO_DEFAULT &h00000080
#define wxICON_EXCLAMATION &h00000100
#define wxICON_HAND &h00000200
#define wxICON_WARNING &h00000100
#define wxICON_ERROR &h00000200
#define wxICON_QUESTION &h00000400
#define wxICON_INFORMATION &h00000800
#define wxICON_STOP &h00000200
#define wxICON_ASTERISK &h00000800
#define wxICON_MASK (&h00000100 or &h00000200 or &h00000400 or &h00000800)
#define wxFORWARD &h00001000
#define wxBACKWARD &h00002000
#define wxRESET &h00004000
#define wxHELP &h00008000
#define wxMORE &h00010000
#define wxSETUP &h00020000

enum 
	wxID_ANY = -1
end enum

enum 
	wxID_SEPARATOR = -1
end enum

enum 
	wxID_LOWEST = 4999
	wxID_OPEN
	wxID_CLOSE
	wxID_NEW
	wxID_SAVE
	wxID_SAVEAS
	wxID_REVERT
	wxID_EXIT
	wxID_UNDO
	wxID_REDO
	wxID_HELP
	wxID_PRINT
	wxID_PRINT_SETUP
	wxID_PREVIEW
	wxID_ABOUT
	wxID_HELP_CONTENTS
	wxID_HELP_COMMANDS
	wxID_HELP_PROCEDURES
	wxID_HELP_CONTEXT
	wxID_CLOSE_ALL
	wxID_CUT = 5030
	wxID_COPY
	wxID_PASTE
	wxID_CLEAR
	wxID_FIND
	wxID_DUPLICATE
	wxID_SELECTALL
	wxID_FILE1 = 5050
	wxID_FILE2
	wxID_FILE3
	wxID_FILE4
	wxID_FILE5
	wxID_FILE6
	wxID_FILE7
	wxID_FILE8
	wxID_FILE9
	wxID_OK = 5100
	wxID_CANCEL
	wxID_APPLY
	wxID_YES
	wxID_NO
	wxID_STATIC
	wxID_FORWARD
	wxID_BACKWARD
	wxID_DEFAULT
	wxID_MORE
	wxID_SETUP
	wxID_RESET
	wxID_CONTEXT_HELP
	wxID_YESTOALL
	wxID_NOTOALL
	wxID_ABORT
	wxID_RETRY
	wxID_IGNORE
	wxID_SYSTEM_MENU = 5200
	wxID_CLOSE_FRAME
	wxID_MOVE_FRAME
	wxID_RESIZE_FRAME
	wxID_MAXIMIZE_FRAME
	wxID_ICONIZE_FRAME
	wxID_RESTORE_FRAME
	wxID_FILEDLGG = 5900
	wxID_HIGHEST = 5999
end enum

enum wxItemKind
	wxITEM_SEPARATOR = -1
	wxITEM_NORMAL
	wxITEM_CHECK
	wxITEM_RADIO
	wxITEM_MAX
end enum

enum wxHitTest
	wxHT_NOWHERE
	wxHT_SCROLLBAR_FIRST = wxHT_NOWHERE
	wxHT_SCROLLBAR_ARROW_LINE_1
	wxHT_SCROLLBAR_ARROW_LINE_2
	wxHT_SCROLLBAR_ARROW_PAGE_1
	wxHT_SCROLLBAR_ARROW_PAGE_2
	wxHT_SCROLLBAR_THUMB
	wxHT_SCROLLBAR_BAR_1
	wxHT_SCROLLBAR_BAR_2
	wxHT_SCROLLBAR_LAST
	wxHT_WINDOW_OUTSIDE
	wxHT_WINDOW_INSIDE
	wxHT_WINDOW_VERT_SCROLLBAR
	wxHT_WINDOW_HORZ_SCROLLBAR
	wxHT_WINDOW_CORNER
	wxHT_MAX
end enum

#define wxSIZE_AUTO_WIDTH &h0001
#define wxSIZE_AUTO_HEIGHT &h0002
#define wxSIZE_AUTO (&h0001 or &h0002)
#define wxSIZE_USE_EXISTING &h0000
#define wxSIZE_ALLOW_MINUS_ONE &h0004
#define wxSIZE_NO_ADJUSTMENTS &h0008

enum 
	wxDEFAULT = 70
	wxDECORATIVE
	wxROMAN
	wxSCRIPT
	wxSWISS
	wxMODERN
	wxTELETYPE
	wxVARIABLE = 80
	wxFIXED
	wxNORMAL = 90
	wxLIGHT
	wxBOLD
	wxITALIC
	wxSLANT
	wxSOLID = 100
	wxDOT
	wxLONG_DASH
	wxSHORT_DASH
	wxDOT_DASH
	wxUSER_DASH
	wxTRANSPARENT
	wxSTIPPLE_MASK_OPAQUE
	wxSTIPPLE_MASK
	wxSTIPPLE = 110
	wxBDIAGONAL_HATCH
	wxCROSSDIAG_HATCH
	wxFDIAGONAL_HATCH
	wxCROSS_HATCH
	wxHORIZONTAL_HATCH
	wxVERTICAL_HATCH
	wxJOIN_BEVEL = 120
	wxJOIN_MITER
	wxJOIN_ROUND
	wxCAP_ROUND = 130
	wxCAP_PROJECTING
	wxCAP_BUTT
end enum

enum form_ops_t
	wxCLEAR
	wxROP_BLACK = wxCLEAR
	wxBLIT_BLACKNESS = wxCLEAR
	wxXOR
	wxROP_XORPEN = wxXOR
	wxBLIT_SRCINVERT = wxXOR
	wxINVERT
	wxROP_NOT = wxINVERT
	wxBLIT_DSTINVERT = wxINVERT
	wxOR_REVERSE
	wxROP_MERGEPENNOT = wxOR_REVERSE
	wxBLIT_00DD0228 = wxOR_REVERSE
	wxAND_REVERSE
	wxROP_MASKPENNOT = wxAND_REVERSE
	wxBLIT_SRCERASE = wxAND_REVERSE
	wxCOPY
	wxROP_COPYPEN = wxCOPY
	wxBLIT_SRCCOPY = wxCOPY
	wxAND
	wxROP_MASKPEN = wxAND
	wxBLIT_SRCAND = wxAND
	wxAND_INVERT
	wxROP_MASKNOTPEN = wxAND_INVERT
	wxBLIT_00220326 = wxAND_INVERT
	wxNO_OP
	wxROP_NOP = wxNO_OP
	wxBLIT_00AA0029 = wxNO_OP
	wxNOR
	wxROP_NOTMERGEPEN = wxNOR
	wxBLIT_NOTSRCERASE = wxNOR
	wxEQUIV
	wxROP_NOTXORPEN = wxEQUIV
	wxBLIT_00990066 = wxEQUIV
	wxSRC_INVERT
	wxROP_NOTCOPYPEN = wxSRC_INVERT
	wxBLIT_NOTSCRCOPY = wxSRC_INVERT
	wxOR_INVERT
	wxROP_MERGENOTPEN = wxOR_INVERT
	wxBLIT_MERGEPAINT = wxOR_INVERT
	wxNAND
	wxROP_NOTMASKPEN = wxNAND
	wxBLIT_007700E6 = wxNAND
	wxOR
	wxROP_MERGEPEN = wxOR
	wxBLIT_SRCPAINT = wxOR
	wxSET
	wxROP_WHITE = wxSET
	wxBLIT_WHITENESS = wxSET
end enum


enum 
	wxFLOOD_SURFACE = 1
	wxFLOOD_BORDER
end enum

enum 
	wxODDEVEN_RULE = 1
	wxWINDING_RULE
end enum

enum 
	wxTOOL_TOP = 1
	wxTOOL_BOTTOM
	wxTOOL_LEFT
	wxTOOL_RIGHT
end enum

enum wxDataFormatId
	wxDF_INVALID = 0
	wxDF_TEXT = 1
	wxDF_BITMAP = 2
	wxDF_METAFILE = 3
	wxDF_SYLK = 4
	wxDF_DIF = 5
	wxDF_TIFF = 6
	wxDF_OEMTEXT = 7
	wxDF_DIB = 8
	wxDF_PALETTE = 9
	wxDF_PENDATA = 10
	wxDF_RIFF = 11
	wxDF_WAVE = 12
	wxDF_UNICODETEXT = 13
	wxDF_ENHMETAFILE = 14
	wxDF_FILENAME = 15
	wxDF_LOCALE = 16
	wxDF_PRIVATE = 20
	wxDF_HTML = 30
	wxDF_MAX
end enum

enum wxKeyCode
	WXK_BACK = 8
	WXK_TAB = 9
	WXK_RETURN = 13
	WXK_ESCAPE = 27
	WXK_SPACE = 32
	WXK_DELETE = 127
	WXK_START = 300
	WXK_LBUTTON
	WXK_RBUTTON
	WXK_CANCEL
	WXK_MBUTTON
	WXK_CLEAR
	WXK_SHIFT
	WXK_ALT
	WXK_CONTROL
	WXK_MENU
	WXK_PAUSE
	WXK_CAPITAL
	WXK_PRIOR
	WXK_NEXT
	WXK_END
	WXK_HOME
	WXK_LEFT
	WXK_UP
	WXK_RIGHT
	WXK_DOWN
	WXK_SELECT
	WXK_PRINT
	WXK_EXECUTE
	WXK_SNAPSHOT
	WXK_INSERT
	WXK_HELP
	WXK_NUMPAD0
	WXK_NUMPAD1
	WXK_NUMPAD2
	WXK_NUMPAD3
	WXK_NUMPAD4
	WXK_NUMPAD5
	WXK_NUMPAD6
	WXK_NUMPAD7
	WXK_NUMPAD8
	WXK_NUMPAD9
	WXK_MULTIPLY
	WXK_ADD
	WXK_SEPARATOR
	WXK_SUBTRACT
	WXK_DECIMAL
	WXK_DIVIDE
	WXK_F1
	WXK_F2
	WXK_F3
	WXK_F4
	WXK_F5
	WXK_F6
	WXK_F7
	WXK_F8
	WXK_F9
	WXK_F10
	WXK_F11
	WXK_F12
	WXK_F13
	WXK_F14
	WXK_F15
	WXK_F16
	WXK_F17
	WXK_F18
	WXK_F19
	WXK_F20
	WXK_F21
	WXK_F22
	WXK_F23
	WXK_F24
	WXK_NUMLOCK
	WXK_SCROLL
	WXK_PAGEUP
	WXK_PAGEDOWN
	WXK_NUMPAD_SPACE
	WXK_NUMPAD_TAB
	WXK_NUMPAD_ENTER
	WXK_NUMPAD_F1
	WXK_NUMPAD_F2
	WXK_NUMPAD_F3
	WXK_NUMPAD_F4
	WXK_NUMPAD_HOME
	WXK_NUMPAD_LEFT
	WXK_NUMPAD_UP
	WXK_NUMPAD_RIGHT
	WXK_NUMPAD_DOWN
	WXK_NUMPAD_PRIOR
	WXK_NUMPAD_PAGEUP
	WXK_NUMPAD_NEXT
	WXK_NUMPAD_PAGEDOWN
	WXK_NUMPAD_END
	WXK_NUMPAD_BEGIN
	WXK_NUMPAD_INSERT
	WXK_NUMPAD_DELETE
	WXK_NUMPAD_EQUAL
	WXK_NUMPAD_MULTIPLY
	WXK_NUMPAD_ADD
	WXK_NUMPAD_SEPARATOR
	WXK_NUMPAD_SUBTRACT
	WXK_NUMPAD_DECIMAL
	WXK_NUMPAD_DIVIDE
end enum

enum 
	wxMM_TEXT = 1
	wxMM_LOMETRIC
	wxMM_HIMETRIC
	wxMM_LOENGLISH
	wxMM_HIENGLISH
	wxMM_TWIPS
	wxMM_ISOTROPIC
	wxMM_ANISOTROPIC
	wxMM_POINTS
	wxMM_METRIC
end enum

enum wxPaperSize
	wxPAPER_NONE
	wxPAPER_LETTER
	wxPAPER_LEGAL
	wxPAPER_A4
	wxPAPER_CSHEET
	wxPAPER_DSHEET
	wxPAPER_ESHEET
	wxPAPER_LETTERSMALL
	wxPAPER_TABLOID
	wxPAPER_LEDGER
	wxPAPER_STATEMENT
	wxPAPER_EXECUTIVE
	wxPAPER_A3
	wxPAPER_A4SMALL
	wxPAPER_A5
	wxPAPER_B4
	wxPAPER_B5
	wxPAPER_FOLIO
	wxPAPER_QUARTO
	wxPAPER_10X14
	wxPAPER_11X17
	wxPAPER_NOTE
	wxPAPER_ENV_9
	wxPAPER_ENV_10
	wxPAPER_ENV_11
	wxPAPER_ENV_12
	wxPAPER_ENV_14
	wxPAPER_ENV_DL
	wxPAPER_ENV_C5
	wxPAPER_ENV_C3
	wxPAPER_ENV_C4
	wxPAPER_ENV_C6
	wxPAPER_ENV_C65
	wxPAPER_ENV_B4
	wxPAPER_ENV_B5
	wxPAPER_ENV_B6
	wxPAPER_ENV_ITALY
	wxPAPER_ENV_MONARCH
	wxPAPER_ENV_PERSONAL
	wxPAPER_FANFOLD_US
	wxPAPER_FANFOLD_STD_GERMAN
	wxPAPER_FANFOLD_LGL_GERMAN
	wxPAPER_ISO_B4
	wxPAPER_JAPANESE_POSTCARD
	wxPAPER_9X11
	wxPAPER_10X11
	wxPAPER_15X11
	wxPAPER_ENV_INVITE
	wxPAPER_LETTER_EXTRA
	wxPAPER_LEGAL_EXTRA
	wxPAPER_TABLOID_EXTRA
	wxPAPER_A4_EXTRA
	wxPAPER_LETTER_TRANSVERSE
	wxPAPER_A4_TRANSVERSE
	wxPAPER_LETTER_EXTRA_TRANSVERSE
	wxPAPER_A_PLUS
	wxPAPER_B_PLUS
	wxPAPER_LETTER_PLUS
	wxPAPER_A4_PLUS
	wxPAPER_A5_TRANSVERSE
	wxPAPER_B5_TRANSVERSE
	wxPAPER_A3_EXTRA
	wxPAPER_A5_EXTRA
	wxPAPER_B5_EXTRA
	wxPAPER_A2
	wxPAPER_A3_TRANSVERSE
	wxPAPER_A3_EXTRA_TRANSVERSE
end enum


#define wxPORTRAIT 1
#define wxLANDSCAPE 2

enum wxDuplexMode
	wxDUPLEX_SIMPLEX
	wxDUPLEX_HORIZONTAL
	wxDUPLEX_VERTICAL
end enum

#define wxPRINT_QUALITY_HIGH -1
#define wxPRINT_QUALITY_MEDIUM -2
#define wxPRINT_QUALITY_LOW -3
#define wxPRINT_QUALITY_DRAFT -4

type wxPrintQuality as integer

enum wxPrintMode
	wxPRINT_MODE_NONE = 0
	wxPRINT_MODE_PREVIEW = 1
	wxPRINT_MODE_FILE = 2
	wxPRINT_MODE_PRINTER = 3
end enum

#define wxUSE_PANGO 0


#ifndef __FB_WIN32__
    #define _WX_X_FONTLIKE
#endif

#ifdef __FB_WIN32__
#   define wxALL_FILES_PATTERN   wxT("*.*")
#   define wxALL_FILES           gettext_noop("All files (*.*)or*.*")
#else
#   define wxALL_FILES_PATTERN   wxT("*")
#   define wxALL_FILES           gettext_noop("All files (*)or*")
#endif

#define wxTE_NO_VSCROLL     &h0002
#define wxTE_AUTO_SCROLL    &h0008
#define wxTE_READONLY       &h0010
#define wxTE_MULTILINE      &h0020
#define wxTE_PROCESS_TAB    &h0040
#define wxTE_LEFT           &h0000                    
#define wxTE_CENTER         wxALIGN_CENTER_HORIZONTAL 
#define wxTE_RIGHT          wxALIGN_RIGHT             
#define wxTE_CENTRE         wxTE_CENTER
#define wxTE_RICH           &h0080
#define wxTE_PROCESS_ENTER  &h0400
#define wxTE_PASSWORD       &h0800
#define wxTE_AUTO_URL       &h1000
#define wxTE_NOHIDESEL      &h2000
#define wxTE_DONTWRAP       wxHSCROLL
#define wxTE_LINEWRAP       &h4000
#define wxTE_WORDWRAP       &h0000  
#define wxTE_RICH2          &h8000

enum wxBitmapType
    wxBITMAP_TYPE_INVALID          
    wxBITMAP_TYPE_BMP
    wxBITMAP_TYPE_BMP_RESOURCE
    wxBITMAP_TYPE_RESOURCE = wxBITMAP_TYPE_BMP_RESOURCE
    wxBITMAP_TYPE_ICO
    wxBITMAP_TYPE_ICO_RESOURCE
    wxBITMAP_TYPE_CUR
    wxBITMAP_TYPE_CUR_RESOURCE
    wxBITMAP_TYPE_XBM
    wxBITMAP_TYPE_XBM_DATA
    wxBITMAP_TYPE_XPM
    wxBITMAP_TYPE_XPM_DATA
    wxBITMAP_TYPE_TIF
    wxBITMAP_TYPE_TIF_RESOURCE
    wxBITMAP_TYPE_GIF
    wxBITMAP_TYPE_GIF_RESOURCE
    wxBITMAP_TYPE_PNG
    wxBITMAP_TYPE_PNG_RESOURCE
    wxBITMAP_TYPE_JPEG
    wxBITMAP_TYPE_JPEG_RESOURCE
    wxBITMAP_TYPE_PNM
    wxBITMAP_TYPE_PNM_RESOURCE
    wxBITMAP_TYPE_PCX
    wxBITMAP_TYPE_PCX_RESOURCE
    wxBITMAP_TYPE_PICT
    wxBITMAP_TYPE_PICT_RESOURCE
    wxBITMAP_TYPE_ICON
    wxBITMAP_TYPE_ICON_RESOURCE
    wxBITMAP_TYPE_ANI
    wxBITMAP_TYPE_IFF
    wxBITMAP_TYPE_MACCURSOR
    wxBITMAP_TYPE_MACCURSOR_RESOURCE
    wxBITMAP_TYPE_ANY = 50
end enum

enum wxStockCursor
    wxCURSOR_NONE          
    wxCURSOR_ARROW
    wxCURSOR_RIGHT_ARROW
    wxCURSOR_BULLSEYE
    wxCURSOR_CHAR
    wxCURSOR_CROSS
    wxCURSOR_HAND
    wxCURSOR_IBEAM
    wxCURSOR_LEFT_BUTTON
    wxCURSOR_MAGNIFIER
    wxCURSOR_MIDDLE_BUTTON
    wxCURSOR_NO_ENTRY
    wxCURSOR_PAINT_BRUSH
    wxCURSOR_PENCIL
    wxCURSOR_POINT_LEFT
    wxCURSOR_POINT_RIGHT
    wxCURSOR_QUESTION_ARROW
    wxCURSOR_RIGHT_BUTTON
    wxCURSOR_SIZENESW
    wxCURSOR_SIZENS
    wxCURSOR_SIZENWSE
    wxCURSOR_SIZEWE
    wxCURSOR_SIZING
    wxCURSOR_SPRAYCAN
    wxCURSOR_WAIT
    wxCURSOR_WATCH
    wxCURSOR_BLANK
#ifndef __FB_WIN32__
    wxCURSOR_DEFAULT 
#endif
#ifndef __FB_WIN32__
        wxCURSOR_CROSS_REVERSE
    wxCURSOR_DOUBLE_ARROW
    wxCURSOR_BASED_ARROW_UP
    wxCURSOR_BASED_ARROW_DOWN
#endif 
    wxCURSOR_ARROWWAIT
    wxCURSOR_MAX
end enum

#ifdef __FB_WIN32__
    #define wxCURSOR_DEFAULT wxCURSOR_ARROW
#endif

#define wxSPLASH_CENTRE_ON_PARENT   &h01
#define wxSPLASH_CENTRE_ON_SCREEN   &h02
#define wxSPLASH_NO_CENTRE          &h00
#define wxSPLASH_TIMEOUT            &h04
#define wxSPLASH_NO_TIMEOUT         &h00

enum wxFontEncoding
    wxFONTENCODING_SYSTEM = -1     
    wxFONTENCODING_DEFAULT         
    wxFONTENCODING_ISO8859_1       
    wxFONTENCODING_ISO8859_2       
    wxFONTENCODING_ISO8859_3       
    wxFONTENCODING_ISO8859_4       
    wxFONTENCODING_ISO8859_5       
    wxFONTENCODING_ISO8859_6       
    wxFONTENCODING_ISO8859_7       
    wxFONTENCODING_ISO8859_8       
    wxFONTENCODING_ISO8859_9       
    wxFONTENCODING_ISO8859_10      
    wxFONTENCODING_ISO8859_11      
    wxFONTENCODING_ISO8859_12      
    wxFONTENCODING_ISO8859_13      
    wxFONTENCODING_ISO8859_14      
    wxFONTENCODING_ISO8859_15      
    wxFONTENCODING_ISO8859_MAX
    wxFONTENCODING_KOI8            
    wxFONTENCODING_ALTERNATIVE     
    wxFONTENCODING_BULGARIAN       
    wxFONTENCODING_CP437           
    wxFONTENCODING_CP850           
    wxFONTENCODING_CP852           
    wxFONTENCODING_CP855           
    wxFONTENCODING_CP866           
    wxFONTENCODING_CP874           
    wxFONTENCODING_CP932           
    wxFONTENCODING_CP936           
    wxFONTENCODING_CP949           
    wxFONTENCODING_CP950           
    wxFONTENCODING_CP1250          
    wxFONTENCODING_CP1251          
    wxFONTENCODING_CP1252          
    wxFONTENCODING_CP1253          
    wxFONTENCODING_CP1254          
    wxFONTENCODING_CP1255          
    wxFONTENCODING_CP1256          
    wxFONTENCODING_CP1257          
    wxFONTENCODING_CP12_MAX
    wxFONTENCODING_UTF7            
    wxFONTENCODING_UTF8            
    wxFONTENCODING_GB2312 = wxFONTENCODING_CP936 
    wxFONTENCODING_BIG5 = wxFONTENCODING_CP950   
    wxFONTENCODING_SHIFT_JIS = wxFONTENCODING_CP932  
    wxFONTENCODING_EUC_JP = wxFONTENCODING_UTF8 + 1  
    wxFONTENCODING_UNICODE         
    wxFONTENCODING_MAX
end enum

enum wxFontFamily
    wxFONTFAMILY_DEFAULT = wxDEFAULT
    wxFONTFAMILY_DECORATIVE = wxDECORATIVE
    wxFONTFAMILY_ROMAN = wxROMAN
    wxFONTFAMILY_SCRIPT = wxSCRIPT
    wxFONTFAMILY_SWISS = wxSWISS
    wxFONTFAMILY_MODERN = wxMODERN
    wxFONTFAMILY_TELETYPE = wxTELETYPE
    wxFONTFAMILY_MAX
    wxFONTFAMILY_UNKNOWN = wxFONTFAMILY_MAX
end enum

enum wxFontStyle
    wxFONTSTYLE_NORMAL = wxNORMAL
    wxFONTSTYLE_ITALIC = wxITALIC
    wxFONTSTYLE_SLANT = wxSLANT
    wxFONTSTYLE_MAX
end enum

enum wxFontWeight
    wxFONTWEIGHT_NORMAL = wxNORMAL
    wxFONTWEIGHT_LIGHT = wxLIGHT
    wxFONTWEIGHT_BOLD = wxBOLD
    wxFONTWEIGHT_MAX
end enum

#ifndef wxSTC_USE_POPUP
#define wxSTC_USE_POPUP 1
#endif

#define wxSTC_INVALID_POSITION -1
#define wxSTC_START 2000
#define wxSTC_OPTIONAL_START 3000
#define wxSTC_LEXER_START 4000
#define wxSTC_WS_INVISIBLE 0
#define wxSTC_WS_VISIBLEALWAYS 1
#define wxSTC_WS_VISIBLEAFTERINDENT 2
#define wxSTC_EOL_CRLF 0
#define wxSTC_EOL_CR 1
#define wxSTC_EOL_LF 2
#define wxSTC_CP_UTF8 65001
#define wxSTC_CP_DBCS 1
#define wxSTC_MARKER_MAX 31
#define wxSTC_MARK_CIRCLE 0
#define wxSTC_MARK_ROUNDRECT 1
#define wxSTC_MARK_ARROW 2
#define wxSTC_MARK_SMALLRECT 3
#define wxSTC_MARK_SHORTARROW 4
#define wxSTC_MARK_EMPTY 5
#define wxSTC_MARK_ARROWDOWN 6
#define wxSTC_MARK_MINUS 7
#define wxSTC_MARK_PLUS 8
#define wxSTC_MARK_VLINE 9
#define wxSTC_MARK_LCORNER 10
#define wxSTC_MARK_TCORNER 11
#define wxSTC_MARK_BOXPLUS 12
#define wxSTC_MARK_BOXPLUSCONNECTED 13
#define wxSTC_MARK_BOXMINUS 14
#define wxSTC_MARK_BOXMINUSCONNECTED 15
#define wxSTC_MARK_LCORNERCURVE 16
#define wxSTC_MARK_TCORNERCURVE 17
#define wxSTC_MARK_CIRCLEPLUS 18
#define wxSTC_MARK_CIRCLEPLUSCONNECTED 19
#define wxSTC_MARK_CIRCLEMINUS 20
#define wxSTC_MARK_CIRCLEMINUSCONNECTED 21
#define wxSTC_MARK_BACKGROUND 22
#define wxSTC_MARK_DOTDOTDOT 23
#define wxSTC_MARK_ARROWS 24
#define wxSTC_MARK_PIXMAP 25
#define wxSTC_MARK_CHARACTER 10000
#define wxSTC_MARKNUM_FOLDEREND 25
#define wxSTC_MARKNUM_FOLDEROPENMID 26
#define wxSTC_MARKNUM_FOLDERMIDTAIL 27
#define wxSTC_MARKNUM_FOLDERTAIL 28
#define wxSTC_MARKNUM_FOLDERSUB 29
#define wxSTC_MARKNUM_FOLDER 30
#define wxSTC_MARKNUM_FOLDEROPEN 31
#define wxSTC_MASK_FOLDERS &hFE000000
#define wxSTC_MARGIN_SYMBOL 0
#define wxSTC_MARGIN_NUMBER 1
#define wxSTC_STYLE_DEFAULT 32
#define wxSTC_STYLE_LINENUMBER 33
#define wxSTC_STYLE_BRACELIGHT 34
#define wxSTC_STYLE_BRACEBAD 35
#define wxSTC_STYLE_CONTROLCHAR 36
#define wxSTC_STYLE_INDENTGUIDE 37
#define wxSTC_STYLE_LASTPREDEFINED 39
#define wxSTC_STYLE_MAX 127
#define wxSTC_CHARSET_ANSI 0
#define wxSTC_CHARSET_DEFAULT 1
#define wxSTC_CHARSET_BALTIC 186
#define wxSTC_CHARSET_CHINESEBIG5 136
#define wxSTC_CHARSET_EASTEUROPE 238
#define wxSTC_CHARSET_GB2312 134
#define wxSTC_CHARSET_GREEK 161
#define wxSTC_CHARSET_HANGUL 129
#define wxSTC_CHARSET_MAC 77
#define wxSTC_CHARSET_OEM 255
#define wxSTC_CHARSET_RUSSIAN 204
#define wxSTC_CHARSET_SHIFTJIS 128
#define wxSTC_CHARSET_SYMBOL 2
#define wxSTC_CHARSET_TURKISH 162
#define wxSTC_CHARSET_JOHAB 130
#define wxSTC_CHARSET_HEBREW 177
#define wxSTC_CHARSET_ARABIC 178
#define wxSTC_CHARSET_VIETNAMESE 163
#define wxSTC_CHARSET_THAI 222
#define wxSTC_CASE_MIXED 0
#define wxSTC_CASE_UPPER 1
#define wxSTC_CASE_LOWER 2
#define wxSTC_INDIC_MAX 7
#define wxSTC_INDIC_PLAIN 0
#define wxSTC_INDIC_SQUIGGLE 1
#define wxSTC_INDIC_TT 2
#define wxSTC_INDIC_DIAGONAL 3
#define wxSTC_INDIC_STRIKE 4
#define wxSTC_INDIC_HIDDEN 5
#define wxSTC_INDIC0_MASK &h20
#define wxSTC_INDIC1_MASK &h40
#define wxSTC_INDIC2_MASK &h80
#define wxSTC_INDICS_MASK &hE0
#define wxSTC_PRINT_NORMAL 0
#define wxSTC_PRINT_INVERTLIGHT 1
#define wxSTC_PRINT_BLACKONWHITE 2
#define wxSTC_PRINT_COLOURONWHITE 3
#define wxSTC_PRINT_COLOURONWHITEDEFAULTBG 4
#define wxSTC_FIND_WHOLEWORD 2
#define wxSTC_FIND_MATCHCASE 4
#define wxSTC_FIND_WORDSTART &h00100000
#define wxSTC_FIND_REGEXP &h00200000
#define wxSTC_FIND_POSIX &h00400000
#define wxSTC_FOLDLEVELBASE &h400
#define wxSTC_FOLDLEVELWHITEFLAG &h1000
#define wxSTC_FOLDLEVELHEADERFLAG &h2000
#define wxSTC_FOLDLEVELBOXHEADERFLAG &h4000
#define wxSTC_FOLDLEVELBOXFOOTERFLAG &h8000
#define wxSTC_FOLDLEVELCONTRACTED &h10000
#define wxSTC_FOLDLEVELUNINDENT &h20000
#define wxSTC_FOLDLEVELNUMBERMASK &h0FFF
#define wxSTC_FOLDFLAG_LINEBEFORE_EXPANDED &h0002
#define wxSTC_FOLDFLAG_LINEBEFORE_CONTRACTED &h0004
#define wxSTC_FOLDFLAG_LINEAFTER_EXPANDED &h0008
#define wxSTC_FOLDFLAG_LINEAFTER_CONTRACTED &h0010
#define wxSTC_FOLDFLAG_LEVELNUMBERS &h0040
#define wxSTC_FOLDFLAG_BOX &h0001
#define wxSTC_TIME_FOREVER 10000000
#define wxSTC_WRAP_NONE 0
#define wxSTC_WRAP_WORD 1
#define wxSTC_CACHE_NONE 0
#define wxSTC_CACHE_CARET 1
#define wxSTC_CACHE_PAGE 2
#define wxSTC_CACHE_DOCUMENT 3
#define wxSTC_EDGE_NONE 0
#define wxSTC_EDGE_LINE 1
#define wxSTC_EDGE_BACKGROUND 2
#define wxSTC_CURSORNORMAL -1
#define wxSTC_CURSORWAIT 4
#define wxSTC_VISIBLE_SLOP &h01
#define wxSTC_VISIBLE_STRICT &h04
#define wxSTC_CARET_SLOP &h01
#define wxSTC_CARET_STRICT &h04
#define wxSTC_CARET_JUMPS &h10
#define wxSTC_CARET_EVEN &h08
#define wxSTC_KEYWORDSET_MAX 8
#define wxSTC_MOD_INSERTTEXT &h1
#define wxSTC_MOD_DELETETEXT &h2
#define wxSTC_MOD_CHANGESTYLE &h4
#define wxSTC_MOD_CHANGEFOLD &h8
#define wxSTC_PERFORMED_USER &h10
#define wxSTC_PERFORMED_UNDO &h20
#define wxSTC_PERFORMED_REDO &h40
#define wxSTC_LASTSTEPINUNDOREDO &h100
#define wxSTC_MOD_CHANGEMARKER &h200
#define wxSTC_MOD_BEFOREINSERT &h400
#define wxSTC_MOD_BEFOREDELETE &h800
#define wxSTC_MODEVENTMASKALL &hF77
#define wxSTC_KEY_DOWN 300
#define wxSTC_KEY_UP 301
#define wxSTC_KEY_LEFT 302
#define wxSTC_KEY_RIGHT 303
#define wxSTC_KEY_HOME 304
#define wxSTC_KEY_END 305
#define wxSTC_KEY_PRIOR 306
#define wxSTC_KEY_NEXT 307
#define wxSTC_KEY_DELETE 308
#define wxSTC_KEY_INSERT 309
#define wxSTC_KEY_ESCAPE 7
#define wxSTC_KEY_BACK 8
#define wxSTC_KEY_TAB 9
#define wxSTC_KEY_RETURN 13
#define wxSTC_KEY_ADD 310
#define wxSTC_KEY_SUBTRACT 311
#define wxSTC_KEY_DIVIDE 312
#define wxSTC_SCMOD_SHIFT 1
#define wxSTC_SCMOD_CTRL 2
#define wxSTC_SCMOD_ALT 4
#define wxSTC_LEX_CONTAINER 0
#define wxSTC_LEX_NULL 1
#define wxSTC_LEX_PYTHON 2
#define wxSTC_LEX_CPP 3
#define wxSTC_LEX_HTML 4
#define wxSTC_LEX_XML 5
#define wxSTC_LEX_PERL 6
#define wxSTC_LEX_SQL 7
#define wxSTC_LEX_VB 8
#define wxSTC_LEX_PROPERTIES 9
#define wxSTC_LEX_ERRORLIST 10
#define wxSTC_LEX_MAKEFILE 11
#define wxSTC_LEX_BATCH 12
#define wxSTC_LEX_XCODE 13
#define wxSTC_LEX_LATEX 14
#define wxSTC_LEX_LUA 15
#define wxSTC_LEX_DIFF 16
#define wxSTC_LEX_CONF 17
#define wxSTC_LEX_PASCAL 18
#define wxSTC_LEX_AVE 19
#define wxSTC_LEX_ADA 20
#define wxSTC_LEX_LISP 21
#define wxSTC_LEX_RUBY 22
#define wxSTC_LEX_EIFFEL 23
#define wxSTC_LEX_EIFFELKW 24
#define wxSTC_LEX_TCL 25
#define wxSTC_LEX_NNCRONTAB 26
#define wxSTC_LEX_BULLANT 27
#define wxSTC_LEX_VBSCRIPT 28
#define wxSTC_LEX_ASP 29
#define wxSTC_LEX_PHP 30
#define wxSTC_LEX_BAAN 31
#define wxSTC_LEX_MATLAB 32
#define wxSTC_LEX_SCRIPTOL 33
#define wxSTC_LEX_ASM 34
#define wxSTC_LEX_CPPNOCASE 35
#define wxSTC_LEX_FORTRAN 36
#define wxSTC_LEX_F77 37
#define wxSTC_LEX_CSS 38
#define wxSTC_LEX_POV 39
#define wxSTC_LEX_LOUT 40
#define wxSTC_LEX_ESCRIPT 41
#define wxSTC_LEX_PS 42
#define wxSTC_LEX_NSIS 43
#define wxSTC_LEX_MMIXAL 44
#define wxSTC_LEX_AUTOMATIC 1000
#define wxSTC_P_DEFAULT 0
#define wxSTC_P_COMMENTLINE 1
#define wxSTC_P_NUMBER 2
#define wxSTC_P_STRING 3
#define wxSTC_P_CHARACTER 4
#define wxSTC_P_WORD 5
#define wxSTC_P_TRIPLE 6
#define wxSTC_P_TRIPLEDOUBLE 7
#define wxSTC_P_CLASSNAME 8
#define wxSTC_P_DEFNAME 9
#define wxSTC_P_OPERATOR 10
#define wxSTC_P_IDENTIFIER 11
#define wxSTC_P_COMMENTBLOCK 12
#define wxSTC_P_STRINGEOL 13
#define wxSTC_C_DEFAULT 0
#define wxSTC_C_COMMENT 1
#define wxSTC_C_COMMENTLINE 2
#define wxSTC_C_COMMENTDOC 3
#define wxSTC_C_NUMBER 4
#define wxSTC_C_WORD 5
#define wxSTC_C_STRING 6
#define wxSTC_C_CHARACTER 7
#define wxSTC_C_UUID 8
#define wxSTC_C_PREPROCESSOR 9
#define wxSTC_C_OPERATOR 10
#define wxSTC_C_IDENTIFIER 11
#define wxSTC_C_STRINGEOL 12
#define wxSTC_C_VERBATIM 13
#define wxSTC_C_REGEX 14
#define wxSTC_C_COMMENTLINEDOC 15
#define wxSTC_C_WORD2 16
#define wxSTC_C_COMMENTDOCKEYWORD 17
#define wxSTC_C_COMMENTDOCKEYWORDERROR 18
#define wxSTC_C_GLOBALCLASS 19
#define wxSTC_H_DEFAULT 0
#define wxSTC_H_TAG 1
#define wxSTC_H_TAGUNKNOWN 2
#define wxSTC_H_ATTRIBUTE 3
#define wxSTC_H_ATTRIBUTEUNKNOWN 4
#define wxSTC_H_NUMBER 5
#define wxSTC_H_DOUBLESTRING 6
#define wxSTC_H_SINGLESTRING 7
#define wxSTC_H_OTHER 8
#define wxSTC_H_COMMENT 9
#define wxSTC_H_ENTITY 10
#define wxSTC_H_TAGEND 11
#define wxSTC_H_XMLSTART 12
#define wxSTC_H_XMLEND 13
#define wxSTC_H_SCRIPT 14
#define wxSTC_H_ASP 15
#define wxSTC_H_ASPAT 16
#define wxSTC_H_CDATA 17
#define wxSTC_H_QUESTION 18
#define wxSTC_H_VALUE 19
#define wxSTC_H_XCCOMMENT 20
#define wxSTC_H_SGML_DEFAULT 21
#define wxSTC_H_SGML_COMMAND 22
#define wxSTC_H_SGML_1ST_PARAM 23
#define wxSTC_H_SGML_DOUBLESTRING 24
#define wxSTC_H_SGML_SIMPLESTRING 25
#define wxSTC_H_SGML_ERROR 26
#define wxSTC_H_SGML_SPECIAL 27
#define wxSTC_H_SGML_ENTITY 28
#define wxSTC_H_SGML_COMMENT 29
#define wxSTC_H_SGML_1ST_PARAM_COMMENT 30
#define wxSTC_H_SGML_BLOCK_DEFAULT 31
#define wxSTC_HJ_START 40
#define wxSTC_HJ_DEFAULT 41
#define wxSTC_HJ_COMMENT 42
#define wxSTC_HJ_COMMENTLINE 43
#define wxSTC_HJ_COMMENTDOC 44
#define wxSTC_HJ_NUMBER 45
#define wxSTC_HJ_WORD 46
#define wxSTC_HJ_KEYWORD 47
#define wxSTC_HJ_DOUBLESTRING 48
#define wxSTC_HJ_SINGLESTRING 49
#define wxSTC_HJ_SYMBOLS 50
#define wxSTC_HJ_STRINGEOL 51
#define wxSTC_HJ_REGEX 52
#define wxSTC_HJA_START 55
#define wxSTC_HJA_DEFAULT 56
#define wxSTC_HJA_COMMENT 57
#define wxSTC_HJA_COMMENTLINE 58
#define wxSTC_HJA_COMMENTDOC 59
#define wxSTC_HJA_NUMBER 60
#define wxSTC_HJA_WORD 61
#define wxSTC_HJA_KEYWORD 62
#define wxSTC_HJA_DOUBLESTRING 63
#define wxSTC_HJA_SINGLESTRING 64
#define wxSTC_HJA_SYMBOLS 65
#define wxSTC_HJA_STRINGEOL 66
#define wxSTC_HJA_REGEX 67
#define wxSTC_HB_START 70
#define wxSTC_HB_DEFAULT 71
#define wxSTC_HB_COMMENTLINE 72
#define wxSTC_HB_NUMBER 73
#define wxSTC_HB_WORD 74
#define wxSTC_HB_STRING 75
#define wxSTC_HB_IDENTIFIER 76
#define wxSTC_HB_STRINGEOL 77
#define wxSTC_HBA_START 80
#define wxSTC_HBA_DEFAULT 81
#define wxSTC_HBA_COMMENTLINE 82
#define wxSTC_HBA_NUMBER 83
#define wxSTC_HBA_WORD 84
#define wxSTC_HBA_STRING 85
#define wxSTC_HBA_IDENTIFIER 86
#define wxSTC_HBA_STRINGEOL 87
#define wxSTC_HP_START 90
#define wxSTC_HP_DEFAULT 91
#define wxSTC_HP_COMMENTLINE 92
#define wxSTC_HP_NUMBER 93
#define wxSTC_HP_STRING 94
#define wxSTC_HP_CHARACTER 95
#define wxSTC_HP_WORD 96
#define wxSTC_HP_TRIPLE 97
#define wxSTC_HP_TRIPLEDOUBLE 98
#define wxSTC_HP_CLASSNAME 99
#define wxSTC_HP_DEFNAME 100
#define wxSTC_HP_OPERATOR 101
#define wxSTC_HP_IDENTIFIER 102
#define wxSTC_HPA_START 105
#define wxSTC_HPA_DEFAULT 106
#define wxSTC_HPA_COMMENTLINE 107
#define wxSTC_HPA_NUMBER 108
#define wxSTC_HPA_STRING 109
#define wxSTC_HPA_CHARACTER 110
#define wxSTC_HPA_WORD 111
#define wxSTC_HPA_TRIPLE 112
#define wxSTC_HPA_TRIPLEDOUBLE 113
#define wxSTC_HPA_CLASSNAME 114
#define wxSTC_HPA_DEFNAME 115
#define wxSTC_HPA_OPERATOR 116
#define wxSTC_HPA_IDENTIFIER 117
#define wxSTC_HPHP_DEFAULT 118
#define wxSTC_HPHP_HSTRING 119
#define wxSTC_HPHP_SIMPLESTRING 120
#define wxSTC_HPHP_WORD 121
#define wxSTC_HPHP_NUMBER 122
#define wxSTC_HPHP_VARIABLE 123
#define wxSTC_HPHP_COMMENT 124
#define wxSTC_HPHP_COMMENTLINE 125
#define wxSTC_HPHP_HSTRING_VARIABLE 126
#define wxSTC_HPHP_OPERATOR 127
#define wxSTC_PL_DEFAULT 0
#define wxSTC_PL_ERROR 1
#define wxSTC_PL_COMMENTLINE 2
#define wxSTC_PL_POD 3
#define wxSTC_PL_NUMBER 4
#define wxSTC_PL_WORD 5
#define wxSTC_PL_STRING 6
#define wxSTC_PL_CHARACTER 7
#define wxSTC_PL_PUNCTUATION 8
#define wxSTC_PL_PREPROCESSOR 9
#define wxSTC_PL_OPERATOR 10
#define wxSTC_PL_IDENTIFIER 11
#define wxSTC_PL_SCALAR 12
#define wxSTC_PL_ARRAY 13
#define wxSTC_PL_HASH 14
#define wxSTC_PL_SYMBOLTABLE 15
#define wxSTC_PL_REGEX 17
#define wxSTC_PL_REGSUBST 18
#define wxSTC_PL_LONGQUOTE 19
#define wxSTC_PL_BACKTICKS 20
#define wxSTC_PL_DATASECTION 21
#define wxSTC_PL_HERE_DELIM 22
#define wxSTC_PL_HERE_Q 23
#define wxSTC_PL_HERE_QQ 24
#define wxSTC_PL_HERE_QX 25
#define wxSTC_PL_STRING_Q 26
#define wxSTC_PL_STRING_QQ 27
#define wxSTC_PL_STRING_QX 28
#define wxSTC_PL_STRING_QR 29
#define wxSTC_PL_STRING_QW 30
#define wxSTC_B_DEFAULT 0
#define wxSTC_B_COMMENT 1
#define wxSTC_B_NUMBER 2
#define wxSTC_B_KEYWORD 3
#define wxSTC_B_STRING 4
#define wxSTC_B_PREPROCESSOR 5
#define wxSTC_B_OPERATOR 6
#define wxSTC_B_IDENTIFIER 7
#define wxSTC_B_DATE 8
#define wxSTC_PROPS_DEFAULT 0
#define wxSTC_PROPS_COMMENT 1
#define wxSTC_PROPS_SECTION 2
#define wxSTC_PROPS_ASSIGNMENT 3
#define wxSTC_PROPS_DEFVAL 4
#define wxSTC_L_DEFAULT 0
#define wxSTC_L_COMMAND 1
#define wxSTC_L_TAG 2
#define wxSTC_L_MATH 3
#define wxSTC_L_COMMENT 4
#define wxSTC_LUA_DEFAULT 0
#define wxSTC_LUA_COMMENT 1
#define wxSTC_LUA_COMMENTLINE 2
#define wxSTC_LUA_COMMENTDOC 3
#define wxSTC_LUA_NUMBER 4
#define wxSTC_LUA_WORD 5
#define wxSTC_LUA_STRING 6
#define wxSTC_LUA_CHARACTER 7
#define wxSTC_LUA_LITERALSTRING 8
#define wxSTC_LUA_PREPROCESSOR 9
#define wxSTC_LUA_OPERATOR 10
#define wxSTC_LUA_IDENTIFIER 11
#define wxSTC_LUA_STRINGEOL 12
#define wxSTC_LUA_WORD2 13
#define wxSTC_LUA_WORD3 14
#define wxSTC_LUA_WORD4 15
#define wxSTC_LUA_WORD5 16
#define wxSTC_LUA_WORD6 17
#define wxSTC_LUA_WORD7 18
#define wxSTC_LUA_WORD8 19
#define wxSTC_ERR_DEFAULT 0
#define wxSTC_ERR_PYTHON 1
#define wxSTC_ERR_GCC 2
#define wxSTC_ERR_MS 3
#define wxSTC_ERR_CMD 4
#define wxSTC_ERR_BORLAND 5
#define wxSTC_ERR_PERL 6
#define wxSTC_ERR_NET 7
#define wxSTC_ERR_LUA 8
#define wxSTC_ERR_CTAG 9
#define wxSTC_ERR_DIFF_CHANGED 10
#define wxSTC_ERR_DIFF_ADDITION 11
#define wxSTC_ERR_DIFF_DELETION 12
#define wxSTC_ERR_DIFF_MESSAGE 13
#define wxSTC_ERR_PHP 14
#define wxSTC_ERR_ELF 15
#define wxSTC_ERR_IFC 16
#define wxSTC_BAT_DEFAULT 0
#define wxSTC_BAT_COMMENT 1
#define wxSTC_BAT_WORD 2
#define wxSTC_BAT_LABEL 3
#define wxSTC_BAT_HIDE 4
#define wxSTC_BAT_COMMAND 5
#define wxSTC_BAT_IDENTIFIER 6
#define wxSTC_BAT_OPERATOR 7
#define wxSTC_MAKE_DEFAULT 0
#define wxSTC_MAKE_COMMENT 1
#define wxSTC_MAKE_PREPROCESSOR 2
#define wxSTC_MAKE_IDENTIFIER 3
#define wxSTC_MAKE_OPERATOR 4
#define wxSTC_MAKE_TARGET 5
#define wxSTC_MAKE_IDEOL 9
#define wxSTC_DIFF_DEFAULT 0
#define wxSTC_DIFF_COMMENT 1
#define wxSTC_DIFF_COMMAND 2
#define wxSTC_DIFF_HEADER 3
#define wxSTC_DIFF_POSITION 4
#define wxSTC_DIFF_DELETED 5
#define wxSTC_DIFF_ADDED 6
#define wxSTC_CONF_DEFAULT 0
#define wxSTC_CONF_COMMENT 1
#define wxSTC_CONF_NUMBER 2
#define wxSTC_CONF_IDENTIFIER 3
#define wxSTC_CONF_EXTENSION 4
#define wxSTC_CONF_PARAMETER 5
#define wxSTC_CONF_STRING 6
#define wxSTC_CONF_OPERATOR 7
#define wxSTC_CONF_IP 8
#define wxSTC_CONF_DIRECTIVE 9
#define wxSTC_AVE_DEFAULT 0
#define wxSTC_AVE_COMMENT 1
#define wxSTC_AVE_NUMBER 2
#define wxSTC_AVE_WORD 3
#define wxSTC_AVE_STRING 6
#define wxSTC_AVE_ENUM 7
#define wxSTC_AVE_STRINGEOL 8
#define wxSTC_AVE_IDENTIFIER 9
#define wxSTC_AVE_OPERATOR 10
#define wxSTC_AVE_WORD1 11
#define wxSTC_AVE_WORD2 12
#define wxSTC_AVE_WORD3 13
#define wxSTC_AVE_WORD4 14
#define wxSTC_AVE_WORD5 15
#define wxSTC_AVE_WORD6 16
#define wxSTC_ADA_DEFAULT 0
#define wxSTC_ADA_WORD 1
#define wxSTC_ADA_IDENTIFIER 2
#define wxSTC_ADA_NUMBER 3
#define wxSTC_ADA_DELIMITER 4
#define wxSTC_ADA_CHARACTER 5
#define wxSTC_ADA_CHARACTEREOL 6
#define wxSTC_ADA_STRING 7
#define wxSTC_ADA_STRINGEOL 8
#define wxSTC_ADA_LABEL 9
#define wxSTC_ADA_COMMENTLINE 10
#define wxSTC_ADA_ILLEGAL 11
#define wxSTC_BAAN_DEFAULT 0
#define wxSTC_BAAN_COMMENT 1
#define wxSTC_BAAN_COMMENTDOC 2
#define wxSTC_BAAN_NUMBER 3
#define wxSTC_BAAN_WORD 4
#define wxSTC_BAAN_STRING 5
#define wxSTC_BAAN_PREPROCESSOR 6
#define wxSTC_BAAN_OPERATOR 7
#define wxSTC_BAAN_IDENTIFIER 8
#define wxSTC_BAAN_STRINGEOL 9
#define wxSTC_BAAN_WORD2 10
#define wxSTC_LISP_DEFAULT 0
#define wxSTC_LISP_COMMENT 1
#define wxSTC_LISP_NUMBER 2
#define wxSTC_LISP_KEYWORD 3
#define wxSTC_LISP_STRING 6
#define wxSTC_LISP_STRINGEOL 8
#define wxSTC_LISP_IDENTIFIER 9
#define wxSTC_LISP_OPERATOR 10
#define wxSTC_EIFFEL_DEFAULT 0
#define wxSTC_EIFFEL_COMMENTLINE 1
#define wxSTC_EIFFEL_NUMBER 2
#define wxSTC_EIFFEL_WORD 3
#define wxSTC_EIFFEL_STRING 4
#define wxSTC_EIFFEL_CHARACTER 5
#define wxSTC_EIFFEL_OPERATOR 6
#define wxSTC_EIFFEL_IDENTIFIER 7
#define wxSTC_EIFFEL_STRINGEOL 8
#define wxSTC_NNCRONTAB_DEFAULT 0
#define wxSTC_NNCRONTAB_COMMENT 1
#define wxSTC_NNCRONTAB_TASK 2
#define wxSTC_NNCRONTAB_SECTION 3
#define wxSTC_NNCRONTAB_KEYWORD 4
#define wxSTC_NNCRONTAB_MODIFIER 5
#define wxSTC_NNCRONTAB_ASTERISK 6
#define wxSTC_NNCRONTAB_NUMBER 7
#define wxSTC_NNCRONTAB_STRING 8
#define wxSTC_NNCRONTAB_ENVIRONMENT 9
#define wxSTC_NNCRONTAB_IDENTIFIER 10
#define wxSTC_MATLAB_DEFAULT 0
#define wxSTC_MATLAB_COMMENT 1
#define wxSTC_MATLAB_COMMAND 2
#define wxSTC_MATLAB_NUMBER 3
#define wxSTC_MATLAB_KEYWORD 4
#define wxSTC_MATLAB_STRING 5
#define wxSTC_MATLAB_OPERATOR 6
#define wxSTC_MATLAB_IDENTIFIER 7
#define wxSTC_SCRIPTOL_DEFAULT 0
#define wxSTC_SCRIPTOL_COMMENT 1
#define wxSTC_SCRIPTOL_COMMENTLINE 2
#define wxSTC_SCRIPTOL_COMMENTDOC 3
#define wxSTC_SCRIPTOL_NUMBER 4
#define wxSTC_SCRIPTOL_WORD 5
#define wxSTC_SCRIPTOL_STRING 6
#define wxSTC_SCRIPTOL_CHARACTER 7
#define wxSTC_SCRIPTOL_UUID 8
#define wxSTC_SCRIPTOL_PREPROCESSOR 9
#define wxSTC_SCRIPTOL_OPERATOR 10
#define wxSTC_SCRIPTOL_IDENTIFIER 11
#define wxSTC_SCRIPTOL_STRINGEOL 12
#define wxSTC_SCRIPTOL_VERBATIM 13
#define wxSTC_SCRIPTOL_REGEX 14
#define wxSTC_SCRIPTOL_COMMENTLINEDOC 15
#define wxSTC_SCRIPTOL_WORD2 16
#define wxSTC_SCRIPTOL_COMMENTDOCKEYWORD 17
#define wxSTC_SCRIPTOL_COMMENTDOCKEYWORDERROR 18
#define wxSTC_SCRIPTOL_COMMENTBASIC 19
#define wxSTC_ASM_DEFAULT 0
#define wxSTC_ASM_COMMENT 1
#define wxSTC_ASM_NUMBER 2
#define wxSTC_ASM_STRING 3
#define wxSTC_ASM_OPERATOR 4
#define wxSTC_ASM_IDENTIFIER 5
#define wxSTC_ASM_CPUINSTRUCTION 6
#define wxSTC_ASM_MATHINSTRUCTION 7
#define wxSTC_ASM_REGISTER 8
#define wxSTC_ASM_DIRECTIVE 9
#define wxSTC_ASM_DIRECTIVEOPERAND 10
#define wxSTC_F_DEFAULT 0
#define wxSTC_F_COMMENT 1
#define wxSTC_F_NUMBER 2
#define wxSTC_F_STRING1 3
#define wxSTC_F_STRING2 4
#define wxSTC_F_STRINGEOL 5
#define wxSTC_F_OPERATOR 6
#define wxSTC_F_IDENTIFIER 7
#define wxSTC_F_WORD 8
#define wxSTC_F_WORD2 9
#define wxSTC_F_WORD3 10
#define wxSTC_F_PREPROCESSOR 11
#define wxSTC_F_OPERATOR2 12
#define wxSTC_F_LABEL 13
#define wxSTC_F_CONTINUATION 14
#define wxSTC_CSS_DEFAULT 0
#define wxSTC_CSS_TAG 1
#define wxSTC_CSS_CLASS 2
#define wxSTC_CSS_PSEUDOCLASS 3
#define wxSTC_CSS_UNKNOWN_PSEUDOCLASS 4
#define wxSTC_CSS_OPERATOR 5
#define wxSTC_CSS_IDENTIFIER 6
#define wxSTC_CSS_UNKNOWN_IDENTIFIER 7
#define wxSTC_CSS_VALUE 8
#define wxSTC_CSS_COMMENT 9
#define wxSTC_CSS_ID 10
#define wxSTC_CSS_IMPORTANT 11
#define wxSTC_CSS_DIRECTIVE 12
#define wxSTC_CSS_DOUBLESTRING 13
#define wxSTC_CSS_SINGLESTRING 14
#define wxSTC_POV_DEFAULT 0
#define wxSTC_POV_COMMENT 1
#define wxSTC_POV_COMMENTLINE 2
#define wxSTC_POV_NUMBER 3
#define wxSTC_POV_OPERATOR 4
#define wxSTC_POV_IDENTIFIER 5
#define wxSTC_POV_STRING 6
#define wxSTC_POV_STRINGEOL 7
#define wxSTC_POV_DIRECTIVE 8
#define wxSTC_POV_BADDIRECTIVE 9
#define wxSTC_POV_WORD2 10
#define wxSTC_POV_WORD3 11
#define wxSTC_POV_WORD4 12
#define wxSTC_POV_WORD5 13
#define wxSTC_POV_WORD6 14
#define wxSTC_POV_WORD7 15
#define wxSTC_POV_WORD8 16
#define wxSTC_LOUT_DEFAULT 0
#define wxSTC_LOUT_COMMENT 1
#define wxSTC_LOUT_NUMBER 2
#define wxSTC_LOUT_WORD 3
#define wxSTC_LOUT_WORD2 4
#define wxSTC_LOUT_WORD3 5
#define wxSTC_LOUT_WORD4 6
#define wxSTC_LOUT_STRING 7
#define wxSTC_LOUT_OPERATOR 8
#define wxSTC_LOUT_IDENTIFIER 9
#define wxSTC_LOUT_STRINGEOL 10
#define wxSTC_ESCRIPT_DEFAULT 0
#define wxSTC_ESCRIPT_COMMENT 1
#define wxSTC_ESCRIPT_COMMENTLINE 2
#define wxSTC_ESCRIPT_COMMENTDOC 3
#define wxSTC_ESCRIPT_NUMBER 4
#define wxSTC_ESCRIPT_WORD 5
#define wxSTC_ESCRIPT_STRING 6
#define wxSTC_ESCRIPT_OPERATOR 7
#define wxSTC_ESCRIPT_IDENTIFIER 8
#define wxSTC_ESCRIPT_BRACE 9
#define wxSTC_ESCRIPT_WORD2 10
#define wxSTC_ESCRIPT_WORD3 11
#define wxSTC_PS_DEFAULT 0
#define wxSTC_PS_COMMENT 1
#define wxSTC_PS_DSC_COMMENT 2
#define wxSTC_PS_DSC_VALUE 3
#define wxSTC_PS_NUMBER 4
#define wxSTC_PS_NAME 5
#define wxSTC_PS_KEYWORD 6
#define wxSTC_PS_LITERAL 7
#define wxSTC_PS_IMMEVAL 8
#define wxSTC_PS_PAREN_ARRAY 9
#define wxSTC_PS_PAREN_DICT 10
#define wxSTC_PS_PAREN_PROC 11
#define wxSTC_PS_TEXT 12
#define wxSTC_PS_HEXSTRING 13
#define wxSTC_PS_BASE85STRING 14
#define wxSTC_PS_BADSTRINGCHAR 15
#define wxSTC_NSIS_DEFAULT 0
#define wxSTC_NSIS_COMMENT 1
#define wxSTC_NSIS_STRINGDQ 2
#define wxSTC_NSIS_STRINGLQ 3
#define wxSTC_NSIS_STRINGRQ 4
#define wxSTC_NSIS_FUNCTION 5
#define wxSTC_NSIS_VARIABLE 6
#define wxSTC_NSIS_LABEL 7
#define wxSTC_NSIS_USERDEFINED 8
#define wxSTC_NSIS_SECTIONDEF 9
#define wxSTC_NSIS_SUBSECTIONDEF 10
#define wxSTC_NSIS_IFDEFINEDEF 11
#define wxSTC_NSIS_MACRODEF 12
#define wxSTC_NSIS_STRINGVAR 13
#define wxSTC_MMIXAL_LEADWS 0
#define wxSTC_MMIXAL_COMMENT 1
#define wxSTC_MMIXAL_LABEL 2
#define wxSTC_MMIXAL_OPCODE 3
#define wxSTC_MMIXAL_OPCODE_PRE 4
#define wxSTC_MMIXAL_OPCODE_VALID 5
#define wxSTC_MMIXAL_OPCODE_UNKNOWN 6
#define wxSTC_MMIXAL_OPCODE_POST 7
#define wxSTC_MMIXAL_OPERANDS 8
#define wxSTC_MMIXAL_NUMBER 9
#define wxSTC_MMIXAL_REF 10
#define wxSTC_MMIXAL_CHAR 11
#define wxSTC_MMIXAL_STRING 12
#define wxSTC_MMIXAL_REGISTER 13
#define wxSTC_MMIXAL_HEX 14
#define wxSTC_MMIXAL_OPERATOR 15
#define wxSTC_MMIXAL_SYMBOL 16
#define wxSTC_MMIXAL_INCLUDE 17
#define wxSTC_CMD_REDO 2011
#define wxSTC_CMD_SELECTALL 2013
#define wxSTC_CMD_UNDO 2176
#define wxSTC_CMD_CUT 2177
#define wxSTC_CMD_COPY 2178
#define wxSTC_CMD_PASTE 2179
#define wxSTC_CMD_CLEAR 2180
#define wxSTC_CMD_LINEDOWN 2300
#define wxSTC_CMD_LINEDOWNEXTEND 2301
#define wxSTC_CMD_LINEUP 2302
#define wxSTC_CMD_LINEUPEXTEND 2303
#define wxSTC_CMD_CHARLEFT 2304
#define wxSTC_CMD_CHARLEFTEXTEND 2305
#define wxSTC_CMD_CHARRIGHT 2306
#define wxSTC_CMD_CHARRIGHTEXTEND 2307
#define wxSTC_CMD_WORDLEFT 2308
#define wxSTC_CMD_WORDLEFTEXTEND 2309
#define wxSTC_CMD_WORDRIGHT 2310
#define wxSTC_CMD_WORDRIGHTEXTEND 2311
#define wxSTC_CMD_HOME 2312
#define wxSTC_CMD_HOMEEXTEND 2313
#define wxSTC_CMD_LINEEND 2314
#define wxSTC_CMD_LINEENDEXTEND 2315
#define wxSTC_CMD_DOCUMENTSTART 2316
#define wxSTC_CMD_DOCUMENTSTARTEXTEND 2317
#define wxSTC_CMD_DOCUMENTEND 2318
#define wxSTC_CMD_DOCUMENTENDEXTEND 2319
#define wxSTC_CMD_PAGEUP 2320
#define wxSTC_CMD_PAGEUPEXTEND 2321
#define wxSTC_CMD_PAGEDOWN 2322
#define wxSTC_CMD_PAGEDOWNEXTEND 2323
#define wxSTC_CMD_EDITTOGGLEOVERTYPE 2324
#define wxSTC_CMD_CANCEL 2325
#define wxSTC_CMD_DELETEBACK 2326#define wxSTC_CMD_TAB 2327
#define wxSTC_CMD_BACKTAB 2328
#define wxSTC_CMD_NEWLINE 2329
#define wxSTC_CMD_FORMFEED 2330#define wxSTC_CMD_VCHOME 2331
#define wxSTC_CMD_VCHOMEEXTEND 2332
#define wxSTC_CMD_ZOOMIN 2333
#define wxSTC_CMD_ZOOMOUT 2334
#define wxSTC_CMD_DELWORDLEFT 2335
#define wxSTC_CMD_DELWORDRIGHT 2336
#define wxSTC_CMD_LINECUT 2337
#define wxSTC_CMD_LINEDELETE 2338
#define wxSTC_CMD_LINETRANSPOSE 2339
#define wxSTC_CMD_LINEDUPLICATE 2404
#define wxSTC_CMD_LOWERCASE 2340
#define wxSTC_CMD_UPPERCASE 2341
#define wxSTC_CMD_LINESCROLLDOWN 2342
#define wxSTC_CMD_LINESCROLLUP 2343
#define wxSTC_CMD_DELETEBACKNOTLINE 2344
#define wxSTC_CMD_HOMEDISPLAY 2345
#define wxSTC_CMD_HOMEDISPLAYEXTEND 2346
#define wxSTC_CMD_LINEENDDISPLAY 2347
#define wxSTC_CMD_LINEENDDISPLAYEXTEND 2348
#define wxSTC_CMD_HOMEWRAP 2349
#define wxSTC_CMD_HOMEWRAPEXTEND 2450
#define wxSTC_CMD_LINEENDWRAP 2451
#define wxSTC_CMD_LINEENDWRAPEXTEND 2452
#define wxSTC_CMD_VCHOMEWRAP 2453
#define wxSTC_CMD_VCHOMEWRAPEXTEND 2454
#define wxSTC_CMD_WORDPARTLEFT 2390
#define wxSTC_CMD_WORDPARTLEFTEXTEND 2391
#define wxSTC_CMD_WORDPARTRIGHT 2392
#define wxSTC_CMD_WORDPARTRIGHTEXTEND 2393
#define wxSTC_CMD_DELLINELEFT 2395
#define wxSTC_CMD_DELLINERIGHT 2396
#define wxSTC_CMD_PARADOWN 2413
#define wxSTC_CMD_PARADOWNEXTEND 2414
#define wxSTC_CMD_PARAUP 2415
#define wxSTC_CMD_PARAUPEXTEND 2416

enum
    wxOPEN              = &h0001
    wxSAVE              = &h0002
    wxOVERWRITE_PROMPT  = &h0004
    wxHIDE_READONLY     = &h0008
    wxFILE_MUST_EXIST   = &h0010
    wxMULTIPLE          = &h0020
    wxCHANGE_DIR        = &h0040
end enum


enum wxFindReplaceFlags
    wxFR_DOWN       = 1
    wxFR_WHOLEWORD  = 2
    wxFR_MATCHCASE  = 4
end enum

enum wxFindReplaceDialogStyles
    wxFR_REPLACEDIALOG = 1
    wxFR_NOUPDOWN      = 2
    wxFR_NOMATCHCASE   = 4
    wxFR_NOWHOLEWORD   = 8
end enum

enum wxXmlResourceFlags
    wxXRC_USE_LOCALE     = 1
    wxXRC_NO_SUBCLASSING = 2
end enum

#endif
