''
''
'' defs -- header translated with help of SWIG FB wrapper
''
'' NOTICE: This file is part of the FreeBASIC Compiler package and can't
''         be included in other distributions without authorization.
''
''
#ifndef __defs_bi__
#define __defs_bi__

enum 
	wxUNKNOWN_PLATFORM
	wxCURSES
	wxXVIEW_X
	wxMOTIF_X
	wxCOSE_X
	wxNEXTSTEP
	wxMAC
	wxMAC_DARWIN
	wxBEOS
	wxGTK
	wxGTK_WIN32
	wxGTK_OS2
	wxGTK_BEOS
	wxGEOS
	wxOS2_PM
	wxWINDOWS
	wxMICROWINDOWS
	wxPENWINDOWS
	wxWINDOWS_NT
	wxWIN32S
	wxWIN95
	wxWIN386
	wxMGL_UNIX
	wxMGL_X
	wxMGL_WIN32
	wxMGL_OS2
	wxMGL_DOS
	wxWINDOWS_OS2
	wxUNIX
	wxX11
end enum

type wxCoord as integer
type wxFloat32 as single
type wxFloat64 as double
type wxDouble as double

#define wxBIG_ENDIAN 4321
#define wxLITTLE_ENDIAN 1234
#define wxPDP_ENDIAN 3412
#define wxBYTE_ORDER 1234

enum wxGeometryCentre
	wxCENTRE = &h0001
	wxCENTER = wxCENTRE
end enum

#define wxCENTER_FRAME &h0000
#define wxCENTRE_ON_SCREEN &h0002
#define wxCENTER_ON_SCREEN &h0002

enum wxOrientation
	wxHORIZONTAL = &h0004
	wxVERTICAL = &h0008
	wxBOTH = (wxVERTICAL or wxHORIZONTAL)
end enum

enum wxDirection
	wxLEFT = &h0010
	wxRIGHT = &h0020
	wxUP = &h0040
	wxDOWN = &h0080
	wxTOP = wxUP
	wxBOTTOM = wxDOWN
	wxNORTH = wxUP
	wxSOUTH = wxDOWN
	wxWEST = wxLEFT
	wxEAST = wxRIGHT
	wxALL = (wxUP or wxDOWN or wxRIGHT or wxLEFT)
end enum

enum wxAlignment
	wxALIGN_NOT = &h0000
	wxALIGN_CENTER_HORIZONTAL = &h0100
	wxALIGN_CENTRE_HORIZONTAL = wxALIGN_CENTER_HORIZONTAL
	wxALIGN_LEFT = wxALIGN_NOT
	wxALIGN_TOP = wxALIGN_NOT
	wxALIGN_RIGHT = &h0200
	wxALIGN_BOTTOM = &h0400
	wxALIGN_CENTER_VERTICAL = &h0800
	wxALIGN_CENTRE_VERTICAL = wxALIGN_CENTER_VERTICAL
	wxALIGN_CENTER = (wxALIGN_CENTER_HORIZONTAL or wxALIGN_CENTER_VERTICAL)
	wxALIGN_CENTRE = wxALIGN_CENTER
	wxALIGN_MASK = &h0f00
end enum

enum wxStretch
	wxSTRETCH_NOT = &h0000
	wxSHRINK = &h1000
	wxGROW = &h2000
	wxEXPAND = wxGROW
	wxSHAPED = &h4000
	wxADJUST_MINSIZE = &h8000
	wxTILE = &hc000
end enum

enum wxBorder
	wxBORDER_DEFAULT = 0
	wxBORDER_NONE = &h00200000
	wxBORDER_STATIC = &h01000000
	wxBORDER_SIMPLE = &h02000000
	wxBORDER_RAISED = &h04000000
	wxBORDER_SUNKEN = &h08000000
	wxBORDER_DOUBLE = &h10000000
	wxBORDER_MASK = &h1f200000
end enum

#define wxVSCROLL &h80000000
#define wxHSCROLL &h40000000
#define wxCAPTION &h20000000
#define wxNO_3D &h00800000
#define wxUSER_COLOURS &h00800000
#define wxALWAYS_SHOW_SB &h00800000
#define wxCLIP_CHILDREN &h00400000
#define wxCLIP_SIBLINGS &h20000000
#define wxTRANSPARENT_WINDOW &h00100000
#define wxTAB_TRAVERSAL &h00080000
#define wxWANTS_CHARS &h00040000
#define wxRETAINED &h00020000
#define wxBACKINGSTORE &h00020000
#define wxPOPUP_WINDOW &h00020000
#define wxNO_FULL_REPAINT_ON_RESIZE &h00010000
#define wxWS_EX_VALIDATE_RECURSIVELY &h00000001
#define wxWS_EX_BLOCK_EVENTS &h00000002
#define wxWS_EX_TRANSIENT &h00000004
#define wxFRAME_EX_CONTEXTHELP &h00000004
#define wxDIALOG_EX_CONTEXTHELP &h00000004
#define wxSTAY_ON_TOP &h8000
#define wxICONIZE &h4000
#define wxMINIMIZE &h4000
#define wxMAXIMIZE &h2000
#define wxSYSTEM_MENU &h0800
#define wxMINIMIZE_BOX &h0400
#define wxMAXIMIZE_BOX &h0200
#define wxTINY_CAPTION_HORIZ &h0100
#define wxTINY_CAPTION_VERT &h0080
#define wxRESIZE_BORDER &h0040
#define wxDIALOG_NO_PARENT &h0001
#define wxFRAME_NO_TASKBAR &h0002
#define wxFRAME_TOOL_WINDOW &h0004
#define wxFRAME_FLOAT_ON_PARENT &h0008
#define wxFRAME_SHAPED &h0010
#define wxRESIZE_BOX &h0200
#define wxTHICK_FRAME &h0040
#define wxDIALOG_MODAL &h0020
#define wxDIALOG_MODELESS &h0000
#define wxFRAME_NO_WINDOW_MENU &h0100
#define wxDEFAULT_FRAME_STYLE (&h0800 or &h0040 or &h0400 or &h0200 or &h20000000 or &h00400000)
#define wxDEFAULT_DIALOG_STYLE &h20000000
#define wxED_CLIENT_MARGIN &h0004
#define wxED_BUTTONS_BOTTOM &h0000
#define wxED_BUTTONS_RIGHT &h0002
#define wxED_STATIC_LINE &h0001
#define wxEXT_DIALOG_STYLE (&h20000000 or &h0004 or &h0001)
#define wxMB_DOCKABLE &h0001
#define wxMENU_TEAROFF &h0001
#define wxCOLOURED &h0800
#define wxFIXED_LENGTH &h0400
#define wxLB_SORT &h0010
#define wxLB_SINGLE &h0020
#define wxLB_MULTIPLE &h0040
#define wxLB_EXTENDED &h0080
#define wxLB_OWNERDRAW &h0100
#define wxLB_NEEDED_SB &h0200
#define wxLB_ALWAYS_SB &h0400
#define wxLB_HSCROLL &h40000000
#define wxLB_INT_HEIGHT &h0800
#define wxPROCESS_ENTER &h0400
#define wxPASSWORD &h0800
#define wxCB_SIMPLE &h0004
#define wxCB_SORT &h0008
#define wxCB_READONLY &h0010
#define wxCB_DROPDOWN &h0020
#define wxRA_LEFTTORIGHT &h0001
#define wxRA_TOPTOBOTTOM &h0002
#define wxRB_GROUP &h0004
#define wxRB_SINGLE &h0008
#define wxGA_PROGRESSBAR &h0010
#define wxGA_SMOOTH &h0020
#define wxSL_NOTIFY_DRAG &h0000
#define wxSL_TICKS &h0010
#define wxSL_AUTOTICKS &h0010
#define wxSL_LABELS &h0020
#define wxSL_LEFT &h0040
#define wxSL_TOP &h0080
#define wxSL_RIGHT &h0100
#define wxSL_BOTTOM &h0200
#define wxSL_BOTH &h0400
#define wxSL_SELRANGE &h0800
#define wxSP_ARROW_KEYS &h1000
#define wxSP_WRAP &h2000
#define wxSP_NOBORDER &h0000
#define wxSP_NOSASH &h0010
#define wxSP_BORDER &h0020
#define wxSP_PERMIT_UNSPLIT &h0040
#define wxSP_LIVE_UPDATE &h0080
#define wxSP_3DSASH &h0100
#define wxSP_3DBORDER &h0200
#define wxSP_FULLSASH &h0400
#define wxSP_3D (&h0200 or &h0100)
#define wxSP_SASH_AQUA &h0800
#define wxNB_FIXEDWIDTH &h0010
#define wxNB_TOP &h0000
#define wxNB_LEFT &h0020
#define wxNB_RIGHT &h0040
#define wxNB_BOTTOM &h0080
#define wxNB_MULTILINE &h0100
#define wxTC_RIGHTJUSTIFY &h0010
#define wxTC_FIXEDWIDTH &h0020
#define wxTC_TOP &h0000
#define wxTC_LEFT &h0020
#define wxTC_RIGHT &h0040
#define wxTC_BOTTOM &h0080
#define wxTC_MULTILINE &h0100
#define wxTC_OWNERDRAW &h0200
#define wxTB_3DBUTTONS &h0010
#define wxTB_FLAT &h0020
#define wxTB_DOCKABLE &h0040
#define wxTB_NOICONS &h0080
#define wxTB_TEXT &h0100
#define wxTB_NODIVIDER &h0200
#define wxTB_NOALIGN &h0400
#define wxST_SIZEGRIP &h0010
#define wxST_NO_AUTORESIZE &h0001
#define wxPD_CAN_ABORT &h0001
#define wxPD_APP_MODAL &h0002
#define wxPD_AUTO_HIDE &h0004
#define wxPD_ELAPSED_TIME &h0008
#define wxPD_ESTIMATED_TIME &h0010
#define wxPD_REMAINING_TIME &h0040
#define wxDD_NEW_DIR_BUTTON &h0080
#define wxYES &h00000002
#define wxOK &h00000004
#define wxNO &h00000008
#define wxYES_NO (&h00000002 or &h00000008)
#define wxCANCEL &h00000010
#define wxYES_DEFAULT &h00000000
#define wxNO_DEFAULT &h00000080
#define wxICON_EXCLAMATION &h00000100
#define wxICON_HAND &h00000200
#define wxICON_WARNING &h00000100
#define wxICON_ERROR &h00000200
#define wxICON_QUESTION &h00000400
#define wxICON_INFORMATION &h00000800
#define wxICON_STOP &h00000200
#define wxICON_ASTERISK &h00000800
#define wxICON_MASK (&h00000100 or &h00000200 or &h00000400 or &h00000800)
#define wxFORWARD &h00001000
#define wxBACKWARD &h00002000
#define wxRESET &h00004000
#define wxHELP &h00008000
#define wxMORE &h00010000
#define wxSETUP &h00020000

enum 
	wxID_ANY = -1
end enum

enum 
	wxID_SEPARATOR = -1
end enum

enum 
	wxID_LOWEST = 4999
	wxID_OPEN
	wxID_CLOSE
	wxID_NEW
	wxID_SAVE
	wxID_SAVEAS
	wxID_REVERT
	wxID_EXIT
	wxID_UNDO
	wxID_REDO
	wxID_HELP
	wxID_PRINT
	wxID_PRINT_SETUP
	wxID_PREVIEW
	wxID_ABOUT
	wxID_HELP_CONTENTS
	wxID_HELP_COMMANDS
	wxID_HELP_PROCEDURES
	wxID_HELP_CONTEXT
	wxID_CLOSE_ALL
	wxID_CUT = 5030
	wxID_COPY
	wxID_PASTE
	wxID_CLEAR
	wxID_FIND
	wxID_DUPLICATE
	wxID_SELECTALL
	wxID_FILE1 = 5050
	wxID_FILE2
	wxID_FILE3
	wxID_FILE4
	wxID_FILE5
	wxID_FILE6
	wxID_FILE7
	wxID_FILE8
	wxID_FILE9
	wxID_OK = 5100
	wxID_CANCEL
	wxID_APPLY
	wxID_YES
	wxID_NO
	wxID_STATIC
	wxID_FORWARD
	wxID_BACKWARD
	wxID_DEFAULT
	wxID_MORE
	wxID_SETUP
	wxID_RESET
	wxID_CONTEXT_HELP
	wxID_YESTOALL
	wxID_NOTOALL
	wxID_ABORT
	wxID_RETRY
	wxID_IGNORE
	wxID_SYSTEM_MENU = 5200
	wxID_CLOSE_FRAME
	wxID_MOVE_FRAME
	wxID_RESIZE_FRAME
	wxID_MAXIMIZE_FRAME
	wxID_ICONIZE_FRAME
	wxID_RESTORE_FRAME
	wxID_FILEDLGG = 5900
	wxID_HIGHEST = 5999
end enum

enum wxItemKind
	wxITEM_SEPARATOR = -1
	wxITEM_NORMAL
	wxITEM_CHECK
	wxITEM_RADIO
	wxITEM_MAX
end enum

enum wxHitTest
	wxHT_NOWHERE
	wxHT_SCROLLBAR_FIRST = wxHT_NOWHERE
	wxHT_SCROLLBAR_ARROW_LINE_1
	wxHT_SCROLLBAR_ARROW_LINE_2
	wxHT_SCROLLBAR_ARROW_PAGE_1
	wxHT_SCROLLBAR_ARROW_PAGE_2
	wxHT_SCROLLBAR_THUMB
	wxHT_SCROLLBAR_BAR_1
	wxHT_SCROLLBAR_BAR_2
	wxHT_SCROLLBAR_LAST
	wxHT_WINDOW_OUTSIDE
	wxHT_WINDOW_INSIDE
	wxHT_WINDOW_VERT_SCROLLBAR
	wxHT_WINDOW_HORZ_SCROLLBAR
	wxHT_WINDOW_CORNER
	wxHT_MAX
end enum

#define wxSIZE_AUTO_WIDTH &h0001
#define wxSIZE_AUTO_HEIGHT &h0002
#define wxSIZE_AUTO (&h0001 or &h0002)
#define wxSIZE_USE_EXISTING &h0000
#define wxSIZE_ALLOW_MINUS_ONE &h0004
#define wxSIZE_NO_ADJUSTMENTS &h0008

enum 
	wxDEFAULT = 70
	wxDECORATIVE
	wxROMAN
	wxSCRIPT
	wxSWISS
	wxMODERN
	wxTELETYPE
	wxVARIABLE = 80
	wxFIXED
	wxNORMAL = 90
	wxLIGHT
	wxBOLD
	wxITALIC
	wxSLANT
	wxSOLID = 100
	wxDOT
	wxLONG_DASH
	wxSHORT_DASH
	wxDOT_DASH
	wxUSER_DASH
	wxTRANSPARENT
	wxSTIPPLE_MASK_OPAQUE
	wxSTIPPLE_MASK
	wxSTIPPLE = 110
	wxBDIAGONAL_HATCH
	wxCROSSDIAG_HATCH
	wxFDIAGONAL_HATCH
	wxCROSS_HATCH
	wxHORIZONTAL_HATCH
	wxVERTICAL_HATCH
	wxJOIN_BEVEL = 120
	wxJOIN_MITER
	wxJOIN_ROUND
	wxCAP_ROUND = 130
	wxCAP_PROJECTING
	wxCAP_BUTT
end enum

enum form_ops_t
	wxCLEAR
	wxROP_BLACK = wxCLEAR
	wxBLIT_BLACKNESS = wxCLEAR
	wxXOR
	wxROP_XORPEN = wxXOR
	wxBLIT_SRCINVERT = wxXOR
	wxINVERT
	wxROP_NOT = wxINVERT
	wxBLIT_DSTINVERT = wxINVERT
	wxOR_REVERSE
	wxROP_MERGEPENNOT = wxOR_REVERSE
	wxBLIT_00DD0228 = wxOR_REVERSE
	wxAND_REVERSE
	wxROP_MASKPENNOT = wxAND_REVERSE
	wxBLIT_SRCERASE = wxAND_REVERSE
	wxCOPY
	wxROP_COPYPEN = wxCOPY
	wxBLIT_SRCCOPY = wxCOPY
	wxAND
	wxROP_MASKPEN = wxAND
	wxBLIT_SRCAND = wxAND
	wxAND_INVERT
	wxROP_MASKNOTPEN = wxAND_INVERT
	wxBLIT_00220326 = wxAND_INVERT
	wxNO_OP
	wxROP_NOP = wxNO_OP
	wxBLIT_00AA0029 = wxNO_OP
	wxNOR
	wxROP_NOTMERGEPEN = wxNOR
	wxBLIT_NOTSRCERASE = wxNOR
	wxEQUIV
	wxROP_NOTXORPEN = wxEQUIV
	wxBLIT_00990066 = wxEQUIV
	wxSRC_INVERT
	wxROP_NOTCOPYPEN = wxSRC_INVERT
	wxBLIT_NOTSCRCOPY = wxSRC_INVERT
	wxOR_INVERT
	wxROP_MERGENOTPEN = wxOR_INVERT
	wxBLIT_MERGEPAINT = wxOR_INVERT
	wxNAND
	wxROP_NOTMASKPEN = wxNAND
	wxBLIT_007700E6 = wxNAND
	wxOR
	wxROP_MERGEPEN = wxOR
	wxBLIT_SRCPAINT = wxOR
	wxSET
	wxROP_WHITE = wxSET
	wxBLIT_WHITENESS = wxSET
end enum


enum 
	wxFLOOD_SURFACE = 1
	wxFLOOD_BORDER
end enum

enum 
	wxODDEVEN_RULE = 1
	wxWINDING_RULE
end enum

enum 
	wxTOOL_TOP = 1
	wxTOOL_BOTTOM
	wxTOOL_LEFT
	wxTOOL_RIGHT
end enum

enum wxDataFormatId
	wxDF_INVALID = 0
	wxDF_TEXT = 1
	wxDF_BITMAP = 2
	wxDF_METAFILE = 3
	wxDF_SYLK = 4
	wxDF_DIF = 5
	wxDF_TIFF = 6
	wxDF_OEMTEXT = 7
	wxDF_DIB = 8
	wxDF_PALETTE = 9
	wxDF_PENDATA = 10
	wxDF_RIFF = 11
	wxDF_WAVE = 12
	wxDF_UNICODETEXT = 13
	wxDF_ENHMETAFILE = 14
	wxDF_FILENAME = 15
	wxDF_LOCALE = 16
	wxDF_PRIVATE = 20
	wxDF_HTML = 30
	wxDF_MAX
end enum

enum wxKeyCode
	WXK_BACK = 8
	WXK_TAB = 9
	WXK_RETURN = 13
	WXK_ESCAPE = 27
	WXK_SPACE = 32
	WXK_DELETE = 127
	WXK_START = 300
	WXK_LBUTTON
	WXK_RBUTTON
	WXK_CANCEL
	WXK_MBUTTON
	WXK_CLEAR
	WXK_SHIFT
	WXK_ALT
	WXK_CONTROL
	WXK_MENU
	WXK_PAUSE
	WXK_CAPITAL
	WXK_PRIOR
	WXK_NEXT
	WXK_END
	WXK_HOME
	WXK_LEFT
	WXK_UP
	WXK_RIGHT
	WXK_DOWN
	WXK_SELECT
	WXK_PRINT
	WXK_EXECUTE
	WXK_SNAPSHOT
	WXK_INSERT
	WXK_HELP
	WXK_NUMPAD0
	WXK_NUMPAD1
	WXK_NUMPAD2
	WXK_NUMPAD3
	WXK_NUMPAD4
	WXK_NUMPAD5
	WXK_NUMPAD6
	WXK_NUMPAD7
	WXK_NUMPAD8
	WXK_NUMPAD9
	WXK_MULTIPLY
	WXK_ADD
	WXK_SEPARATOR
	WXK_SUBTRACT
	WXK_DECIMAL
	WXK_DIVIDE
	WXK_F1
	WXK_F2
	WXK_F3
	WXK_F4
	WXK_F5
	WXK_F6
	WXK_F7
	WXK_F8
	WXK_F9
	WXK_F10
	WXK_F11
	WXK_F12
	WXK_F13
	WXK_F14
	WXK_F15
	WXK_F16
	WXK_F17
	WXK_F18
	WXK_F19
	WXK_F20
	WXK_F21
	WXK_F22
	WXK_F23
	WXK_F24
	WXK_NUMLOCK
	WXK_SCROLL
	WXK_PAGEUP
	WXK_PAGEDOWN
	WXK_NUMPAD_SPACE
	WXK_NUMPAD_TAB
	WXK_NUMPAD_ENTER
	WXK_NUMPAD_F1
	WXK_NUMPAD_F2
	WXK_NUMPAD_F3
	WXK_NUMPAD_F4
	WXK_NUMPAD_HOME
	WXK_NUMPAD_LEFT
	WXK_NUMPAD_UP
	WXK_NUMPAD_RIGHT
	WXK_NUMPAD_DOWN
	WXK_NUMPAD_PRIOR
	WXK_NUMPAD_PAGEUP
	WXK_NUMPAD_NEXT
	WXK_NUMPAD_PAGEDOWN
	WXK_NUMPAD_END
	WXK_NUMPAD_BEGIN
	WXK_NUMPAD_INSERT
	WXK_NUMPAD_DELETE
	WXK_NUMPAD_EQUAL
	WXK_NUMPAD_MULTIPLY
	WXK_NUMPAD_ADD
	WXK_NUMPAD_SEPARATOR
	WXK_NUMPAD_SUBTRACT
	WXK_NUMPAD_DECIMAL
	WXK_NUMPAD_DIVIDE
end enum

enum 
	wxMM_TEXT = 1
	wxMM_LOMETRIC
	wxMM_HIMETRIC
	wxMM_LOENGLISH
	wxMM_HIENGLISH
	wxMM_TWIPS
	wxMM_ISOTROPIC
	wxMM_ANISOTROPIC
	wxMM_POINTS
	wxMM_METRIC
end enum

enum wxPaperSize
	wxPAPER_NONE
	wxPAPER_LETTER
	wxPAPER_LEGAL
	wxPAPER_A4
	wxPAPER_CSHEET
	wxPAPER_DSHEET
	wxPAPER_ESHEET
	wxPAPER_LETTERSMALL
	wxPAPER_TABLOID
	wxPAPER_LEDGER
	wxPAPER_STATEMENT
	wxPAPER_EXECUTIVE
	wxPAPER_A3
	wxPAPER_A4SMALL
	wxPAPER_A5
	wxPAPER_B4
	wxPAPER_B5
	wxPAPER_FOLIO
	wxPAPER_QUARTO
	wxPAPER_10X14
	wxPAPER_11X17
	wxPAPER_NOTE
	wxPAPER_ENV_9
	wxPAPER_ENV_10
	wxPAPER_ENV_11
	wxPAPER_ENV_12
	wxPAPER_ENV_14
	wxPAPER_ENV_DL
	wxPAPER_ENV_C5
	wxPAPER_ENV_C3
	wxPAPER_ENV_C4
	wxPAPER_ENV_C6
	wxPAPER_ENV_C65
	wxPAPER_ENV_B4
	wxPAPER_ENV_B5
	wxPAPER_ENV_B6
	wxPAPER_ENV_ITALY
	wxPAPER_ENV_MONARCH
	wxPAPER_ENV_PERSONAL
	wxPAPER_FANFOLD_US
	wxPAPER_FANFOLD_STD_GERMAN
	wxPAPER_FANFOLD_LGL_GERMAN
	wxPAPER_ISO_B4
	wxPAPER_JAPANESE_POSTCARD
	wxPAPER_9X11
	wxPAPER_10X11
	wxPAPER_15X11
	wxPAPER_ENV_INVITE
	wxPAPER_LETTER_EXTRA
	wxPAPER_LEGAL_EXTRA
	wxPAPER_TABLOID_EXTRA
	wxPAPER_A4_EXTRA
	wxPAPER_LETTER_TRANSVERSE
	wxPAPER_A4_TRANSVERSE
	wxPAPER_LETTER_EXTRA_TRANSVERSE
	wxPAPER_A_PLUS
	wxPAPER_B_PLUS
	wxPAPER_LETTER_PLUS
	wxPAPER_A4_PLUS
	wxPAPER_A5_TRANSVERSE
	wxPAPER_B5_TRANSVERSE
	wxPAPER_A3_EXTRA
	wxPAPER_A5_EXTRA
	wxPAPER_B5_EXTRA
	wxPAPER_A2
	wxPAPER_A3_TRANSVERSE
	wxPAPER_A3_EXTRA_TRANSVERSE
end enum


#define wxPORTRAIT 1
#define wxLANDSCAPE 2

enum wxDuplexMode
	wxDUPLEX_SIMPLEX
	wxDUPLEX_HORIZONTAL
	wxDUPLEX_VERTICAL
end enum

#define wxPRINT_QUALITY_HIGH -1
#define wxPRINT_QUALITY_MEDIUM -2
#define wxPRINT_QUALITY_LOW -3
#define wxPRINT_QUALITY_DRAFT -4

type wxPrintQuality as integer

enum wxPrintMode
	wxPRINT_MODE_NONE = 0
	wxPRINT_MODE_PREVIEW = 1
	wxPRINT_MODE_FILE = 2
	wxPRINT_MODE_PRINTER = 3
end enum

#define wxUSE_PANGO 0

#endif
