''
''
'' event -- header translated with help of SWIG FB wrapper
''
'' NOTICE: This file is part of the FreeBASIC Compiler package and can't
''         be included in other distributions without authorization.
''
''
#ifndef __wxc_event_bi__
#define __wxc_event_bi__

#include once "wx-c/wx.bi"

declare function wxEvent_EVT_COMMAND_BUTTON_CLICKED cdecl alias "wxEvent_EVT_COMMAND_BUTTON_CLICKED" () as integer
declare function wxEvent_EVT_COMMAND_CHECKBOX_CLICKED cdecl alias "wxEvent_EVT_COMMAND_CHECKBOX_CLICKED" () as integer
declare function wxEvent_EVT_COMMAND_CHOICE_SELECTED cdecl alias "wxEvent_EVT_COMMAND_CHOICE_SELECTED" () as integer
declare function wxEvent_EVT_COMMAND_LISTBOX_SELECTED cdecl alias "wxEvent_EVT_COMMAND_LISTBOX_SELECTED" () as integer
declare function wxEvent_EVT_COMMAND_LISTBOX_DOUBLECLICKED cdecl alias "wxEvent_EVT_COMMAND_LISTBOX_DOUBLECLICKED" () as integer
declare function wxEvent_EVT_COMMAND_CHECKLISTBOX_TOGGLED cdecl alias "wxEvent_EVT_COMMAND_CHECKLISTBOX_TOGGLED" () as integer
declare function wxEvent_EVT_COMMAND_TEXT_UPDATED cdecl alias "wxEvent_EVT_COMMAND_TEXT_UPDATED" () as integer
declare function wxEvent_EVT_COMMAND_TEXT_ENTER cdecl alias "wxEvent_EVT_COMMAND_TEXT_ENTER" () as integer
declare function wxEvent_EVT_COMMAND_TEXT_URL cdecl alias "wxEvent_EVT_COMMAND_TEXT_URL" () as integer
declare function wxEvent_EVT_COMMAND_TEXT_MAXLEN cdecl alias "wxEvent_EVT_COMMAND_TEXT_MAXLEN" () as integer
declare function wxEvent_EVT_COMMAND_MENU_SELECTED cdecl alias "wxEvent_EVT_COMMAND_MENU_SELECTED" () as integer
declare function wxEvent_EVT_COMMAND_SLIDER_UPDATED cdecl alias "wxEvent_EVT_COMMAND_SLIDER_UPDATED" () as integer
declare function wxEvent_EVT_COMMAND_RADIOBOX_SELECTED cdecl alias "wxEvent_EVT_COMMAND_RADIOBOX_SELECTED" () as integer
declare function wxEvent_EVT_COMMAND_RADIOBUTTON_SELECTED cdecl alias "wxEvent_EVT_COMMAND_RADIOBUTTON_SELECTED" () as integer
declare function wxEvent_EVT_COMMAND_SCROLLBAR_UPDATED cdecl alias "wxEvent_EVT_COMMAND_SCROLLBAR_UPDATED" () as integer
declare function wxEvent_EVT_COMMAND_VLBOX_SELECTED cdecl alias "wxEvent_EVT_COMMAND_VLBOX_SELECTED" () as integer
declare function wxEvent_EVT_COMMAND_COMBOBOX_SELECTED cdecl alias "wxEvent_EVT_COMMAND_COMBOBOX_SELECTED" () as integer
declare function wxEvent_EVT_COMMAND_TOOL_RCLICKED cdecl alias "wxEvent_EVT_COMMAND_TOOL_RCLICKED" () as integer
declare function wxEvent_EVT_COMMAND_TOOL_ENTER cdecl alias "wxEvent_EVT_COMMAND_TOOL_ENTER" () as integer
declare function wxEvent_EVT_COMMAND_SPINCTRL_UPDATED cdecl alias "wxEvent_EVT_COMMAND_SPINCTRL_UPDATED" () as integer
declare function wxEvent_EVT_SOCKET cdecl alias "wxEvent_EVT_SOCKET" () as integer
declare function wxEvent_EVT_TIMER cdecl alias "wxEvent_EVT_TIMER" () as integer
declare function wxEvent_EVT_LEFT_DOWN cdecl alias "wxEvent_EVT_LEFT_DOWN" () as integer
declare function wxEvent_EVT_LEFT_UP cdecl alias "wxEvent_EVT_LEFT_UP" () as integer
declare function wxEvent_EVT_MIDDLE_DOWN cdecl alias "wxEvent_EVT_MIDDLE_DOWN" () as integer
declare function wxEvent_EVT_MIDDLE_UP cdecl alias "wxEvent_EVT_MIDDLE_UP" () as integer
declare function wxEvent_EVT_RIGHT_DOWN cdecl alias "wxEvent_EVT_RIGHT_DOWN" () as integer
declare function wxEvent_EVT_RIGHT_UP cdecl alias "wxEvent_EVT_RIGHT_UP" () as integer
declare function wxEvent_EVT_MOTION cdecl alias "wxEvent_EVT_MOTION" () as integer
declare function wxEvent_EVT_ENTER_WINDOW cdecl alias "wxEvent_EVT_ENTER_WINDOW" () as integer
declare function wxEvent_EVT_LEAVE_WINDOW cdecl alias "wxEvent_EVT_LEAVE_WINDOW" () as integer
declare function wxEvent_EVT_LEFT_DCLICK cdecl alias "wxEvent_EVT_LEFT_DCLICK" () as integer
declare function wxEvent_EVT_MIDDLE_DCLICK cdecl alias "wxEvent_EVT_MIDDLE_DCLICK" () as integer
declare function wxEvent_EVT_RIGHT_DCLICK cdecl alias "wxEvent_EVT_RIGHT_DCLICK" () as integer
declare function wxEvent_EVT_SET_FOCUS cdecl alias "wxEvent_EVT_SET_FOCUS" () as integer
declare function wxEvent_EVT_KILL_FOCUS cdecl alias "wxEvent_EVT_KILL_FOCUS" () as integer
declare function wxEvent_EVT_CHILD_FOCUS cdecl alias "wxEvent_EVT_CHILD_FOCUS" () as integer
declare function wxEvent_EVT_MOUSEWHEEL cdecl alias "wxEvent_EVT_MOUSEWHEEL" () as integer
declare function wxEvent_EVT_NC_LEFT_DOWN cdecl alias "wxEvent_EVT_NC_LEFT_DOWN" () as integer
declare function wxEvent_EVT_NC_LEFT_UP cdecl alias "wxEvent_EVT_NC_LEFT_UP" () as integer
declare function wxEvent_EVT_NC_MIDDLE_DOWN cdecl alias "wxEvent_EVT_NC_MIDDLE_DOWN" () as integer
declare function wxEvent_EVT_NC_MIDDLE_UP cdecl alias "wxEvent_EVT_NC_MIDDLE_UP" () as integer
declare function wxEvent_EVT_NC_RIGHT_DOWN cdecl alias "wxEvent_EVT_NC_RIGHT_DOWN" () as integer
declare function wxEvent_EVT_NC_RIGHT_UP cdecl alias "wxEvent_EVT_NC_RIGHT_UP" () as integer
declare function wxEvent_EVT_NC_MOTION cdecl alias "wxEvent_EVT_NC_MOTION" () as integer
declare function wxEvent_EVT_NC_ENTER_WINDOW cdecl alias "wxEvent_EVT_NC_ENTER_WINDOW" () as integer
declare function wxEvent_EVT_NC_LEAVE_WINDOW cdecl alias "wxEvent_EVT_NC_LEAVE_WINDOW" () as integer
declare function wxEvent_EVT_NC_LEFT_DCLICK cdecl alias "wxEvent_EVT_NC_LEFT_DCLICK" () as integer
declare function wxEvent_EVT_NC_MIDDLE_DCLICK cdecl alias "wxEvent_EVT_NC_MIDDLE_DCLICK" () as integer
declare function wxEvent_EVT_NC_RIGHT_DCLICK cdecl alias "wxEvent_EVT_NC_RIGHT_DCLICK" () as integer
declare function wxEvent_EVT_CHAR cdecl alias "wxEvent_EVT_CHAR" () as integer
declare function wxEvent_EVT_CHAR_HOOK cdecl alias "wxEvent_EVT_CHAR_HOOK" () as integer
declare function wxEvent_EVT_NAVIGATION_KEY cdecl alias "wxEvent_EVT_NAVIGATION_KEY" () as integer
declare function wxEvent_EVT_KEY_DOWN cdecl alias "wxEvent_EVT_KEY_DOWN" () as integer
declare function wxEvent_EVT_KEY_UP cdecl alias "wxEvent_EVT_KEY_UP" () as integer
declare function wxEvent_EVT_SET_CURSOR cdecl alias "wxEvent_EVT_SET_CURSOR" () as integer
declare function wxEvent_EVT_SCROLL_TOP cdecl alias "wxEvent_EVT_SCROLL_TOP" () as integer
declare function wxEvent_EVT_SCROLL_BOTTOM cdecl alias "wxEvent_EVT_SCROLL_BOTTOM" () as integer
declare function wxEvent_EVT_SCROLL_LINEUP cdecl alias "wxEvent_EVT_SCROLL_LINEUP" () as integer
declare function wxEvent_EVT_SCROLL_LINEDOWN cdecl alias "wxEvent_EVT_SCROLL_LINEDOWN" () as integer
declare function wxEvent_EVT_SCROLL_PAGEUP cdecl alias "wxEvent_EVT_SCROLL_PAGEUP" () as integer
declare function wxEvent_EVT_SCROLL_PAGEDOWN cdecl alias "wxEvent_EVT_SCROLL_PAGEDOWN" () as integer
declare function wxEvent_EVT_SCROLL_THUMBTRACK cdecl alias "wxEvent_EVT_SCROLL_THUMBTRACK" () as integer
declare function wxEvent_EVT_SCROLL_THUMBRELEASE cdecl alias "wxEvent_EVT_SCROLL_THUMBRELEASE" () as integer
declare function wxEvent_EVT_SCROLL_ENDSCROLL cdecl alias "wxEvent_EVT_SCROLL_ENDSCROLL" () as integer
declare function wxEvent_EVT_SCROLLWIN_TOP cdecl alias "wxEvent_EVT_SCROLLWIN_TOP" () as integer
declare function wxEvent_EVT_SCROLLWIN_BOTTOM cdecl alias "wxEvent_EVT_SCROLLWIN_BOTTOM" () as integer
declare function wxEvent_EVT_SCROLLWIN_LINEUP cdecl alias "wxEvent_EVT_SCROLLWIN_LINEUP" () as integer
declare function wxEvent_EVT_SCROLLWIN_LINEDOWN cdecl alias "wxEvent_EVT_SCROLLWIN_LINEDOWN" () as integer
declare function wxEvent_EVT_SCROLLWIN_PAGEUP cdecl alias "wxEvent_EVT_SCROLLWIN_PAGEUP" () as integer
declare function wxEvent_EVT_SCROLLWIN_PAGEDOWN cdecl alias "wxEvent_EVT_SCROLLWIN_PAGEDOWN" () as integer
declare function wxEvent_EVT_SCROLLWIN_THUMBTRACK cdecl alias "wxEvent_EVT_SCROLLWIN_THUMBTRACK" () as integer
declare function wxEvent_EVT_SCROLLWIN_THUMBRELEASE cdecl alias "wxEvent_EVT_SCROLLWIN_THUMBRELEASE" () as integer
declare function wxEvent_EVT_SIZE cdecl alias "wxEvent_EVT_SIZE" () as integer
declare function wxEvent_EVT_MOVE cdecl alias "wxEvent_EVT_MOVE" () as integer
declare function wxEvent_EVT_CLOSE_WINDOW cdecl alias "wxEvent_EVT_CLOSE_WINDOW" () as integer
declare function wxEvent_EVT_END_SESSION cdecl alias "wxEvent_EVT_END_SESSION" () as integer
declare function wxEvent_EVT_QUERY_END_SESSION cdecl alias "wxEvent_EVT_QUERY_END_SESSION" () as integer
declare function wxEvent_EVT_ACTIVATE_APP cdecl alias "wxEvent_EVT_ACTIVATE_APP" () as integer
declare function wxEvent_EVT_POWER cdecl alias "wxEvent_EVT_POWER" () as integer
declare function wxEvent_EVT_ACTIVATE cdecl alias "wxEvent_EVT_ACTIVATE" () as integer
declare function wxEvent_EVT_CREATE cdecl alias "wxEvent_EVT_CREATE" () as integer
declare function wxEvent_EVT_DESTROY cdecl alias "wxEvent_EVT_DESTROY" () as integer
declare function wxEvent_EVT_SHOW cdecl alias "wxEvent_EVT_SHOW" () as integer
declare function wxEvent_EVT_ICONIZE cdecl alias "wxEvent_EVT_ICONIZE" () as integer
declare function wxEvent_EVT_MAXIMIZE cdecl alias "wxEvent_EVT_MAXIMIZE" () as integer
declare function wxEvent_EVT_MOUSE_CAPTURE_CHANGED cdecl alias "wxEvent_EVT_MOUSE_CAPTURE_CHANGED" () as integer
declare function wxEvent_EVT_PAINT cdecl alias "wxEvent_EVT_PAINT" () as integer
declare function wxEvent_EVT_ERASE_BACKGROUND cdecl alias "wxEvent_EVT_ERASE_BACKGROUND" () as integer
declare function wxEvent_EVT_NC_PAINT cdecl alias "wxEvent_EVT_NC_PAINT" () as integer
declare function wxEvent_EVT_PAINT_ICON cdecl alias "wxEvent_EVT_PAINT_ICON" () as integer
declare function wxEvent_EVT_MENU_OPEN cdecl alias "wxEvent_EVT_MENU_OPEN" () as integer
declare function wxEvent_EVT_MENU_CLOSE cdecl alias "wxEvent_EVT_MENU_CLOSE" () as integer
declare function wxEvent_EVT_MENU_HIGHLIGHT cdecl alias "wxEvent_EVT_MENU_HIGHLIGHT" () as integer
declare function wxEvent_EVT_CONTEXT_MENU cdecl alias "wxEvent_EVT_CONTEXT_MENU" () as integer
declare function wxEvent_EVT_SYS_COLOUR_CHANGED cdecl alias "wxEvent_EVT_SYS_COLOUR_CHANGED" () as integer
declare function wxEvent_EVT_DISPLAY_CHANGED cdecl alias "wxEvent_EVT_DISPLAY_CHANGED" () as integer
declare function wxEvent_EVT_SETTING_CHANGED cdecl alias "wxEvent_EVT_SETTING_CHANGED" () as integer
declare function wxEvent_EVT_QUERY_NEW_PALETTE cdecl alias "wxEvent_EVT_QUERY_NEW_PALETTE" () as integer
declare function wxEvent_EVT_PALETTE_CHANGED cdecl alias "wxEvent_EVT_PALETTE_CHANGED" () as integer
declare function wxEvent_EVT_JOY_BUTTON_DOWN cdecl alias "wxEvent_EVT_JOY_BUTTON_DOWN" () as integer
declare function wxEvent_EVT_JOY_BUTTON_UP cdecl alias "wxEvent_EVT_JOY_BUTTON_UP" () as integer
declare function wxEvent_EVT_JOY_MOVE cdecl alias "wxEvent_EVT_JOY_MOVE" () as integer
declare function wxEvent_EVT_JOY_ZMOVE cdecl alias "wxEvent_EVT_JOY_ZMOVE" () as integer
declare function wxEvent_EVT_DROP_FILES cdecl alias "wxEvent_EVT_DROP_FILES" () as integer
declare function wxEvent_EVT_DRAW_ITEM cdecl alias "wxEvent_EVT_DRAW_ITEM" () as integer
declare function wxEvent_EVT_MEASURE_ITEM cdecl alias "wxEvent_EVT_MEASURE_ITEM" () as integer
declare function wxEvent_EVT_COMPARE_ITEM cdecl alias "wxEvent_EVT_COMPARE_ITEM" () as integer
declare function wxEvent_EVT_INIT_DIALOG cdecl alias "wxEvent_EVT_INIT_DIALOG" () as integer
declare function wxEvent_EVT_IDLE cdecl alias "wxEvent_EVT_IDLE" () as integer
declare function wxEvent_EVT_UPDATE_UI cdecl alias "wxEvent_EVT_UPDATE_UI" () as integer
declare function wxEvent_EVT_SIZING cdecl alias "wxEvent_EVT_SIZING" () as integer
declare function wxEvent_EVT_MOVING cdecl alias "wxEvent_EVT_MOVING" () as integer
declare function wxEvent_EVT_COMMAND_LEFT_CLICK cdecl alias "wxEvent_EVT_COMMAND_LEFT_CLICK" () as integer
declare function wxEvent_EVT_COMMAND_LEFT_DCLICK cdecl alias "wxEvent_EVT_COMMAND_LEFT_DCLICK" () as integer
declare function wxEvent_EVT_COMMAND_RIGHT_CLICK cdecl alias "wxEvent_EVT_COMMAND_RIGHT_CLICK" () as integer
declare function wxEvent_EVT_COMMAND_RIGHT_DCLICK cdecl alias "wxEvent_EVT_COMMAND_RIGHT_DCLICK" () as integer
declare function wxEvent_EVT_COMMAND_SET_FOCUS cdecl alias "wxEvent_EVT_COMMAND_SET_FOCUS" () as integer
declare function wxEvent_EVT_COMMAND_KILL_FOCUS cdecl alias "wxEvent_EVT_COMMAND_KILL_FOCUS" () as integer
declare function wxEvent_EVT_COMMAND_ENTER cdecl alias "wxEvent_EVT_COMMAND_ENTER" () as integer
declare function wxEvent_EVT_HELP cdecl alias "wxEvent_EVT_HELP" () as integer
declare function wxEvent_EVT_DETAILED_HELP cdecl alias "wxEvent_EVT_DETAILED_HELP" () as integer
declare function wxEvent_EVT_COMMAND_TOGGLEBUTTON_CLICKED cdecl alias "wxEvent_EVT_COMMAND_TOGGLEBUTTON_CLICKED" () as integer
declare function wxEvent_EVT_OBJECTDELETED cdecl alias "wxEvent_EVT_OBJECTDELETED" () as integer
declare function wxEvent_EVT_CALENDAR_SEL_CHANGED cdecl alias "wxEvent_EVT_CALENDAR_SEL_CHANGED" () as integer
declare function wxEvent_EVT_CALENDAR_DAY_CHANGED cdecl alias "wxEvent_EVT_CALENDAR_DAY_CHANGED" () as integer
declare function wxEvent_EVT_CALENDAR_MONTH_CHANGED cdecl alias "wxEvent_EVT_CALENDAR_MONTH_CHANGED" () as integer
declare function wxEvent_EVT_CALENDAR_YEAR_CHANGED cdecl alias "wxEvent_EVT_CALENDAR_YEAR_CHANGED" () as integer
declare function wxEvent_EVT_CALENDAR_DOUBLECLICKED cdecl alias "wxEvent_EVT_CALENDAR_DOUBLECLICKED" () as integer
declare function wxEvent_EVT_CALENDAR_WEEKDAY_CLICKED cdecl alias "wxEvent_EVT_CALENDAR_WEEKDAY_CLICKED" () as integer
declare function wxEvent_EVT_COMMAND_FIND cdecl alias "wxEvent_EVT_COMMAND_FIND" () as integer
declare function wxEvent_EVT_COMMAND_FIND_NEXT cdecl alias "wxEvent_EVT_COMMAND_FIND_NEXT" () as integer
declare function wxEvent_EVT_COMMAND_FIND_REPLACE cdecl alias "wxEvent_EVT_COMMAND_FIND_REPLACE" () as integer
declare function wxEvent_EVT_COMMAND_FIND_REPLACE_ALL cdecl alias "wxEvent_EVT_COMMAND_FIND_REPLACE_ALL" () as integer
declare function wxEvent_EVT_COMMAND_FIND_CLOSE cdecl alias "wxEvent_EVT_COMMAND_FIND_CLOSE" () as integer
declare function wxEvent_EVT_COMMAND_TREE_BEGIN_DRAG cdecl alias "wxEvent_EVT_COMMAND_TREE_BEGIN_DRAG" () as integer
declare function wxEvent_EVT_COMMAND_TREE_BEGIN_RDRAG cdecl alias "wxEvent_EVT_COMMAND_TREE_BEGIN_RDRAG" () as integer
declare function wxEvent_EVT_COMMAND_TREE_BEGIN_LABEL_EDIT cdecl alias "wxEvent_EVT_COMMAND_TREE_BEGIN_LABEL_EDIT" () as integer
declare function wxEvent_EVT_COMMAND_TREE_END_LABEL_EDIT cdecl alias "wxEvent_EVT_COMMAND_TREE_END_LABEL_EDIT" () as integer
declare function wxEvent_EVT_COMMAND_TREE_DELETE_ITEM cdecl alias "wxEvent_EVT_COMMAND_TREE_DELETE_ITEM" () as integer
declare function wxEvent_EVT_COMMAND_TREE_GET_INFO cdecl alias "wxEvent_EVT_COMMAND_TREE_GET_INFO" () as integer
declare function wxEvent_EVT_COMMAND_TREE_SET_INFO cdecl alias "wxEvent_EVT_COMMAND_TREE_SET_INFO" () as integer
declare function wxEvent_EVT_COMMAND_TREE_ITEM_EXPANDED cdecl alias "wxEvent_EVT_COMMAND_TREE_ITEM_EXPANDED" () as integer
declare function wxEvent_EVT_COMMAND_TREE_ITEM_EXPANDING cdecl alias "wxEvent_EVT_COMMAND_TREE_ITEM_EXPANDING" () as integer
declare function wxEvent_EVT_COMMAND_TREE_ITEM_COLLAPSED cdecl alias "wxEvent_EVT_COMMAND_TREE_ITEM_COLLAPSED" () as integer
declare function wxEvent_EVT_COMMAND_TREE_ITEM_COLLAPSING cdecl alias "wxEvent_EVT_COMMAND_TREE_ITEM_COLLAPSING" () as integer
declare function wxEvent_EVT_COMMAND_TREE_SEL_CHANGED cdecl alias "wxEvent_EVT_COMMAND_TREE_SEL_CHANGED" () as integer
declare function wxEvent_EVT_COMMAND_TREE_SEL_CHANGING cdecl alias "wxEvent_EVT_COMMAND_TREE_SEL_CHANGING" () as integer
declare function wxEvent_EVT_COMMAND_TREE_KEY_DOWN cdecl alias "wxEvent_EVT_COMMAND_TREE_KEY_DOWN" () as integer
declare function wxEvent_EVT_COMMAND_TREE_ITEM_ACTIVATED cdecl alias "wxEvent_EVT_COMMAND_TREE_ITEM_ACTIVATED" () as integer
declare function wxEvent_EVT_COMMAND_TREE_ITEM_RIGHT_CLICK cdecl alias "wxEvent_EVT_COMMAND_TREE_ITEM_RIGHT_CLICK" () as integer
declare function wxEvent_EVT_COMMAND_TREE_ITEM_MIDDLE_CLICK cdecl alias "wxEvent_EVT_COMMAND_TREE_ITEM_MIDDLE_CLICK" () as integer
declare function wxEvent_EVT_COMMAND_TREE_END_DRAG cdecl alias "wxEvent_EVT_COMMAND_TREE_END_DRAG" () as integer
declare function wxEvent_EVT_COMMAND_LIST_BEGIN_DRAG cdecl alias "wxEvent_EVT_COMMAND_LIST_BEGIN_DRAG" () as integer
declare function wxEvent_EVT_COMMAND_LIST_BEGIN_RDRAG cdecl alias "wxEvent_EVT_COMMAND_LIST_BEGIN_RDRAG" () as integer
declare function wxEvent_EVT_COMMAND_LIST_BEGIN_LABEL_EDIT cdecl alias "wxEvent_EVT_COMMAND_LIST_BEGIN_LABEL_EDIT" () as integer
declare function wxEvent_EVT_COMMAND_LIST_END_LABEL_EDIT cdecl alias "wxEvent_EVT_COMMAND_LIST_END_LABEL_EDIT" () as integer
declare function wxEvent_EVT_COMMAND_LIST_DELETE_ITEM cdecl alias "wxEvent_EVT_COMMAND_LIST_DELETE_ITEM" () as integer
declare function wxEvent_EVT_COMMAND_LIST_DELETE_ALL_ITEMS cdecl alias "wxEvent_EVT_COMMAND_LIST_DELETE_ALL_ITEMS" () as integer
declare function wxEvent_EVT_COMMAND_LIST_GET_INFO cdecl alias "wxEvent_EVT_COMMAND_LIST_GET_INFO" () as integer
declare function wxEvent_EVT_COMMAND_LIST_SET_INFO cdecl alias "wxEvent_EVT_COMMAND_LIST_SET_INFO" () as integer
declare function wxEvent_EVT_COMMAND_LIST_ITEM_SELECTED cdecl alias "wxEvent_EVT_COMMAND_LIST_ITEM_SELECTED" () as integer
declare function wxEvent_EVT_COMMAND_LIST_ITEM_DESELECTED cdecl alias "wxEvent_EVT_COMMAND_LIST_ITEM_DESELECTED" () as integer
declare function wxEvent_EVT_COMMAND_LIST_ITEM_ACTIVATED cdecl alias "wxEvent_EVT_COMMAND_LIST_ITEM_ACTIVATED" () as integer
declare function wxEvent_EVT_COMMAND_LIST_ITEM_FOCUSED cdecl alias "wxEvent_EVT_COMMAND_LIST_ITEM_FOCUSED" () as integer
declare function wxEvent_EVT_COMMAND_LIST_ITEM_MIDDLE_CLICK cdecl alias "wxEvent_EVT_COMMAND_LIST_ITEM_MIDDLE_CLICK" () as integer
declare function wxEvent_EVT_COMMAND_LIST_ITEM_RIGHT_CLICK cdecl alias "wxEvent_EVT_COMMAND_LIST_ITEM_RIGHT_CLICK" () as integer
declare function wxEvent_EVT_COMMAND_LIST_KEY_DOWN cdecl alias "wxEvent_EVT_COMMAND_LIST_KEY_DOWN" () as integer
declare function wxEvent_EVT_COMMAND_LIST_INSERT_ITEM cdecl alias "wxEvent_EVT_COMMAND_LIST_INSERT_ITEM" () as integer
declare function wxEvent_EVT_COMMAND_LIST_COL_CLICK cdecl alias "wxEvent_EVT_COMMAND_LIST_COL_CLICK" () as integer
declare function wxEvent_EVT_COMMAND_LIST_COL_RIGHT_CLICK cdecl alias "wxEvent_EVT_COMMAND_LIST_COL_RIGHT_CLICK" () as integer
declare function wxEvent_EVT_COMMAND_LIST_COL_BEGIN_DRAG cdecl alias "wxEvent_EVT_COMMAND_LIST_COL_BEGIN_DRAG" () as integer
declare function wxEvent_EVT_COMMAND_LIST_COL_DRAGGING cdecl alias "wxEvent_EVT_COMMAND_LIST_COL_DRAGGING" () as integer
declare function wxEvent_EVT_COMMAND_LIST_COL_END_DRAG cdecl alias "wxEvent_EVT_COMMAND_LIST_COL_END_DRAG" () as integer
declare function wxEvent_EVT_COMMAND_LIST_CACHE_HINT cdecl alias "wxEvent_EVT_COMMAND_LIST_CACHE_HINT" () as integer
declare function wxEvent_EVT_COMMAND_NOTEBOOK_PAGE_CHANGED cdecl alias "wxEvent_EVT_COMMAND_NOTEBOOK_PAGE_CHANGED" () as integer
declare function wxEvent_EVT_COMMAND_NOTEBOOK_PAGE_CHANGING cdecl alias "wxEvent_EVT_COMMAND_NOTEBOOK_PAGE_CHANGING" () as integer
declare function wxEvent_EVT_COMMAND_LISTBOOK_PAGE_CHANGED cdecl alias "wxEvent_EVT_COMMAND_LISTBOOK_PAGE_CHANGED" () as integer
declare function wxEvent_EVT_COMMAND_LISTBOOK_PAGE_CHANGING cdecl alias "wxEvent_EVT_COMMAND_LISTBOOK_PAGE_CHANGING" () as integer
declare function wxEvent_EVT_GRID_CELL_LEFT_CLICK cdecl alias "wxEvent_EVT_GRID_CELL_LEFT_CLICK" () as integer
declare function wxEvent_EVT_GRID_CELL_RIGHT_CLICK cdecl alias "wxEvent_EVT_GRID_CELL_RIGHT_CLICK" () as integer
declare function wxEvent_EVT_GRID_CELL_LEFT_DCLICK cdecl alias "wxEvent_EVT_GRID_CELL_LEFT_DCLICK" () as integer
declare function wxEvent_EVT_GRID_CELL_RIGHT_DCLICK cdecl alias "wxEvent_EVT_GRID_CELL_RIGHT_DCLICK" () as integer
declare function wxEvent_EVT_GRID_LABEL_LEFT_CLICK cdecl alias "wxEvent_EVT_GRID_LABEL_LEFT_CLICK" () as integer
declare function wxEvent_EVT_GRID_LABEL_RIGHT_CLICK cdecl alias "wxEvent_EVT_GRID_LABEL_RIGHT_CLICK" () as integer
declare function wxEvent_EVT_GRID_LABEL_LEFT_DCLICK cdecl alias "wxEvent_EVT_GRID_LABEL_LEFT_DCLICK" () as integer
declare function wxEvent_EVT_GRID_LABEL_RIGHT_DCLICK cdecl alias "wxEvent_EVT_GRID_LABEL_RIGHT_DCLICK" () as integer
declare function wxEvent_EVT_GRID_ROW_SIZE cdecl alias "wxEvent_EVT_GRID_ROW_SIZE" () as integer
declare function wxEvent_EVT_GRID_COL_SIZE cdecl alias "wxEvent_EVT_GRID_COL_SIZE" () as integer
declare function wxEvent_EVT_GRID_RANGE_SELECT cdecl alias "wxEvent_EVT_GRID_RANGE_SELECT" () as integer
declare function wxEvent_EVT_GRID_CELL_CHANGE cdecl alias "wxEvent_EVT_GRID_CELL_CHANGE" () as integer
declare function wxEvent_EVT_GRID_SELECT_CELL cdecl alias "wxEvent_EVT_GRID_SELECT_CELL" () as integer
declare function wxEvent_EVT_GRID_EDITOR_SHOWN cdecl alias "wxEvent_EVT_GRID_EDITOR_SHOWN" () as integer
declare function wxEvent_EVT_GRID_EDITOR_HIDDEN cdecl alias "wxEvent_EVT_GRID_EDITOR_HIDDEN" () as integer
declare function wxEvent_EVT_GRID_EDITOR_CREATED cdecl alias "wxEvent_EVT_GRID_EDITOR_CREATED" () as integer
declare function wxEvent_EVT_SASH_DRAGGED cdecl alias "wxEvent_EVT_SASH_DRAGGED" () as integer
declare function wxEvent_EVT_QUERY_LAYOUT_INFO cdecl alias "wxEvent_EVT_QUERY_LAYOUT_INFO" () as integer
declare function wxEvent_EVT_CALCULATE_LAYOUT cdecl alias "wxEvent_EVT_CALCULATE_LAYOUT" () as integer
declare function wxEvent_GetEventType cdecl alias "wxEvent_GetEventType" (byval self as wxEvent ptr) as integer
declare function wxEvent_GetId cdecl alias "wxEvent_GetId" (byval self as wxEvent ptr) as integer
declare function wxEvent_GetSkipped cdecl alias "wxEvent_GetSkipped" (byval self as wxEvent ptr) as integer
declare function wxEvent_GetTimestamp cdecl alias "wxEvent_GetTimestamp" (byval self as wxEvent ptr) as integer
declare sub wxEvent_Skip cdecl alias "wxEvent_Skip" (byval self as wxEvent ptr, byval skip as integer)
declare function wxEvent_GetEventObject cdecl alias "wxEvent_GetEventObject" (byval self as wxEvent ptr) as wxObject ptr

#endif
