''
''
'' wx-c -- wxWindows C-wrapper (header translated with help of SWIG FB wrapper)
''
'' NOTICE: This file is part of the FreeBASIC Compiler package and can't
''         be included in other distributions without authorization.
''
''
#ifndef __wxc_wx_bi__
#define __wxc_wx_bi__

#inclib "wx-c"

extern "c"

#include once "defs.bi"
#include once "classes.bi"

#include once "accel.bi"
#include once "activateevent.bi"
#include once "app.bi"
#include once "artprovider.bi"
#include once "bitmap.bi"
#include once "bitmapbutton.bi"
#include once "boxsizer.bi"
#include once "brush.bi"
#include once "button.bi"
#include once "calendarctrl.bi"
#include once "caret.bi"
#include once "checkbox.bi"
#include once "childfocusevent.bi"
#include once "choice.bi"
#include once "choicedialog.bi"
#include once "clientdata.bi"
#include once "clipboard.bi"
#include once "closeevent.bi"
#include once "colour.bi"
#include once "colourdialog.bi"
#include once "combobox.bi"
#include once "commandevent.bi"
#include once "config.bi"
#include once "contextmenuevent.bi"
#include once "control.bi"
#include once "cursor.bi"
#include once "dataformat.bi"
#include once "dataobject.bi"
#include once "dc.bi"
#include once "dialog.bi"
#include once "dirdialog.bi"
#include once "display.bi"
#include once "displaychangedevent.bi"
#include once "dnd.bi"
#include once "docmanager.bi"
#include once "doctemplate.bi"
#include once "document.bi"
#include once "eraseevent.bi"
#include once "event.bi"
#include once "evthandler.bi"
#include once "filedialog.bi"
#include once "findreplacedialog.bi"
#include once "flexgridsizer.bi"
#include once "focusevent.bi"
#include once "font.bi"
#include once "fontdialog.bi"
#include once "fontmisc.bi"
#include once "frame.bi"
#include once "gauge.bi"
#include once "gdicmn.bi"
#include once "gdiobject.bi"
#include once "global.bi"
#include once "grid.bi"
#include once "gridbagsizer.bi"
#include once "gridctrl.bi"
#include once "gridsizer.bi"
#include once "helpevent.bi"
#include once "html.bi"
#include once "htmlhelpctrl.bi"
#include once "htmllbox.bi"
#include once "icon.bi"
#include once "iconizeevent.bi"
#include once "idleevent.bi"
#include once "image.bi"
#include once "imagelist.bi"
#include once "imghandler.bi"
#include once "initdialogevent.bi"
#include once "keyevent.bi"
#include once "laywin.bi"
#include once "listbook.bi"
#include once "listbox.bi"
#include once "listctrl.bi"
#include once "locale.bi"
#include once "log.bi"
#include once "maximizeevent.bi"
#include once "mdi.bi"
#include once "memorydc.bi"
#include once "menu.bi"
#include once "menubar.bi"
#include once "menuitem.bi"
#include once "messagedialog.bi"
#include once "miniframe.bi"
#include once "mousecapturechangedevent.bi"
#include once "mouseevent.bi"
#include once "moveevent.bi"
#include once "navigationkeyevent.bi"
#include once "ncpaintevent.bi"
#include once "notebook.bi"
#include once "notebooksizer.bi"
#include once "object.bi"
#include once "paintevent.bi"
#include once "palette.bi"
#include once "palettechangedevent.bi"
#include once "panel.bi"
#include once "pen.bi"
#include once "printdata.bi"
#include once "printdialog.bi"
#include once "printer.bi"
#include once "printpreview.bi"
#include once "progdlg.bi"
#include once "querynewpaletteevent.bi"
#include once "radiobox.bi"
#include once "radiobutton.bi"
#include once "region.bi"
#include once "sashwindow.bi"
#include once "scrollbar.bi"
#include once "scrolledwindow.bi"
#include once "setcursorevent.bi"
#include once "showevent.bi"
#include once "sizeevent.bi"
#include once "sizer.bi"
#include once "sizeritem.bi"
#include once "slider.bi"
#include once "spinbutton.bi"
#include once "spinctrl.bi"
#include once "splashscreen.bi"
#include once "splitterwindow.bi"
#include once "staticbitmap.bi"
#include once "staticbox.bi"
#include once "staticboxsizer.bi"
#include once "staticline.bi"
#include once "statictext.bi"
#include once "statusbar.bi"
#include once "styledtextctrl.bi"
#include once "syscolourchangedevent.bi"
#include once "systemsettings.bi"
#include once "tabctrl.bi"
#include once "textctrl.bi"
#include once "textdialog.bi"
#include once "tipdialog.bi"
#include once "tipwindow.bi"
#include once "togglebutton.bi"
#include once "toolbar.bi"
#include once "tooltip.bi"
#include once "treectrl.bi"
#include once "updateuievent.bi"
#include once "validator.bi"
#include once "view.bi"
#include once "vlbox.bi"
#include once "vscroll.bi"
#include once "window.bi"
#include once "windowcreateevent.bi"
#include once "windowdestroyevent.bi"
#include once "wizard.bi"
#include once "wizardpagesimple.bi"
#include once "wxdatetime.bi"
#include once "wxstring.bi"
#include once "xmlresource.bi"

end extern

#endif
