''
''
'' xmlunicode -- header translated with help of SWIG FB wrapper
''
'' NOTICE: This file is part of the FreeBASIC Compiler package and can't
''         be included in other distributions without authorization.
''
''
#ifndef __xmlunicode_bi__
#define __xmlunicode_bi__

#include once "libxml/xmlversion.bi"

declare function xmlUCSIsAegeanNumbers cdecl alias "xmlUCSIsAegeanNumbers" (byval code as integer) as integer
declare function xmlUCSIsAlphabeticPresentationForms cdecl alias "xmlUCSIsAlphabeticPresentationForms" (byval code as integer) as integer
declare function xmlUCSIsArabic cdecl alias "xmlUCSIsArabic" (byval code as integer) as integer
declare function xmlUCSIsArabicPresentationFormsA cdecl alias "xmlUCSIsArabicPresentationFormsA" (byval code as integer) as integer
declare function xmlUCSIsArabicPresentationFormsB cdecl alias "xmlUCSIsArabicPresentationFormsB" (byval code as integer) as integer
declare function xmlUCSIsArmenian cdecl alias "xmlUCSIsArmenian" (byval code as integer) as integer
declare function xmlUCSIsArrows cdecl alias "xmlUCSIsArrows" (byval code as integer) as integer
declare function xmlUCSIsBasicLatin cdecl alias "xmlUCSIsBasicLatin" (byval code as integer) as integer
declare function xmlUCSIsBengali cdecl alias "xmlUCSIsBengali" (byval code as integer) as integer
declare function xmlUCSIsBlockElements cdecl alias "xmlUCSIsBlockElements" (byval code as integer) as integer
declare function xmlUCSIsBopomofo cdecl alias "xmlUCSIsBopomofo" (byval code as integer) as integer
declare function xmlUCSIsBopomofoExtended cdecl alias "xmlUCSIsBopomofoExtended" (byval code as integer) as integer
declare function xmlUCSIsBoxDrawing cdecl alias "xmlUCSIsBoxDrawing" (byval code as integer) as integer
declare function xmlUCSIsBraillePatterns cdecl alias "xmlUCSIsBraillePatterns" (byval code as integer) as integer
declare function xmlUCSIsBuhid cdecl alias "xmlUCSIsBuhid" (byval code as integer) as integer
declare function xmlUCSIsByzantineMusicalSymbols cdecl alias "xmlUCSIsByzantineMusicalSymbols" (byval code as integer) as integer
declare function xmlUCSIsCJKCompatibility cdecl alias "xmlUCSIsCJKCompatibility" (byval code as integer) as integer
declare function xmlUCSIsCJKCompatibilityForms cdecl alias "xmlUCSIsCJKCompatibilityForms" (byval code as integer) as integer
declare function xmlUCSIsCJKCompatibilityIdeographs cdecl alias "xmlUCSIsCJKCompatibilityIdeographs" (byval code as integer) as integer
declare function xmlUCSIsCJKCompatibilityIdeographsSupplement cdecl alias "xmlUCSIsCJKCompatibilityIdeographsSupplement" (byval code as integer) as integer
declare function xmlUCSIsCJKRadicalsSupplement cdecl alias "xmlUCSIsCJKRadicalsSupplement" (byval code as integer) as integer
declare function xmlUCSIsCJKSymbolsandPunctuation cdecl alias "xmlUCSIsCJKSymbolsandPunctuation" (byval code as integer) as integer
declare function xmlUCSIsCJKUnifiedIdeographs cdecl alias "xmlUCSIsCJKUnifiedIdeographs" (byval code as integer) as integer
declare function xmlUCSIsCJKUnifiedIdeographsExtensionA cdecl alias "xmlUCSIsCJKUnifiedIdeographsExtensionA" (byval code as integer) as integer
declare function xmlUCSIsCJKUnifiedIdeographsExtensionB cdecl alias "xmlUCSIsCJKUnifiedIdeographsExtensionB" (byval code as integer) as integer
declare function xmlUCSIsCherokee cdecl alias "xmlUCSIsCherokee" (byval code as integer) as integer
declare function xmlUCSIsCombiningDiacriticalMarks cdecl alias "xmlUCSIsCombiningDiacriticalMarks" (byval code as integer) as integer
declare function xmlUCSIsCombiningDiacriticalMarksforSymbols cdecl alias "xmlUCSIsCombiningDiacriticalMarksforSymbols" (byval code as integer) as integer
declare function xmlUCSIsCombiningHalfMarks cdecl alias "xmlUCSIsCombiningHalfMarks" (byval code as integer) as integer
declare function xmlUCSIsCombiningMarksforSymbols cdecl alias "xmlUCSIsCombiningMarksforSymbols" (byval code as integer) as integer
declare function xmlUCSIsControlPictures cdecl alias "xmlUCSIsControlPictures" (byval code as integer) as integer
declare function xmlUCSIsCurrencySymbols cdecl alias "xmlUCSIsCurrencySymbols" (byval code as integer) as integer
declare function xmlUCSIsCypriotSyllabary cdecl alias "xmlUCSIsCypriotSyllabary" (byval code as integer) as integer
declare function xmlUCSIsCyrillic cdecl alias "xmlUCSIsCyrillic" (byval code as integer) as integer
declare function xmlUCSIsCyrillicSupplement cdecl alias "xmlUCSIsCyrillicSupplement" (byval code as integer) as integer
declare function xmlUCSIsDeseret cdecl alias "xmlUCSIsDeseret" (byval code as integer) as integer
declare function xmlUCSIsDevanagari cdecl alias "xmlUCSIsDevanagari" (byval code as integer) as integer
declare function xmlUCSIsDingbats cdecl alias "xmlUCSIsDingbats" (byval code as integer) as integer
declare function xmlUCSIsEnclosedAlphanumerics cdecl alias "xmlUCSIsEnclosedAlphanumerics" (byval code as integer) as integer
declare function xmlUCSIsEnclosedCJKLettersandMonths cdecl alias "xmlUCSIsEnclosedCJKLettersandMonths" (byval code as integer) as integer
declare function xmlUCSIsEthiopic cdecl alias "xmlUCSIsEthiopic" (byval code as integer) as integer
declare function xmlUCSIsGeneralPunctuation cdecl alias "xmlUCSIsGeneralPunctuation" (byval code as integer) as integer
declare function xmlUCSIsGeometricShapes cdecl alias "xmlUCSIsGeometricShapes" (byval code as integer) as integer
declare function xmlUCSIsGeorgian cdecl alias "xmlUCSIsGeorgian" (byval code as integer) as integer
declare function xmlUCSIsGothic cdecl alias "xmlUCSIsGothic" (byval code as integer) as integer
declare function xmlUCSIsGreek cdecl alias "xmlUCSIsGreek" (byval code as integer) as integer
declare function xmlUCSIsGreekExtended cdecl alias "xmlUCSIsGreekExtended" (byval code as integer) as integer
declare function xmlUCSIsGreekandCoptic cdecl alias "xmlUCSIsGreekandCoptic" (byval code as integer) as integer
declare function xmlUCSIsGujarati cdecl alias "xmlUCSIsGujarati" (byval code as integer) as integer
declare function xmlUCSIsGurmukhi cdecl alias "xmlUCSIsGurmukhi" (byval code as integer) as integer
declare function xmlUCSIsHalfwidthandFullwidthForms cdecl alias "xmlUCSIsHalfwidthandFullwidthForms" (byval code as integer) as integer
declare function xmlUCSIsHangulCompatibilityJamo cdecl alias "xmlUCSIsHangulCompatibilityJamo" (byval code as integer) as integer
declare function xmlUCSIsHangulJamo cdecl alias "xmlUCSIsHangulJamo" (byval code as integer) as integer
declare function xmlUCSIsHangulSyllables cdecl alias "xmlUCSIsHangulSyllables" (byval code as integer) as integer
declare function xmlUCSIsHanunoo cdecl alias "xmlUCSIsHanunoo" (byval code as integer) as integer
declare function xmlUCSIsHebrew cdecl alias "xmlUCSIsHebrew" (byval code as integer) as integer
declare function xmlUCSIsHighPrivateUseSurrogates cdecl alias "xmlUCSIsHighPrivateUseSurrogates" (byval code as integer) as integer
declare function xmlUCSIsHighSurrogates cdecl alias "xmlUCSIsHighSurrogates" (byval code as integer) as integer
declare function xmlUCSIsHiragana cdecl alias "xmlUCSIsHiragana" (byval code as integer) as integer
declare function xmlUCSIsIPAExtensions cdecl alias "xmlUCSIsIPAExtensions" (byval code as integer) as integer
declare function xmlUCSIsIdeographicDescriptionCharacters cdecl alias "xmlUCSIsIdeographicDescriptionCharacters" (byval code as integer) as integer
declare function xmlUCSIsKanbun cdecl alias "xmlUCSIsKanbun" (byval code as integer) as integer
declare function xmlUCSIsKangxiRadicals cdecl alias "xmlUCSIsKangxiRadicals" (byval code as integer) as integer
declare function xmlUCSIsKannada cdecl alias "xmlUCSIsKannada" (byval code as integer) as integer
declare function xmlUCSIsKatakana cdecl alias "xmlUCSIsKatakana" (byval code as integer) as integer
declare function xmlUCSIsKatakanaPhoneticExtensions cdecl alias "xmlUCSIsKatakanaPhoneticExtensions" (byval code as integer) as integer
declare function xmlUCSIsKhmer cdecl alias "xmlUCSIsKhmer" (byval code as integer) as integer
declare function xmlUCSIsKhmerSymbols cdecl alias "xmlUCSIsKhmerSymbols" (byval code as integer) as integer
declare function xmlUCSIsLao cdecl alias "xmlUCSIsLao" (byval code as integer) as integer
declare function xmlUCSIsLatin1Supplement cdecl alias "xmlUCSIsLatin1Supplement" (byval code as integer) as integer
declare function xmlUCSIsLatinExtendedA cdecl alias "xmlUCSIsLatinExtendedA" (byval code as integer) as integer
declare function xmlUCSIsLatinExtendedB cdecl alias "xmlUCSIsLatinExtendedB" (byval code as integer) as integer
declare function xmlUCSIsLatinExtendedAdditional cdecl alias "xmlUCSIsLatinExtendedAdditional" (byval code as integer) as integer
declare function xmlUCSIsLetterlikeSymbols cdecl alias "xmlUCSIsLetterlikeSymbols" (byval code as integer) as integer
declare function xmlUCSIsLimbu cdecl alias "xmlUCSIsLimbu" (byval code as integer) as integer
declare function xmlUCSIsLinearBIdeograms cdecl alias "xmlUCSIsLinearBIdeograms" (byval code as integer) as integer
declare function xmlUCSIsLinearBSyllabary cdecl alias "xmlUCSIsLinearBSyllabary" (byval code as integer) as integer
declare function xmlUCSIsLowSurrogates cdecl alias "xmlUCSIsLowSurrogates" (byval code as integer) as integer
declare function xmlUCSIsMalayalam cdecl alias "xmlUCSIsMalayalam" (byval code as integer) as integer
declare function xmlUCSIsMathematicalAlphanumericSymbols cdecl alias "xmlUCSIsMathematicalAlphanumericSymbols" (byval code as integer) as integer
declare function xmlUCSIsMathematicalOperators cdecl alias "xmlUCSIsMathematicalOperators" (byval code as integer) as integer
declare function xmlUCSIsMiscellaneousMathematicalSymbolsA cdecl alias "xmlUCSIsMiscellaneousMathematicalSymbolsA" (byval code as integer) as integer
declare function xmlUCSIsMiscellaneousMathematicalSymbolsB cdecl alias "xmlUCSIsMiscellaneousMathematicalSymbolsB" (byval code as integer) as integer
declare function xmlUCSIsMiscellaneousSymbols cdecl alias "xmlUCSIsMiscellaneousSymbols" (byval code as integer) as integer
declare function xmlUCSIsMiscellaneousSymbolsandArrows cdecl alias "xmlUCSIsMiscellaneousSymbolsandArrows" (byval code as integer) as integer
declare function xmlUCSIsMiscellaneousTechnical cdecl alias "xmlUCSIsMiscellaneousTechnical" (byval code as integer) as integer
declare function xmlUCSIsMongolian cdecl alias "xmlUCSIsMongolian" (byval code as integer) as integer
declare function xmlUCSIsMusicalSymbols cdecl alias "xmlUCSIsMusicalSymbols" (byval code as integer) as integer
declare function xmlUCSIsMyanmar cdecl alias "xmlUCSIsMyanmar" (byval code as integer) as integer
declare function xmlUCSIsNumberForms cdecl alias "xmlUCSIsNumberForms" (byval code as integer) as integer
declare function xmlUCSIsOgham cdecl alias "xmlUCSIsOgham" (byval code as integer) as integer
declare function xmlUCSIsOldItalic cdecl alias "xmlUCSIsOldItalic" (byval code as integer) as integer
declare function xmlUCSIsOpticalCharacterRecognition cdecl alias "xmlUCSIsOpticalCharacterRecognition" (byval code as integer) as integer
declare function xmlUCSIsOriya cdecl alias "xmlUCSIsOriya" (byval code as integer) as integer
declare function xmlUCSIsOsmanya cdecl alias "xmlUCSIsOsmanya" (byval code as integer) as integer
declare function xmlUCSIsPhoneticExtensions cdecl alias "xmlUCSIsPhoneticExtensions" (byval code as integer) as integer
declare function xmlUCSIsPrivateUse cdecl alias "xmlUCSIsPrivateUse" (byval code as integer) as integer
declare function xmlUCSIsPrivateUseArea cdecl alias "xmlUCSIsPrivateUseArea" (byval code as integer) as integer
declare function xmlUCSIsRunic cdecl alias "xmlUCSIsRunic" (byval code as integer) as integer
declare function xmlUCSIsShavian cdecl alias "xmlUCSIsShavian" (byval code as integer) as integer
declare function xmlUCSIsSinhala cdecl alias "xmlUCSIsSinhala" (byval code as integer) as integer
declare function xmlUCSIsSmallFormVariants cdecl alias "xmlUCSIsSmallFormVariants" (byval code as integer) as integer
declare function xmlUCSIsSpacingModifierLetters cdecl alias "xmlUCSIsSpacingModifierLetters" (byval code as integer) as integer
declare function xmlUCSIsSpecials cdecl alias "xmlUCSIsSpecials" (byval code as integer) as integer
declare function xmlUCSIsSuperscriptsandSubscripts cdecl alias "xmlUCSIsSuperscriptsandSubscripts" (byval code as integer) as integer
declare function xmlUCSIsSupplementalArrowsA cdecl alias "xmlUCSIsSupplementalArrowsA" (byval code as integer) as integer
declare function xmlUCSIsSupplementalArrowsB cdecl alias "xmlUCSIsSupplementalArrowsB" (byval code as integer) as integer
declare function xmlUCSIsSupplementalMathematicalOperators cdecl alias "xmlUCSIsSupplementalMathematicalOperators" (byval code as integer) as integer
declare function xmlUCSIsSupplementaryPrivateUseAreaA cdecl alias "xmlUCSIsSupplementaryPrivateUseAreaA" (byval code as integer) as integer
declare function xmlUCSIsSupplementaryPrivateUseAreaB cdecl alias "xmlUCSIsSupplementaryPrivateUseAreaB" (byval code as integer) as integer
declare function xmlUCSIsSyriac cdecl alias "xmlUCSIsSyriac" (byval code as integer) as integer
declare function xmlUCSIsTagalog cdecl alias "xmlUCSIsTagalog" (byval code as integer) as integer
declare function xmlUCSIsTagbanwa cdecl alias "xmlUCSIsTagbanwa" (byval code as integer) as integer
declare function xmlUCSIsTags cdecl alias "xmlUCSIsTags" (byval code as integer) as integer
declare function xmlUCSIsTaiLe cdecl alias "xmlUCSIsTaiLe" (byval code as integer) as integer
declare function xmlUCSIsTaiXuanJingSymbols cdecl alias "xmlUCSIsTaiXuanJingSymbols" (byval code as integer) as integer
declare function xmlUCSIsTamil cdecl alias "xmlUCSIsTamil" (byval code as integer) as integer
declare function xmlUCSIsTelugu cdecl alias "xmlUCSIsTelugu" (byval code as integer) as integer
declare function xmlUCSIsThaana cdecl alias "xmlUCSIsThaana" (byval code as integer) as integer
declare function xmlUCSIsThai cdecl alias "xmlUCSIsThai" (byval code as integer) as integer
declare function xmlUCSIsTibetan cdecl alias "xmlUCSIsTibetan" (byval code as integer) as integer
declare function xmlUCSIsUgaritic cdecl alias "xmlUCSIsUgaritic" (byval code as integer) as integer
declare function xmlUCSIsUnifiedCanadianAboriginalSyllabics cdecl alias "xmlUCSIsUnifiedCanadianAboriginalSyllabics" (byval code as integer) as integer
declare function xmlUCSIsVariationSelectors cdecl alias "xmlUCSIsVariationSelectors" (byval code as integer) as integer
declare function xmlUCSIsVariationSelectorsSupplement cdecl alias "xmlUCSIsVariationSelectorsSupplement" (byval code as integer) as integer
declare function xmlUCSIsYiRadicals cdecl alias "xmlUCSIsYiRadicals" (byval code as integer) as integer
declare function xmlUCSIsYiSyllables cdecl alias "xmlUCSIsYiSyllables" (byval code as integer) as integer
declare function xmlUCSIsYijingHexagramSymbols cdecl alias "xmlUCSIsYijingHexagramSymbols" (byval code as integer) as integer
declare function xmlUCSIsBlock cdecl alias "xmlUCSIsBlock" (byval code as integer, byval block as zstring ptr) as integer
declare function xmlUCSIsCatC cdecl alias "xmlUCSIsCatC" (byval code as integer) as integer
declare function xmlUCSIsCatCc cdecl alias "xmlUCSIsCatCc" (byval code as integer) as integer
declare function xmlUCSIsCatCf cdecl alias "xmlUCSIsCatCf" (byval code as integer) as integer
declare function xmlUCSIsCatCo cdecl alias "xmlUCSIsCatCo" (byval code as integer) as integer
declare function xmlUCSIsCatCs cdecl alias "xmlUCSIsCatCs" (byval code as integer) as integer
declare function xmlUCSIsCatL cdecl alias "xmlUCSIsCatL" (byval code as integer) as integer
declare function xmlUCSIsCatLl cdecl alias "xmlUCSIsCatLl" (byval code as integer) as integer
declare function xmlUCSIsCatLm cdecl alias "xmlUCSIsCatLm" (byval code as integer) as integer
declare function xmlUCSIsCatLo cdecl alias "xmlUCSIsCatLo" (byval code as integer) as integer
declare function xmlUCSIsCatLt cdecl alias "xmlUCSIsCatLt" (byval code as integer) as integer
declare function xmlUCSIsCatLu cdecl alias "xmlUCSIsCatLu" (byval code as integer) as integer
declare function xmlUCSIsCatM cdecl alias "xmlUCSIsCatM" (byval code as integer) as integer
declare function xmlUCSIsCatMc cdecl alias "xmlUCSIsCatMc" (byval code as integer) as integer
declare function xmlUCSIsCatMe cdecl alias "xmlUCSIsCatMe" (byval code as integer) as integer
declare function xmlUCSIsCatMn cdecl alias "xmlUCSIsCatMn" (byval code as integer) as integer
declare function xmlUCSIsCatN cdecl alias "xmlUCSIsCatN" (byval code as integer) as integer
declare function xmlUCSIsCatNd cdecl alias "xmlUCSIsCatNd" (byval code as integer) as integer
declare function xmlUCSIsCatNl cdecl alias "xmlUCSIsCatNl" (byval code as integer) as integer
declare function xmlUCSIsCatNo cdecl alias "xmlUCSIsCatNo" (byval code as integer) as integer
declare function xmlUCSIsCatP cdecl alias "xmlUCSIsCatP" (byval code as integer) as integer
declare function xmlUCSIsCatPc cdecl alias "xmlUCSIsCatPc" (byval code as integer) as integer
declare function xmlUCSIsCatPd cdecl alias "xmlUCSIsCatPd" (byval code as integer) as integer
declare function xmlUCSIsCatPe cdecl alias "xmlUCSIsCatPe" (byval code as integer) as integer
declare function xmlUCSIsCatPf cdecl alias "xmlUCSIsCatPf" (byval code as integer) as integer
declare function xmlUCSIsCatPi cdecl alias "xmlUCSIsCatPi" (byval code as integer) as integer
declare function xmlUCSIsCatPo cdecl alias "xmlUCSIsCatPo" (byval code as integer) as integer
declare function xmlUCSIsCatPs cdecl alias "xmlUCSIsCatPs" (byval code as integer) as integer
declare function xmlUCSIsCatS cdecl alias "xmlUCSIsCatS" (byval code as integer) as integer
declare function xmlUCSIsCatSc cdecl alias "xmlUCSIsCatSc" (byval code as integer) as integer
declare function xmlUCSIsCatSk cdecl alias "xmlUCSIsCatSk" (byval code as integer) as integer
declare function xmlUCSIsCatSm cdecl alias "xmlUCSIsCatSm" (byval code as integer) as integer
declare function xmlUCSIsCatSo cdecl alias "xmlUCSIsCatSo" (byval code as integer) as integer
declare function xmlUCSIsCatZ cdecl alias "xmlUCSIsCatZ" (byval code as integer) as integer
declare function xmlUCSIsCatZl cdecl alias "xmlUCSIsCatZl" (byval code as integer) as integer
declare function xmlUCSIsCatZp cdecl alias "xmlUCSIsCatZp" (byval code as integer) as integer
declare function xmlUCSIsCatZs cdecl alias "xmlUCSIsCatZs" (byval code as integer) as integer
declare function xmlUCSIsCat cdecl alias "xmlUCSIsCat" (byval code as integer, byval cat as zstring ptr) as integer

#endif
