' ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
'< Signal handler generated by utility                       GladeToBac V3.0.1 >
'< Signal-Modul erzeugt von                                                    >
'< Generated at / Generierung am                             2011-09-15, 17:37 >
' -----------------------------------------------------------------------------
'< Main/Haupt Program name: FB_Calc.bas                                        >
'<  Email:  Thomas{ dot ]Freiherr[ AT ]gmx[ dot }net                           >
'<    WWW:  www.freebasic-portal.de                                            >
' -----------------------------------------------------------------------------
'< callback SUB/FUNCTION                                          insert code! >
'< Ereignis Unterprogramm/Funktion                        Quelltext einfuegen! >
' vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
SUB on_operation_clicked CDECL ALIAS "on_operation_clicked" ( _
  BYVAL button AS GtkButton PTR, _
  BYVAL user_data AS gpointer) EXPORT

WITH GUI
SELECT CASE G_OBJECT(button)
CASE .but_plus : Calc(Op.Plus)
CASE .but_minus : Calc(Op.Minus)
CASE .but_mult : Calc(Op.Multiplication)
CASE .but_div : Calc(Op.Division)
CASE .but_clear : Calc(Op.Clear)
CASE .but_gleich : Calc(Op.Result)
END SELECT
END WITH

END SUB
