#!/bin/sh

# The 32bit X development libraries are not to be found in the amd64 Debian
# repositories, so we depend on getlibs and use it to download the 32bit
# versions, so it's possible to compile and run FreeBASIC graphics programs.
echo "Running getlibs to install i386 versions of libx11-dev, libxext-dev,"
echo "libxpm-dev, libxrandr-dev, and libxrender-dev..."
yes | getlibs --verbose -p \
        libx11-dev libxext-dev libxpm-dev libxrandr-dev libxrender-dev

exit 0
