extern should_not_be_allocated_by_local_i1 as integer
extern should_not_be_allocated_by_local_i2 as integer
extern should_not_be_allocated_by_local_i3 as integer
extern should_not_be_allocated_by_local_i4 as integer
extern should_not_be_allocated_by_local_i5 as integer
extern should_not_be_allocated_by_local_i6 as integer
extern should_not_be_allocated_by_local_i7 as integer
extern should_not_be_allocated_by_local_i8 as integer
