''
''
'' gtk -- header translated with help of SWIG FB wrapper
''
'' NOTICE: This file is part of the FreeBASIC Compiler package and can't
''         be included in other distributions without authorization.
''
''
#ifndef __gtk_bi__
#define __gtk_bi__

#ifdef __FB_WIN32__
# inclib "gtk-win32-2.0"
# pragma push(msbitfields)
#elseif defined(__FB_LINUX__)
# inclib "gtk-x11-2.0"
#else
# error Platform not supported!
#endif

extern "c"

#include once "gdk.bi"
#include once "gtk/gtkaboutdialog.bi"
#include once "gtk/gtkaccelgroup.bi"
#include once "gtk/gtkaccellabel.bi"
#include once "gtk/gtkaccelmap.bi"
#include once "gtk/gtkaccessible.bi"
#include once "gtk/gtkaction.bi"
#include once "gtk/gtkactiongroup.bi"
#include once "gtk/gtkadjustment.bi"
#include once "gtk/gtkalignment.bi"
#include once "gtk/gtkarrow.bi"
#include once "gtk/gtkaspectframe.bi"
#include once "gtk/gtkbbox.bi"
#include once "gtk/gtkbin.bi"
#include once "gtk/gtkbindings.bi"
#include once "gtk/gtkbox.bi"
#include once "gtk/gtkbutton.bi"
#include once "gtk/gtkcalendar.bi"
#include once "gtk/gtkcelllayout.bi"
#include once "gtk/gtkcellrenderer.bi"
#include once "gtk/gtkcellrenderercombo.bi"
#include once "gtk/gtkcellrendererpixbuf.bi"
#include once "gtk/gtkcellrendererprogress.bi"
#include once "gtk/gtkcellrenderertext.bi"
#include once "gtk/gtkcellrenderertoggle.bi"
#include once "gtk/gtkcellview.bi"
#include once "gtk/gtkcheckbutton.bi"
#include once "gtk/gtkcheckmenuitem.bi"
#include once "gtk/gtkclipboard.bi"
#include once "gtk/gtkclist.bi"
#include once "gtk/gtkcolorbutton.bi"
#include once "gtk/gtkcolorsel.bi"
#include once "gtk/gtkcolorseldialog.bi"
#include once "gtk/gtkcombo.bi"
#include once "gtk/gtkcombobox.bi"
#include once "gtk/gtkcomboboxentry.bi"
#include once "gtk/gtkcontainer.bi"
#include once "gtk/gtkctree.bi"
#include once "gtk/gtkcurve.bi"
#include once "gtk/gtkdialog.bi"
#include once "gtk/gtkdnd.bi"
#include once "gtk/gtkdrawingarea.bi"
#include once "gtk/gtkeditable.bi"
#include once "gtk/gtkentry.bi"
#include once "gtk/gtkentrycompletion.bi"
#include once "gtk/gtkenums.bi"
#include once "gtk/gtkeventbox.bi"
#include once "gtk/gtkexpander.bi"
#include once "gtk/gtkfilesel.bi"
#include once "gtk/gtkfixed.bi"
#include once "gtk/gtkfilechooserbutton.bi"
#include once "gtk/gtkfilechooserdialog.bi"
#include once "gtk/gtkfilechooserwidget.bi"
#include once "gtk/gtkfontbutton.bi"
#include once "gtk/gtkfontsel.bi"
#include once "gtk/gtkframe.bi"
#include once "gtk/gtkgamma.bi"
#include once "gtk/gtkgc.bi"
#include once "gtk/gtkhandlebox.bi"
#include once "gtk/gtkhbbox.bi"
#include once "gtk/gtkhbox.bi"
#include once "gtk/gtkhpaned.bi"
#include once "gtk/gtkhruler.bi"
#include once "gtk/gtkhscale.bi"
#include once "gtk/gtkhscrollbar.bi"
#include once "gtk/gtkhseparator.bi"
#include once "gtk/gtkiconfactory.bi"
#include once "gtk/gtkicontheme.bi"
#include once "gtk/gtkiconview.bi"
#include once "gtk/gtkimage.bi"
#include once "gtk/gtkimagemenuitem.bi"
#include once "gtk/gtkimcontext.bi"
#include once "gtk/gtkimcontextsimple.bi"
#include once "gtk/gtkimmulticontext.bi"
#include once "gtk/gtkinputdialog.bi"
#include once "gtk/gtkinvisible.bi"
#include once "gtk/gtkitem.bi"
#include once "gtk/gtkitemfactory.bi"
#include once "gtk/gtklabel.bi"
#include once "gtk/gtklayout.bi"
#include once "gtk/gtklist.bi"
#include once "gtk/gtklistitem.bi"
#include once "gtk/gtkliststore.bi"
#include once "gtk/gtkmain.bi"
#include once "gtk/gtkmenu.bi"
#include once "gtk/gtkmenubar.bi"
#include once "gtk/gtkmenuitem.bi"
#include once "gtk/gtkmenushell.bi"
#include once "gtk/gtkmenutoolbutton.bi"
#include once "gtk/gtkmessagedialog.bi"
#include once "gtk/gtkmisc.bi"
#include once "gtk/gtkmodules.bi"
#include once "gtk/gtknotebook.bi"
#include once "gtk/gtkobject.bi"
#include once "gtk/gtkoldeditable.bi"
#include once "gtk/gtkoptionmenu.bi"
#include once "gtk/gtkpaned.bi"
#include once "gtk/gtkpixmap.bi"
#include once "gtk/gtkplug.bi"
#include once "gtk/gtkpreview.bi"
#include once "gtk/gtkprogress.bi"
#include once "gtk/gtkprogressbar.bi"
#include once "gtk/gtkradioaction.bi"
#include once "gtk/gtkradiobutton.bi"
#include once "gtk/gtkradiomenuitem.bi"
#include once "gtk/gtkradiotoolbutton.bi"
#include once "gtk/gtkrange.bi"
#include once "gtk/gtkrc.bi"
#include once "gtk/gtkruler.bi"
#include once "gtk/gtkscale.bi"
#include once "gtk/gtkscrollbar.bi"
#include once "gtk/gtkscrolledwindow.bi"
#include once "gtk/gtkselection.bi"
#include once "gtk/gtkseparator.bi"
#include once "gtk/gtkseparatormenuitem.bi"
#include once "gtk/gtkseparatortoolitem.bi"
#include once "gtk/gtksettings.bi"
#include once "gtk/gtksignal.bi"
#include once "gtk/gtksizegroup.bi"
#include once "gtk/gtksocket.bi"
#include once "gtk/gtkspinbutton.bi"
#include once "gtk/gtkstatusbar.bi"
#include once "gtk/gtkstock.bi"
#include once "gtk/gtkstyle.bi"
#include once "gtk/gtktable.bi"
#include once "gtk/gtktearoffmenuitem.bi"
#include once "gtk/gtktext.bi"
#include once "gtk/gtktextbuffer.bi"
#include once "gtk/gtktextview.bi"
#include once "gtk/gtktipsquery.bi"
#include once "gtk/gtktoggleaction.bi"
#include once "gtk/gtktogglebutton.bi"
#include once "gtk/gtktoggletoolbutton.bi"
#include once "gtk/gtktoolbar.bi"
#include once "gtk/gtktoolbar.bi"
#include once "gtk/gtktoolbutton.bi"
#include once "gtk/gtktoolitem.bi"
#include once "gtk/gtktooltips.bi"
#include once "gtk/gtktree.bi"
#include once "gtk/gtktreednd.bi"
#include once "gtk/gtktreeitem.bi"
#include once "gtk/gtktreemodel.bi"
#include once "gtk/gtktreemodelfilter.bi"
#include once "gtk/gtktreemodelsort.bi"
#include once "gtk/gtktreeselection.bi"
#include once "gtk/gtktreestore.bi"
#include once "gtk/gtktreeview.bi"
#include once "gtk/gtktreeviewcolumn.bi"
#include once "gtk/gtktypeutils.bi"
#include once "gtk/gtkuimanager.bi"
#include once "gtk/gtkvbbox.bi"
#include once "gtk/gtkvbox.bi"
#include once "gtk/gtkversion.bi"
#include once "gtk/gtkviewport.bi"
#include once "gtk/gtkvpaned.bi"
#include once "gtk/gtkvruler.bi"
#include once "gtk/gtkvscale.bi"
#include once "gtk/gtkvscrollbar.bi"
#include once "gtk/gtkvseparator.bi"
#include once "gtk/gtkwidget.bi"
#include once "gtk/gtkwindow.bi"

end extern

#ifdef __FB_WIN32__
# pragma pop(msbitfields)
#endif

#endif
