

#ifndef __FB_COLOR_H__
#define __FB_COLOR_H__

#ifdef WIN32


#define FB_COLOR_BLACK 		(0)
#define FB_COLOR_BLUE   	(FOREGROUND_BLUE)
#define FB_COLOR_GREEN     	(FOREGROUND_GREEN)
#define FB_COLOR_CYAN   	(FOREGROUND_GREEN|FOREGROUND_BLUE)
#define FB_COLOR_RED       	(FOREGROUND_RED)
#define FB_COLOR_MAGENTA   	(FOREGROUND_RED|FOREGROUND_BLUE)
#define FB_COLOR_BROWN     	(FOREGROUND_RED|FOREGROUND_GREEN)
#define FB_COLOR_WHITE     	(FOREGROUND_RED|FOREGROUND_GREEN|FOREGROUND_BLUE)
#define FB_COLOR_GREY   	(FOREGROUND_RED|FOREGROUND_GREEN|FOREGROUND_BLUE)
#define FB_COLOR_LBLUE     	(FOREGROUND_BLUE|FOREGROUND_INTENSITY)
#define FB_COLOR_LGREEN    	(FOREGROUND_GREEN|FOREGROUND_INTENSITY) 
#define FB_COLOR_LCYAN     	(FOREGROUND_GREEN|FOREGROUND_BLUE|FOREGROUND_INTENSITY)
#define FB_COLOR_LRED   	(FOREGROUND_RED|FOREGROUND_INTENSITY)
#define FB_COLOR_LMAGENTA  	(FOREGROUND_RED|FOREGROUND_BLUE|FOREGROUND_INTENSITY)
#define FB_COLOR_YELLOW    	(FOREGROUND_RED|FOREGROUND_GREEN|FOREGROUND_INTENSITY)
#define FB_COLOR_BWHITE    	(FOREGROUND_RED|FOREGROUND_GREEN|FOREGROUND_BLUE|FOREGROUND_INTENSITY)

#endif /* WIN32 */

#endif /* __FB_COLOR_H__ */
