#macro t ? ( n, stmt... )
#print stmt
stmt
#if( n = 0 )
#print OK
#endif
#endmacro

dim as string a, b










'' -------------------
t( 1, line input       )
t( 1, line input  ;    )
t( 1, line input    '' )
t( 1, line input  ; '' )
t( 1, line input   ,     )
t( 1, line input  ;,     )
t( 1, line input   ,  '' )
t( 1, line input  ;,  '' )
t( 1, line input   ,  1     )
t( 1, line input  ;,  1     )
t( 1, line input   ,  1  '' )
t( 1, line input  ;,  1  '' )
t( 1, line input   ,  1 ,     )
t( 1, line input  ;,  1 ,     )
t( 1, line input   ,  1 ,  '' )
t( 1, line input  ;,  1 ,  '' )
t( 1, line input   ,  1 ;     )
t( 1, line input  ;,  1 ;     )
t( 1, line input   ,  1 ;  '' )
t( 1, line input  ;,  1 ;  '' )
t( 1, line input   ,  1 ,,    )
t( 1, line input  ;,  1 ,,    )
t( 1, line input   ,  1 ,, '' )
t( 1, line input  ;,  1 ,, '' )
t( 1, line input   ,  1 ,;    )
t( 1, line input  ;,  1 ,;    )
t( 1, line input   ,  1 ,; '' )
t( 1, line input  ;,  1 ,; '' )
t( 1, line input   ,  1 ;,    )
t( 1, line input  ;,  1 ;,    )
t( 1, line input   ,  1 ;, '' )
t( 1, line input  ;,  1 ;, '' )
t( 1, line input   ,  1 ;;    )
t( 1, line input  ;,  1 ;;    )
t( 1, line input   ,  1 ;; '' )
t( 1, line input  ;,  1 ;; '' )
t( 0, line input   ,  a     )
t( 0, line input  ;,  a     )
t( 0, line input   ,  a  '' )
t( 0, line input  ;,  a  '' )
t( 1, line input   ,  a ,     )
t( 1, line input  ;,  a ,     )
t( 1, line input   ,  a ,  '' )
t( 1, line input  ;,  a ,  '' )
t( 1, line input   ,  a ;     )
t( 1, line input  ;,  a ;     )
t( 1, line input   ,  a ;  '' )
t( 1, line input  ;,  a ;  '' )
t( 1, line input   ,  a ,,    )
t( 1, line input  ;,  a ,,    )
t( 1, line input   ,  a ,, '' )
t( 1, line input  ;,  a ,, '' )
t( 1, line input   ,  a ,;    )
t( 1, line input  ;,  a ,;    )
t( 1, line input   ,  a ,; '' )
t( 1, line input  ;,  a ,; '' )
t( 1, line input   ,  a ;,    )
t( 1, line input  ;,  a ;,    )
t( 1, line input   ,  a ;, '' )
t( 1, line input  ;,  a ;, '' )
t( 1, line input   ,  a ;;    )
t( 1, line input  ;,  a ;;    )
t( 1, line input   ,  a ;; '' )
t( 1, line input  ;,  a ;; '' )
t( 1, line input   , "T"    )
t( 1, line input  ;, "T"    )
t( 1, line input   , "T" '' )
t( 1, line input  ;, "T" '' )
t( 1, line input   , "T",     )
t( 1, line input  ;, "T",     )
t( 1, line input   , "T",  '' )
t( 1, line input  ;, "T",  '' )
t( 1, line input   , "T";     )
t( 1, line input  ;, "T";     )
t( 1, line input   , "T";  '' )
t( 1, line input  ;, "T";  '' )
t( 1, line input   , "T",,    )
t( 1, line input  ;, "T",,    )
t( 1, line input   , "T",, '' )
t( 1, line input  ;, "T",, '' )
t( 1, line input   , "T",;    )
t( 1, line input  ;, "T",;    )
t( 1, line input   , "T",; '' )
t( 1, line input  ;, "T",; '' )
t( 1, line input   , "T";,    )
t( 1, line input  ;, "T";,    )
t( 1, line input   , "T";, '' )
t( 1, line input  ;, "T";, '' )
t( 1, line input   , "T";;    )
t( 1, line input  ;, "T";;    )
t( 1, line input   , "T";; '' )
t( 1, line input  ;, "T";; '' )
t( 0, line input   ,  b     )
t( 0, line input  ;,  b     )
t( 0, line input   ,  b  '' )
t( 0, line input  ;,  b  '' )
t( 1, line input   ,  b ,     )
t( 1, line input  ;,  b ,     )
t( 1, line input   ,  b ,  '' )
t( 1, line input  ;,  b ,  '' )
t( 1, line input   ,  b ;     )
t( 1, line input  ;,  b ;     )
t( 1, line input   ,  b ;  '' )
t( 1, line input  ;,  b ;  '' )
t( 1, line input   ,  b ,,    )
t( 1, line input  ;,  b ,,    )
t( 1, line input   ,  b ,, '' )
t( 1, line input  ;,  b ,, '' )
t( 1, line input   ,  b ,;    )
t( 1, line input  ;,  b ,;    )
t( 1, line input   ,  b ,; '' )
t( 1, line input  ;,  b ,; '' )
t( 1, line input   ,  b ;,    )
t( 1, line input  ;,  b ;,    )
t( 1, line input   ,  b ;, '' )
t( 1, line input  ;,  b ;, '' )
t( 1, line input   ,  b ;;    )
t( 1, line input  ;,  b ;;    )
t( 1, line input   ,  b ;; '' )
t( 1, line input  ;,  b ;; '' )
t( 1, line input   ;     )
t( 1, line input  ;;     )
t( 1, line input   ;  '' )
t( 1, line input  ;;  '' )
t( 1, line input   ;  1     )
t( 1, line input  ;;  1     )
t( 1, line input   ;  1  '' )
t( 1, line input  ;;  1  '' )
t( 1, line input   ;  1 ,     )
t( 1, line input  ;;  1 ,     )
t( 1, line input   ;  1 ,  '' )
t( 1, line input  ;;  1 ,  '' )
t( 1, line input   ;  1 ;     )
t( 1, line input  ;;  1 ;     )
t( 1, line input   ;  1 ;  '' )
t( 1, line input  ;;  1 ;  '' )
t( 1, line input   ;  1 ,,    )
t( 1, line input  ;;  1 ,,    )
t( 1, line input   ;  1 ,, '' )
t( 1, line input  ;;  1 ,, '' )
t( 1, line input   ;  1 ,;    )
t( 1, line input  ;;  1 ,;    )
t( 1, line input   ;  1 ,; '' )
t( 1, line input  ;;  1 ,; '' )
t( 1, line input   ;  1 ;,    )
t( 1, line input  ;;  1 ;,    )
t( 1, line input   ;  1 ;, '' )
t( 1, line input  ;;  1 ;, '' )
t( 1, line input   ;  1 ;;    )
t( 1, line input  ;;  1 ;;    )
t( 1, line input   ;  1 ;; '' )
t( 1, line input  ;;  1 ;; '' )
t( 0, line input   ;  a     )
t( 0, line input  ;;  a     )
t( 0, line input   ;  a  '' )
t( 0, line input  ;;  a  '' )
t( 1, line input   ;  a ,     )
t( 1, line input  ;;  a ,     )
t( 1, line input   ;  a ,  '' )
t( 1, line input  ;;  a ,  '' )
t( 1, line input   ;  a ;     )
t( 1, line input  ;;  a ;     )
t( 1, line input   ;  a ;  '' )
t( 1, line input  ;;  a ;  '' )
t( 1, line input   ;  a ,,    )
t( 1, line input  ;;  a ,,    )
t( 1, line input   ;  a ,, '' )
t( 1, line input  ;;  a ,, '' )
t( 1, line input   ;  a ,;    )
t( 1, line input  ;;  a ,;    )
t( 1, line input   ;  a ,; '' )
t( 1, line input  ;;  a ,; '' )
t( 1, line input   ;  a ;,    )
t( 1, line input  ;;  a ;,    )
t( 1, line input   ;  a ;, '' )
t( 1, line input  ;;  a ;, '' )
t( 1, line input   ;  a ;;    )
t( 1, line input  ;;  a ;;    )
t( 1, line input   ;  a ;; '' )
t( 1, line input  ;;  a ;; '' )
t( 1, line input   ; "T"    )
t( 1, line input  ;; "T"    )
t( 1, line input   ; "T" '' )
t( 1, line input  ;; "T" '' )
t( 1, line input   ; "T",     )
t( 1, line input  ;; "T",     )
t( 1, line input   ; "T",  '' )
t( 1, line input  ;; "T",  '' )
t( 1, line input   ; "T";     )
t( 1, line input  ;; "T";     )
t( 1, line input   ; "T";  '' )
t( 1, line input  ;; "T";  '' )
t( 1, line input   ; "T",,    )
t( 1, line input  ;; "T",,    )
t( 1, line input   ; "T",, '' )
t( 1, line input  ;; "T",, '' )
t( 1, line input   ; "T",;    )
t( 1, line input  ;; "T",;    )
t( 1, line input   ; "T",; '' )
t( 1, line input  ;; "T",; '' )
t( 1, line input   ; "T";,    )
t( 1, line input  ;; "T";,    )
t( 1, line input   ; "T";, '' )
t( 1, line input  ;; "T";, '' )
t( 1, line input   ; "T";;    )
t( 1, line input  ;; "T";;    )
t( 1, line input   ; "T";; '' )
t( 1, line input  ;; "T";; '' )
t( 0, line input   ;  b     )
t( 0, line input  ;;  b     )
t( 0, line input   ;  b  '' )
t( 0, line input  ;;  b  '' )
t( 1, line input   ;  b ,     )
t( 1, line input  ;;  b ,     )
t( 1, line input   ;  b ,  '' )
t( 1, line input  ;;  b ,  '' )
t( 1, line input   ;  b ;     )
t( 1, line input  ;;  b ;     )
t( 1, line input   ;  b ;  '' )
t( 1, line input  ;;  b ;  '' )
t( 1, line input   ;  b ,,    )
t( 1, line input  ;;  b ,,    )
t( 1, line input   ;  b ,, '' )
t( 1, line input  ;;  b ,, '' )
t( 1, line input   ;  b ,;    )
t( 1, line input  ;;  b ,;    )
t( 1, line input   ;  b ,; '' )
t( 1, line input  ;;  b ,; '' )
t( 1, line input   ;  b ;,    )
t( 1, line input  ;;  b ;,    )
t( 1, line input   ;  b ;, '' )
t( 1, line input  ;;  b ;, '' )
t( 1, line input   ;  b ;;    )
t( 1, line input  ;;  b ;;    )
t( 1, line input   ;  b ;; '' )
t( 1, line input  ;;  b ;; '' )
t( 1, line input   ,,    )
t( 1, line input  ;,,    )
t( 1, line input   ,, '' )
t( 1, line input  ;,, '' )
t( 1, line input   ,, 1     )
t( 1, line input  ;,, 1     )
t( 1, line input   ,, 1  '' )
t( 1, line input  ;,, 1  '' )
t( 1, line input   ,, 1 ,     )
t( 1, line input  ;,, 1 ,     )
t( 1, line input   ,, 1 ,  '' )
t( 1, line input  ;,, 1 ,  '' )
t( 1, line input   ,, 1 ;     )
t( 1, line input  ;,, 1 ;     )
t( 1, line input   ,, 1 ;  '' )
t( 1, line input  ;,, 1 ;  '' )
t( 1, line input   ,, 1 ,,    )
t( 1, line input  ;,, 1 ,,    )
t( 1, line input   ,, 1 ,, '' )
t( 1, line input  ;,, 1 ,, '' )
t( 1, line input   ,, 1 ,;    )
t( 1, line input  ;,, 1 ,;    )
t( 1, line input   ,, 1 ,; '' )
t( 1, line input  ;,, 1 ,; '' )
t( 1, line input   ,, 1 ;,    )
t( 1, line input  ;,, 1 ;,    )
t( 1, line input   ,, 1 ;, '' )
t( 1, line input  ;,, 1 ;, '' )
t( 1, line input   ,, 1 ;;    )
t( 1, line input  ;,, 1 ;;    )
t( 1, line input   ,, 1 ;; '' )
t( 1, line input  ;,, 1 ;; '' )
t( 1, line input   ,, a     )
t( 1, line input  ;,, a     )
t( 1, line input   ,, a  '' )
t( 1, line input  ;,, a  '' )
t( 1, line input   ,, a ,     )
t( 1, line input  ;,, a ,     )
t( 1, line input   ,, a ,  '' )
t( 1, line input  ;,, a ,  '' )
t( 1, line input   ,, a ;     )
t( 1, line input  ;,, a ;     )
t( 1, line input   ,, a ;  '' )
t( 1, line input  ;,, a ;  '' )
t( 1, line input   ,, a ,,    )
t( 1, line input  ;,, a ,,    )
t( 1, line input   ,, a ,, '' )
t( 1, line input  ;,, a ,, '' )
t( 1, line input   ,, a ,;    )
t( 1, line input  ;,, a ,;    )
t( 1, line input   ,, a ,; '' )
t( 1, line input  ;,, a ,; '' )
t( 1, line input   ,, a ;,    )
t( 1, line input  ;,, a ;,    )
t( 1, line input   ,, a ;, '' )
t( 1, line input  ;,, a ;, '' )
t( 1, line input   ,, a ;;    )
t( 1, line input  ;,, a ;;    )
t( 1, line input   ,, a ;; '' )
t( 1, line input  ;,, a ;; '' )
t( 1, line input   ,,"T"    )
t( 1, line input  ;,,"T"    )
t( 1, line input   ,,"T" '' )
t( 1, line input  ;,,"T" '' )
t( 1, line input   ,,"T",     )
t( 1, line input  ;,,"T",     )
t( 1, line input   ,,"T",  '' )
t( 1, line input  ;,,"T",  '' )
t( 1, line input   ,,"T";     )
t( 1, line input  ;,,"T";     )
t( 1, line input   ,,"T";  '' )
t( 1, line input  ;,,"T";  '' )
t( 1, line input   ,,"T",,    )
t( 1, line input  ;,,"T",,    )
t( 1, line input   ,,"T",, '' )
t( 1, line input  ;,,"T",, '' )
t( 1, line input   ,,"T",;    )
t( 1, line input  ;,,"T",;    )
t( 1, line input   ,,"T",; '' )
t( 1, line input  ;,,"T",; '' )
t( 1, line input   ,,"T";,    )
t( 1, line input  ;,,"T";,    )
t( 1, line input   ,,"T";, '' )
t( 1, line input  ;,,"T";, '' )
t( 1, line input   ,,"T";;    )
t( 1, line input  ;,,"T";;    )
t( 1, line input   ,,"T";; '' )
t( 1, line input  ;,,"T";; '' )
t( 1, line input   ,, b     )
t( 1, line input  ;,, b     )
t( 1, line input   ,, b  '' )
t( 1, line input  ;,, b  '' )
t( 1, line input   ,, b ,     )
t( 1, line input  ;,, b ,     )
t( 1, line input   ,, b ,  '' )
t( 1, line input  ;,, b ,  '' )
t( 1, line input   ,, b ;     )
t( 1, line input  ;,, b ;     )
t( 1, line input   ,, b ;  '' )
t( 1, line input  ;,, b ;  '' )
t( 1, line input   ,, b ,,    )
t( 1, line input  ;,, b ,,    )
t( 1, line input   ,, b ,, '' )
t( 1, line input  ;,, b ,, '' )
t( 1, line input   ,, b ,;    )
t( 1, line input  ;,, b ,;    )
t( 1, line input   ,, b ,; '' )
t( 1, line input  ;,, b ,; '' )
t( 1, line input   ,, b ;,    )
t( 1, line input  ;,, b ;,    )
t( 1, line input   ,, b ;, '' )
t( 1, line input  ;,, b ;, '' )
t( 1, line input   ,, b ;;    )
t( 1, line input  ;,, b ;;    )
t( 1, line input   ,, b ;; '' )
t( 1, line input  ;,, b ;; '' )
t( 1, line input   ,;    )
t( 1, line input  ;,;    )
t( 1, line input   ,; '' )
t( 1, line input  ;,; '' )
t( 1, line input   ,; 1     )
t( 1, line input  ;,; 1     )
t( 1, line input   ,; 1  '' )
t( 1, line input  ;,; 1  '' )
t( 1, line input   ,; 1 ,     )
t( 1, line input  ;,; 1 ,     )
t( 1, line input   ,; 1 ,  '' )
t( 1, line input  ;,; 1 ,  '' )
t( 1, line input   ,; 1 ;     )
t( 1, line input  ;,; 1 ;     )
t( 1, line input   ,; 1 ;  '' )
t( 1, line input  ;,; 1 ;  '' )
t( 1, line input   ,; 1 ,,    )
t( 1, line input  ;,; 1 ,,    )
t( 1, line input   ,; 1 ,, '' )
t( 1, line input  ;,; 1 ,, '' )
t( 1, line input   ,; 1 ,;    )
t( 1, line input  ;,; 1 ,;    )
t( 1, line input   ,; 1 ,; '' )
t( 1, line input  ;,; 1 ,; '' )
t( 1, line input   ,; 1 ;,    )
t( 1, line input  ;,; 1 ;,    )
t( 1, line input   ,; 1 ;, '' )
t( 1, line input  ;,; 1 ;, '' )
t( 1, line input   ,; 1 ;;    )
t( 1, line input  ;,; 1 ;;    )
t( 1, line input   ,; 1 ;; '' )
t( 1, line input  ;,; 1 ;; '' )
t( 1, line input   ,; a     )
t( 1, line input  ;,; a     )
t( 1, line input   ,; a  '' )
t( 1, line input  ;,; a  '' )
t( 1, line input   ,; a ,     )
t( 1, line input  ;,; a ,     )
t( 1, line input   ,; a ,  '' )
t( 1, line input  ;,; a ,  '' )
t( 1, line input   ,; a ;     )
t( 1, line input  ;,; a ;     )
t( 1, line input   ,; a ;  '' )
t( 1, line input  ;,; a ;  '' )
t( 1, line input   ,; a ,,    )
t( 1, line input  ;,; a ,,    )
t( 1, line input   ,; a ,, '' )
t( 1, line input  ;,; a ,, '' )
t( 1, line input   ,; a ,;    )
t( 1, line input  ;,; a ,;    )
t( 1, line input   ,; a ,; '' )
t( 1, line input  ;,; a ,; '' )
t( 1, line input   ,; a ;,    )
t( 1, line input  ;,; a ;,    )
t( 1, line input   ,; a ;, '' )
t( 1, line input  ;,; a ;, '' )
t( 1, line input   ,; a ;;    )
t( 1, line input  ;,; a ;;    )
t( 1, line input   ,; a ;; '' )
t( 1, line input  ;,; a ;; '' )
t( 1, line input   ,;"T"    )
t( 1, line input  ;,;"T"    )
t( 1, line input   ,;"T" '' )
t( 1, line input  ;,;"T" '' )
t( 1, line input   ,;"T",     )
t( 1, line input  ;,;"T",     )
t( 1, line input   ,;"T",  '' )
t( 1, line input  ;,;"T",  '' )
t( 1, line input   ,;"T";     )
t( 1, line input  ;,;"T";     )
t( 1, line input   ,;"T";  '' )
t( 1, line input  ;,;"T";  '' )
t( 1, line input   ,;"T",,    )
t( 1, line input  ;,;"T",,    )
t( 1, line input   ,;"T",, '' )
t( 1, line input  ;,;"T",, '' )
t( 1, line input   ,;"T",;    )
t( 1, line input  ;,;"T",;    )
t( 1, line input   ,;"T",; '' )
t( 1, line input  ;,;"T",; '' )
t( 1, line input   ,;"T";,    )
t( 1, line input  ;,;"T";,    )
t( 1, line input   ,;"T";, '' )
t( 1, line input  ;,;"T";, '' )
t( 1, line input   ,;"T";;    )
t( 1, line input  ;,;"T";;    )
t( 1, line input   ,;"T";; '' )
t( 1, line input  ;,;"T";; '' )
t( 1, line input   ,; b     )
t( 1, line input  ;,; b     )
t( 1, line input   ,; b  '' )
t( 1, line input  ;,; b  '' )
t( 1, line input   ,; b ,     )
t( 1, line input  ;,; b ,     )
t( 1, line input   ,; b ,  '' )
t( 1, line input  ;,; b ,  '' )
t( 1, line input   ,; b ;     )
t( 1, line input  ;,; b ;     )
t( 1, line input   ,; b ;  '' )
t( 1, line input  ;,; b ;  '' )
t( 1, line input   ,; b ,,    )
t( 1, line input  ;,; b ,,    )
t( 1, line input   ,; b ,, '' )
t( 1, line input  ;,; b ,, '' )
t( 1, line input   ,; b ,;    )
t( 1, line input  ;,; b ,;    )
t( 1, line input   ,; b ,; '' )
t( 1, line input  ;,; b ,; '' )
t( 1, line input   ,; b ;,    )
t( 1, line input  ;,; b ;,    )
t( 1, line input   ,; b ;, '' )
t( 1, line input  ;,; b ;, '' )
t( 1, line input   ,; b ;;    )
t( 1, line input  ;,; b ;;    )
t( 1, line input   ,; b ;; '' )
t( 1, line input  ;,; b ;; '' )
t( 1, line input   ;,    )
t( 1, line input  ;;,    )
t( 1, line input   ;, '' )
t( 1, line input  ;;, '' )
t( 1, line input   ;, 1     )
t( 1, line input  ;;, 1     )
t( 1, line input   ;, 1  '' )
t( 1, line input  ;;, 1  '' )
t( 1, line input   ;, 1 ,     )
t( 1, line input  ;;, 1 ,     )
t( 1, line input   ;, 1 ,  '' )
t( 1, line input  ;;, 1 ,  '' )
t( 1, line input   ;, 1 ;     )
t( 1, line input  ;;, 1 ;     )
t( 1, line input   ;, 1 ;  '' )
t( 1, line input  ;;, 1 ;  '' )
t( 1, line input   ;, 1 ,,    )
t( 1, line input  ;;, 1 ,,    )
t( 1, line input   ;, 1 ,, '' )
t( 1, line input  ;;, 1 ,, '' )
t( 1, line input   ;, 1 ,;    )
t( 1, line input  ;;, 1 ,;    )
t( 1, line input   ;, 1 ,; '' )
t( 1, line input  ;;, 1 ,; '' )
t( 1, line input   ;, 1 ;,    )
t( 1, line input  ;;, 1 ;,    )
t( 1, line input   ;, 1 ;, '' )
t( 1, line input  ;;, 1 ;, '' )
t( 1, line input   ;, 1 ;;    )
t( 1, line input  ;;, 1 ;;    )
t( 1, line input   ;, 1 ;; '' )
t( 1, line input  ;;, 1 ;; '' )
t( 0, line input   ;, a     )
t( 1, line input  ;;, a     )
t( 0, line input   ;, a  '' )
t( 1, line input  ;;, a  '' )
t( 1, line input   ;, a ,     )
t( 1, line input  ;;, a ,     )
t( 1, line input   ;, a ,  '' )
t( 1, line input  ;;, a ,  '' )
t( 1, line input   ;, a ;     )
t( 1, line input  ;;, a ;     )
t( 1, line input   ;, a ;  '' )
t( 1, line input  ;;, a ;  '' )
t( 1, line input   ;, a ,,    )
t( 1, line input  ;;, a ,,    )
t( 1, line input   ;, a ,, '' )
t( 1, line input  ;;, a ,, '' )
t( 1, line input   ;, a ,;    )
t( 1, line input  ;;, a ,;    )
t( 1, line input   ;, a ,; '' )
t( 1, line input  ;;, a ,; '' )
t( 1, line input   ;, a ;,    )
t( 1, line input  ;;, a ;,    )
t( 1, line input   ;, a ;, '' )
t( 1, line input  ;;, a ;, '' )
t( 1, line input   ;, a ;;    )
t( 1, line input  ;;, a ;;    )
t( 1, line input   ;, a ;; '' )
t( 1, line input  ;;, a ;; '' )
t( 1, line input   ;,"T"    )
t( 1, line input  ;;,"T"    )
t( 1, line input   ;,"T" '' )
t( 1, line input  ;;,"T" '' )
t( 1, line input   ;,"T",     )
t( 1, line input  ;;,"T",     )
t( 1, line input   ;,"T",  '' )
t( 1, line input  ;;,"T",  '' )
t( 1, line input   ;,"T";     )
t( 1, line input  ;;,"T";     )
t( 1, line input   ;,"T";  '' )
t( 1, line input  ;;,"T";  '' )
t( 1, line input   ;,"T",,    )
t( 1, line input  ;;,"T",,    )
t( 1, line input   ;,"T",, '' )
t( 1, line input  ;;,"T",, '' )
t( 1, line input   ;,"T",;    )
t( 1, line input  ;;,"T",;    )
t( 1, line input   ;,"T",; '' )
t( 1, line input  ;;,"T",; '' )
t( 1, line input   ;,"T";,    )
t( 1, line input  ;;,"T";,    )
t( 1, line input   ;,"T";, '' )
t( 1, line input  ;;,"T";, '' )
t( 1, line input   ;,"T";;    )
t( 1, line input  ;;,"T";;    )
t( 1, line input   ;,"T";; '' )
t( 1, line input  ;;,"T";; '' )
t( 0, line input   ;, b     )
t( 1, line input  ;;, b     )
t( 0, line input   ;, b  '' )
t( 1, line input  ;;, b  '' )
t( 1, line input   ;, b ,     )
t( 1, line input  ;;, b ,     )
t( 1, line input   ;, b ,  '' )
t( 1, line input  ;;, b ,  '' )
t( 1, line input   ;, b ;     )
t( 1, line input  ;;, b ;     )
t( 1, line input   ;, b ;  '' )
t( 1, line input  ;;, b ;  '' )
t( 1, line input   ;, b ,,    )
t( 1, line input  ;;, b ,,    )
t( 1, line input   ;, b ,, '' )
t( 1, line input  ;;, b ,, '' )
t( 1, line input   ;, b ,;    )
t( 1, line input  ;;, b ,;    )
t( 1, line input   ;, b ,; '' )
t( 1, line input  ;;, b ,; '' )
t( 1, line input   ;, b ;,    )
t( 1, line input  ;;, b ;,    )
t( 1, line input   ;, b ;, '' )
t( 1, line input  ;;, b ;, '' )
t( 1, line input   ;, b ;;    )
t( 1, line input  ;;, b ;;    )
t( 1, line input   ;, b ;; '' )
t( 1, line input  ;;, b ;; '' )
t( 1, line input   ;;    )
t( 1, line input  ;;;    )
t( 1, line input   ;; '' )
t( 1, line input  ;;; '' )
t( 1, line input   ;; 1     )
t( 1, line input  ;;; 1     )
t( 1, line input   ;; 1  '' )
t( 1, line input  ;;; 1  '' )
t( 1, line input   ;; 1 ,     )
t( 1, line input  ;;; 1 ,     )
t( 1, line input   ;; 1 ,  '' )
t( 1, line input  ;;; 1 ,  '' )
t( 1, line input   ;; 1 ;     )
t( 1, line input  ;;; 1 ;     )
t( 1, line input   ;; 1 ;  '' )
t( 1, line input  ;;; 1 ;  '' )
t( 1, line input   ;; 1 ,,    )
t( 1, line input  ;;; 1 ,,    )
t( 1, line input   ;; 1 ,, '' )
t( 1, line input  ;;; 1 ,, '' )
t( 1, line input   ;; 1 ,;    )
t( 1, line input  ;;; 1 ,;    )
t( 1, line input   ;; 1 ,; '' )
t( 1, line input  ;;; 1 ,; '' )
t( 1, line input   ;; 1 ;,    )
t( 1, line input  ;;; 1 ;,    )
t( 1, line input   ;; 1 ;, '' )
t( 1, line input  ;;; 1 ;, '' )
t( 1, line input   ;; 1 ;;    )
t( 1, line input  ;;; 1 ;;    )
t( 1, line input   ;; 1 ;; '' )
t( 1, line input  ;;; 1 ;; '' )
t( 0, line input   ;; a     )
t( 1, line input  ;;; a     )
t( 0, line input   ;; a  '' )
t( 1, line input  ;;; a  '' )
t( 1, line input   ;; a ,     )
t( 1, line input  ;;; a ,     )
t( 1, line input   ;; a ,  '' )
t( 1, line input  ;;; a ,  '' )
t( 1, line input   ;; a ;     )
t( 1, line input  ;;; a ;     )
t( 1, line input   ;; a ;  '' )
t( 1, line input  ;;; a ;  '' )
t( 1, line input   ;; a ,,    )
t( 1, line input  ;;; a ,,    )
t( 1, line input   ;; a ,, '' )
t( 1, line input  ;;; a ,, '' )
t( 1, line input   ;; a ,;    )
t( 1, line input  ;;; a ,;    )
t( 1, line input   ;; a ,; '' )
t( 1, line input  ;;; a ,; '' )
t( 1, line input   ;; a ;,    )
t( 1, line input  ;;; a ;,    )
t( 1, line input   ;; a ;, '' )
t( 1, line input  ;;; a ;, '' )
t( 1, line input   ;; a ;;    )
t( 1, line input  ;;; a ;;    )
t( 1, line input   ;; a ;; '' )
t( 1, line input  ;;; a ;; '' )
t( 1, line input   ;;"T"    )
t( 1, line input  ;;;"T"    )
t( 1, line input   ;;"T" '' )
t( 1, line input  ;;;"T" '' )
t( 1, line input   ;;"T",     )
t( 1, line input  ;;;"T",     )
t( 1, line input   ;;"T",  '' )
t( 1, line input  ;;;"T",  '' )
t( 1, line input   ;;"T";     )
t( 1, line input  ;;;"T";     )
t( 1, line input   ;;"T";  '' )
t( 1, line input  ;;;"T";  '' )
t( 1, line input   ;;"T",,    )
t( 1, line input  ;;;"T",,    )
t( 1, line input   ;;"T",, '' )
t( 1, line input  ;;;"T",, '' )
t( 1, line input   ;;"T",;    )
t( 1, line input  ;;;"T",;    )
t( 1, line input   ;;"T",; '' )
t( 1, line input  ;;;"T",; '' )
t( 1, line input   ;;"T";,    )
t( 1, line input  ;;;"T";,    )
t( 1, line input   ;;"T";, '' )
t( 1, line input  ;;;"T";, '' )
t( 1, line input   ;;"T";;    )
t( 1, line input  ;;;"T";;    )
t( 1, line input   ;;"T";; '' )
t( 1, line input  ;;;"T";; '' )
t( 0, line input   ;; b     )
t( 1, line input  ;;; b     )
t( 0, line input   ;; b  '' )
t( 1, line input  ;;; b  '' )
t( 1, line input   ;; b ,     )
t( 1, line input  ;;; b ,     )
t( 1, line input   ;; b ,  '' )
t( 1, line input  ;;; b ,  '' )
t( 1, line input   ;; b ;     )
t( 1, line input  ;;; b ;     )
t( 1, line input   ;; b ;  '' )
t( 1, line input  ;;; b ;  '' )
t( 1, line input   ;; b ,,    )
t( 1, line input  ;;; b ,,    )
t( 1, line input   ;; b ,, '' )
t( 1, line input  ;;; b ,, '' )
t( 1, line input   ;; b ,;    )
t( 1, line input  ;;; b ,;    )
t( 1, line input   ;; b ,; '' )
t( 1, line input  ;;; b ,; '' )
t( 1, line input   ;; b ;,    )
t( 1, line input  ;;; b ;,    )
t( 1, line input   ;; b ;, '' )
t( 1, line input  ;;; b ;, '' )
t( 1, line input   ;; b ;;    )
t( 1, line input  ;;; b ;;    )
t( 1, line input   ;; b ;; '' )
t( 1, line input  ;;; b ;; '' )
t( 1, line input    1     )
t( 1, line input  ; 1     )
t( 1, line input    1  '' )
t( 1, line input  ; 1  '' )
t( 1, line input    1 ,     )
t( 1, line input  ; 1 ,     )
t( 1, line input    1 ,  '' )
t( 1, line input  ; 1 ,  '' )
t( 1, line input    1 ,  1     )
t( 1, line input  ; 1 ,  1     )
t( 1, line input    1 ,  1  '' )
t( 1, line input  ; 1 ,  1  '' )
t( 1, line input    1 ,  a     )
t( 1, line input  ; 1 ,  a     )
t( 1, line input    1 ,  a  '' )
t( 1, line input  ; 1 ,  a  '' )
t( 1, line input    1 , "T"    )
t( 1, line input  ; 1 , "T"    )
t( 1, line input    1 , "T" '' )
t( 1, line input  ; 1 , "T" '' )
t( 1, line input    1 ,  b     )
t( 1, line input  ; 1 ,  b     )
t( 1, line input    1 ,  b  '' )
t( 1, line input  ; 1 ,  b  '' )
t( 1, line input    1 ;     )
t( 1, line input  ; 1 ;     )
t( 1, line input    1 ;  '' )
t( 1, line input  ; 1 ;  '' )
t( 1, line input    1 ;  1     )
t( 1, line input  ; 1 ;  1     )
t( 1, line input    1 ;  1  '' )
t( 1, line input  ; 1 ;  1  '' )
t( 1, line input    1 ;  a     )
t( 1, line input  ; 1 ;  a     )
t( 1, line input    1 ;  a  '' )
t( 1, line input  ; 1 ;  a  '' )
t( 1, line input    1 ; "T"    )
t( 1, line input  ; 1 ; "T"    )
t( 1, line input    1 ; "T" '' )
t( 1, line input  ; 1 ; "T" '' )
t( 1, line input    1 ;  b     )
t( 1, line input  ; 1 ;  b     )
t( 1, line input    1 ;  b  '' )
t( 1, line input  ; 1 ;  b  '' )
t( 1, line input    1 ,,    )
t( 1, line input  ; 1 ,,    )
t( 1, line input    1 ,, '' )
t( 1, line input  ; 1 ,, '' )
t( 1, line input    1 ,, 1     )
t( 1, line input  ; 1 ,, 1     )
t( 1, line input    1 ,, 1  '' )
t( 1, line input  ; 1 ,, 1  '' )
t( 1, line input    1 ,, a     )
t( 1, line input  ; 1 ,, a     )
t( 1, line input    1 ,, a  '' )
t( 1, line input  ; 1 ,, a  '' )
t( 1, line input    1 ,,"T"    )
t( 1, line input  ; 1 ,,"T"    )
t( 1, line input    1 ,,"T" '' )
t( 1, line input  ; 1 ,,"T" '' )
t( 1, line input    1 ,, b     )
t( 1, line input  ; 1 ,, b     )
t( 1, line input    1 ,, b  '' )
t( 1, line input  ; 1 ,, b  '' )
t( 1, line input    1 ,;    )
t( 1, line input  ; 1 ,;    )
t( 1, line input    1 ,; '' )
t( 1, line input  ; 1 ,; '' )
t( 1, line input    1 ,; 1     )
t( 1, line input  ; 1 ,; 1     )
t( 1, line input    1 ,; 1  '' )
t( 1, line input  ; 1 ,; 1  '' )
t( 1, line input    1 ,; a     )
t( 1, line input  ; 1 ,; a     )
t( 1, line input    1 ,; a  '' )
t( 1, line input  ; 1 ,; a  '' )
t( 1, line input    1 ,;"T"    )
t( 1, line input  ; 1 ,;"T"    )
t( 1, line input    1 ,;"T" '' )
t( 1, line input  ; 1 ,;"T" '' )
t( 1, line input    1 ,; b     )
t( 1, line input  ; 1 ,; b     )
t( 1, line input    1 ,; b  '' )
t( 1, line input  ; 1 ,; b  '' )
t( 1, line input    1 ;,    )
t( 1, line input  ; 1 ;,    )
t( 1, line input    1 ;, '' )
t( 1, line input  ; 1 ;, '' )
t( 1, line input    1 ;, 1     )
t( 1, line input  ; 1 ;, 1     )
t( 1, line input    1 ;, 1  '' )
t( 1, line input  ; 1 ;, 1  '' )
t( 1, line input    1 ;, a     )
t( 1, line input  ; 1 ;, a     )
t( 1, line input    1 ;, a  '' )
t( 1, line input  ; 1 ;, a  '' )
t( 1, line input    1 ;,"T"    )
t( 1, line input  ; 1 ;,"T"    )
t( 1, line input    1 ;,"T" '' )
t( 1, line input  ; 1 ;,"T" '' )
t( 1, line input    1 ;, b     )
t( 1, line input  ; 1 ;, b     )
t( 1, line input    1 ;, b  '' )
t( 1, line input  ; 1 ;, b  '' )
t( 1, line input    1 ;;    )
t( 1, line input  ; 1 ;;    )
t( 1, line input    1 ;; '' )
t( 1, line input  ; 1 ;; '' )
t( 1, line input    1 ;; 1     )
t( 1, line input  ; 1 ;; 1     )
t( 1, line input    1 ;; 1  '' )
t( 1, line input  ; 1 ;; 1  '' )
t( 1, line input    1 ;; a     )
t( 1, line input  ; 1 ;; a     )
t( 1, line input    1 ;; a  '' )
t( 1, line input  ; 1 ;; a  '' )
t( 1, line input    1 ;;"T"    )
t( 1, line input  ; 1 ;;"T"    )
t( 1, line input    1 ;;"T" '' )
t( 1, line input  ; 1 ;;"T" '' )
t( 1, line input    1 ;; b     )
t( 1, line input  ; 1 ;; b     )
t( 1, line input    1 ;; b  '' )
t( 1, line input  ; 1 ;; b  '' )
t( 0, line input    a     )
t( 0, line input  ; a     )
t( 0, line input    a  '' )
t( 0, line input  ; a  '' )
t( 1, line input    a ,     )
t( 1, line input  ; a ,     )
t( 1, line input    a ,  '' )
t( 1, line input  ; a ,  '' )
t( 1, line input    a ,  1     )
t( 1, line input  ; a ,  1     )
t( 1, line input    a ,  1  '' )
t( 1, line input  ; a ,  1  '' )
t( 0, line input    a ,  a     )
t( 0, line input  ; a ,  a     )
t( 0, line input    a ,  a  '' )
t( 0, line input  ; a ,  a  '' )
t( 1, line input    a , "T"    )
t( 1, line input  ; a , "T"    )
t( 1, line input    a , "T" '' )
t( 1, line input  ; a , "T" '' )
t( 0, line input    a ,  b     )
t( 0, line input  ; a ,  b     )
t( 0, line input    a ,  b  '' )
t( 0, line input  ; a ,  b  '' )
t( 1, line input    a ;     )
t( 1, line input  ; a ;     )
t( 1, line input    a ;  '' )
t( 1, line input  ; a ;  '' )
t( 1, line input    a ;  1     )
t( 1, line input  ; a ;  1     )
t( 1, line input    a ;  1  '' )
t( 1, line input  ; a ;  1  '' )
t( 0, line input    a ;  a     )
t( 0, line input  ; a ;  a     )
t( 0, line input    a ;  a  '' )
t( 0, line input  ; a ;  a  '' )
t( 1, line input    a ; "T"    )
t( 1, line input  ; a ; "T"    )
t( 1, line input    a ; "T" '' )
t( 1, line input  ; a ; "T" '' )
t( 0, line input    a ;  b     )
t( 0, line input  ; a ;  b     )
t( 0, line input    a ;  b  '' )
t( 0, line input  ; a ;  b  '' )
t( 1, line input    a ,,    )
t( 1, line input  ; a ,,    )
t( 1, line input    a ,, '' )
t( 1, line input  ; a ,, '' )
t( 1, line input    a ,, 1     )
t( 1, line input  ; a ,, 1     )
t( 1, line input    a ,, 1  '' )
t( 1, line input  ; a ,, 1  '' )
t( 1, line input    a ,, a     )
t( 1, line input  ; a ,, a     )
t( 1, line input    a ,, a  '' )
t( 1, line input  ; a ,, a  '' )
t( 1, line input    a ,,"T"    )
t( 1, line input  ; a ,,"T"    )
t( 1, line input    a ,,"T" '' )
t( 1, line input  ; a ,,"T" '' )
t( 1, line input    a ,, b     )
t( 1, line input  ; a ,, b     )
t( 1, line input    a ,, b  '' )
t( 1, line input  ; a ,, b  '' )
t( 1, line input    a ,;    )
t( 1, line input  ; a ,;    )
t( 1, line input    a ,; '' )
t( 1, line input  ; a ,; '' )
t( 1, line input    a ,; 1     )
t( 1, line input  ; a ,; 1     )
t( 1, line input    a ,; 1  '' )
t( 1, line input  ; a ,; 1  '' )
t( 1, line input    a ,; a     )
t( 1, line input  ; a ,; a     )
t( 1, line input    a ,; a  '' )
t( 1, line input  ; a ,; a  '' )
t( 1, line input    a ,;"T"    )
t( 1, line input  ; a ,;"T"    )
t( 1, line input    a ,;"T" '' )
t( 1, line input  ; a ,;"T" '' )
t( 1, line input    a ,; b     )
t( 1, line input  ; a ,; b     )
t( 1, line input    a ,; b  '' )
t( 1, line input  ; a ,; b  '' )
t( 1, line input    a ;,    )
t( 1, line input  ; a ;,    )
t( 1, line input    a ;, '' )
t( 1, line input  ; a ;, '' )
t( 1, line input    a ;, 1     )
t( 1, line input  ; a ;, 1     )
t( 1, line input    a ;, 1  '' )
t( 1, line input  ; a ;, 1  '' )
t( 1, line input    a ;, a     )
t( 1, line input  ; a ;, a     )
t( 1, line input    a ;, a  '' )
t( 1, line input  ; a ;, a  '' )
t( 1, line input    a ;,"T"    )
t( 1, line input  ; a ;,"T"    )
t( 1, line input    a ;,"T" '' )
t( 1, line input  ; a ;,"T" '' )
t( 1, line input    a ;, b     )
t( 1, line input  ; a ;, b     )
t( 1, line input    a ;, b  '' )
t( 1, line input  ; a ;, b  '' )
t( 1, line input    a ;;    )
t( 1, line input  ; a ;;    )
t( 1, line input    a ;; '' )
t( 1, line input  ; a ;; '' )
t( 1, line input    a ;; 1     )
t( 1, line input  ; a ;; 1     )
t( 1, line input    a ;; 1  '' )
t( 1, line input  ; a ;; 1  '' )
t( 1, line input    a ;; a     )
t( 1, line input  ; a ;; a     )
t( 1, line input    a ;; a  '' )
t( 1, line input  ; a ;; a  '' )
t( 1, line input    a ;;"T"    )
t( 1, line input  ; a ;;"T"    )
t( 1, line input    a ;;"T" '' )
t( 1, line input  ; a ;;"T" '' )
t( 1, line input    a ;; b     )
t( 1, line input  ; a ;; b     )
t( 1, line input    a ;; b  '' )
t( 1, line input  ; a ;; b  '' )
t( 1, line input   "T"    )
t( 1, line input  ;"T"    )
t( 1, line input   "T" '' )
t( 1, line input  ;"T" '' )
t( 1, line input   "T",     )
t( 1, line input  ;"T",     )
t( 1, line input   "T",  '' )
t( 1, line input  ;"T",  '' )
t( 1, line input   "T",  1     )
t( 1, line input  ;"T",  1     )
t( 1, line input   "T",  1  '' )
t( 1, line input  ;"T",  1  '' )
t( 0, line input   "T",  a     )
t( 0, line input  ;"T",  a     )
t( 0, line input   "T",  a  '' )
t( 0, line input  ;"T",  a  '' )
t( 1, line input   "T", "T"    )
t( 1, line input  ;"T", "T"    )
t( 1, line input   "T", "T" '' )
t( 1, line input  ;"T", "T" '' )
t( 0, line input   "T",  b     )
t( 0, line input  ;"T",  b     )
t( 0, line input   "T",  b  '' )
t( 0, line input  ;"T",  b  '' )
t( 1, line input   "T";     )
t( 1, line input  ;"T";     )
t( 1, line input   "T";  '' )
t( 1, line input  ;"T";  '' )
t( 1, line input   "T";  1     )
t( 1, line input  ;"T";  1     )
t( 1, line input   "T";  1  '' )
t( 1, line input  ;"T";  1  '' )
t( 0, line input   "T";  a     )
t( 0, line input  ;"T";  a     )
t( 0, line input   "T";  a  '' )
t( 0, line input  ;"T";  a  '' )
t( 1, line input   "T"; "T"    )
t( 1, line input  ;"T"; "T"    )
t( 1, line input   "T"; "T" '' )
t( 1, line input  ;"T"; "T" '' )
t( 0, line input   "T";  b     )
t( 0, line input  ;"T";  b     )
t( 0, line input   "T";  b  '' )
t( 0, line input  ;"T";  b  '' )
t( 1, line input   "T",,    )
t( 1, line input  ;"T",,    )
t( 1, line input   "T",, '' )
t( 1, line input  ;"T",, '' )
t( 1, line input   "T",, 1     )
t( 1, line input  ;"T",, 1     )
t( 1, line input   "T",, 1  '' )
t( 1, line input  ;"T",, 1  '' )
t( 1, line input   "T",, a     )
t( 1, line input  ;"T",, a     )
t( 1, line input   "T",, a  '' )
t( 1, line input  ;"T",, a  '' )
t( 1, line input   "T",,"T"    )
t( 1, line input  ;"T",,"T"    )
t( 1, line input   "T",,"T" '' )
t( 1, line input  ;"T",,"T" '' )
t( 1, line input   "T",, b     )
t( 1, line input  ;"T",, b     )
t( 1, line input   "T",, b  '' )
t( 1, line input  ;"T",, b  '' )
t( 1, line input   "T",;    )
t( 1, line input  ;"T",;    )
t( 1, line input   "T",; '' )
t( 1, line input  ;"T",; '' )
t( 1, line input   "T",; 1     )
t( 1, line input  ;"T",; 1     )
t( 1, line input   "T",; 1  '' )
t( 1, line input  ;"T",; 1  '' )
t( 1, line input   "T",; a     )
t( 1, line input  ;"T",; a     )
t( 1, line input   "T",; a  '' )
t( 1, line input  ;"T",; a  '' )
t( 1, line input   "T",;"T"    )
t( 1, line input  ;"T",;"T"    )
t( 1, line input   "T",;"T" '' )
t( 1, line input  ;"T",;"T" '' )
t( 1, line input   "T",; b     )
t( 1, line input  ;"T",; b     )
t( 1, line input   "T",; b  '' )
t( 1, line input  ;"T",; b  '' )
t( 1, line input   "T";,    )
t( 1, line input  ;"T";,    )
t( 1, line input   "T";, '' )
t( 1, line input  ;"T";, '' )
t( 1, line input   "T";, 1     )
t( 1, line input  ;"T";, 1     )
t( 1, line input   "T";, 1  '' )
t( 1, line input  ;"T";, 1  '' )
t( 1, line input   "T";, a     )
t( 1, line input  ;"T";, a     )
t( 1, line input   "T";, a  '' )
t( 1, line input  ;"T";, a  '' )
t( 1, line input   "T";,"T"    )
t( 1, line input  ;"T";,"T"    )
t( 1, line input   "T";,"T" '' )
t( 1, line input  ;"T";,"T" '' )
t( 1, line input   "T";, b     )
t( 1, line input  ;"T";, b     )
t( 1, line input   "T";, b  '' )
t( 1, line input  ;"T";, b  '' )
t( 1, line input   "T";;    )
t( 1, line input  ;"T";;    )
t( 1, line input   "T";; '' )
t( 1, line input  ;"T";; '' )
t( 1, line input   "T";; 1     )
t( 1, line input  ;"T";; 1     )
t( 1, line input   "T";; 1  '' )
t( 1, line input  ;"T";; 1  '' )
t( 1, line input   "T";; a     )
t( 1, line input  ;"T";; a     )
t( 1, line input   "T";; a  '' )
t( 1, line input  ;"T";; a  '' )
t( 1, line input   "T";;"T"    )
t( 1, line input  ;"T";;"T"    )
t( 1, line input   "T";;"T" '' )
t( 1, line input  ;"T";;"T" '' )
t( 1, line input   "T";; b     )
t( 1, line input  ;"T";; b     )
t( 1, line input   "T";; b  '' )
t( 1, line input  ;"T";; b  '' )
t( 0, line input    b     )
t( 0, line input  ; b     )
t( 0, line input    b  '' )
t( 0, line input  ; b  '' )
t( 1, line input    b ,     )
t( 1, line input  ; b ,     )
t( 1, line input    b ,  '' )
t( 1, line input  ; b ,  '' )
t( 1, line input    b ,  1     )
t( 1, line input  ; b ,  1     )
t( 1, line input    b ,  1  '' )
t( 1, line input  ; b ,  1  '' )
t( 0, line input    b ,  a     )
t( 0, line input  ; b ,  a     )
t( 0, line input    b ,  a  '' )
t( 0, line input  ; b ,  a  '' )
t( 1, line input    b , "T"    )
t( 1, line input  ; b , "T"    )
t( 1, line input    b , "T" '' )
t( 1, line input  ; b , "T" '' )
t( 0, line input    b ,  b     )
t( 0, line input  ; b ,  b     )
t( 0, line input    b ,  b  '' )
t( 0, line input  ; b ,  b  '' )
t( 1, line input    b ;     )
t( 1, line input  ; b ;     )
t( 1, line input    b ;  '' )
t( 1, line input  ; b ;  '' )
t( 1, line input    b ;  1     )
t( 1, line input  ; b ;  1     )
t( 1, line input    b ;  1  '' )
t( 1, line input  ; b ;  1  '' )
t( 0, line input    b ;  a     )
t( 0, line input  ; b ;  a     )
t( 0, line input    b ;  a  '' )
t( 0, line input  ; b ;  a  '' )
t( 1, line input    b ; "T"    )
t( 1, line input  ; b ; "T"    )
t( 1, line input    b ; "T" '' )
t( 1, line input  ; b ; "T" '' )
t( 0, line input    b ;  b     )
t( 0, line input  ; b ;  b     )
t( 0, line input    b ;  b  '' )
t( 0, line input  ; b ;  b  '' )
t( 1, line input    b ,,    )
t( 1, line input  ; b ,,    )
t( 1, line input    b ,, '' )
t( 1, line input  ; b ,, '' )
t( 1, line input    b ,, 1     )
t( 1, line input  ; b ,, 1     )
t( 1, line input    b ,, 1  '' )
t( 1, line input  ; b ,, 1  '' )
t( 1, line input    b ,, a     )
t( 1, line input  ; b ,, a     )
t( 1, line input    b ,, a  '' )
t( 1, line input  ; b ,, a  '' )
t( 1, line input    b ,,"T"    )
t( 1, line input  ; b ,,"T"    )
t( 1, line input    b ,,"T" '' )
t( 1, line input  ; b ,,"T" '' )
t( 1, line input    b ,, b     )
t( 1, line input  ; b ,, b     )
t( 1, line input    b ,, b  '' )
t( 1, line input  ; b ,, b  '' )
t( 1, line input    b ,;    )
t( 1, line input  ; b ,;    )
t( 1, line input    b ,; '' )
t( 1, line input  ; b ,; '' )
t( 1, line input    b ,; 1     )
t( 1, line input  ; b ,; 1     )
t( 1, line input    b ,; 1  '' )
t( 1, line input  ; b ,; 1  '' )
t( 1, line input    b ,; a     )
t( 1, line input  ; b ,; a     )
t( 1, line input    b ,; a  '' )
t( 1, line input  ; b ,; a  '' )
t( 1, line input    b ,;"T"    )
t( 1, line input  ; b ,;"T"    )
t( 1, line input    b ,;"T" '' )
t( 1, line input  ; b ,;"T" '' )
t( 1, line input    b ,; b     )
t( 1, line input  ; b ,; b     )
t( 1, line input    b ,; b  '' )
t( 1, line input  ; b ,; b  '' )
t( 1, line input    b ;,    )
t( 1, line input  ; b ;,    )
t( 1, line input    b ;, '' )
t( 1, line input  ; b ;, '' )
t( 1, line input    b ;, 1     )
t( 1, line input  ; b ;, 1     )
t( 1, line input    b ;, 1  '' )
t( 1, line input  ; b ;, 1  '' )
t( 1, line input    b ;, a     )
t( 1, line input  ; b ;, a     )
t( 1, line input    b ;, a  '' )
t( 1, line input  ; b ;, a  '' )
t( 1, line input    b ;,"T"    )
t( 1, line input  ; b ;,"T"    )
t( 1, line input    b ;,"T" '' )
t( 1, line input  ; b ;,"T" '' )
t( 1, line input    b ;, b     )
t( 1, line input  ; b ;, b     )
t( 1, line input    b ;, b  '' )
t( 1, line input  ; b ;, b  '' )
t( 1, line input    b ;;    )
t( 1, line input  ; b ;;    )
t( 1, line input    b ;; '' )
t( 1, line input  ; b ;; '' )
t( 1, line input    b ;; 1     )
t( 1, line input  ; b ;; 1     )
t( 1, line input    b ;; 1  '' )
t( 1, line input  ; b ;; 1  '' )
t( 1, line input    b ;; a     )
t( 1, line input  ; b ;; a     )
t( 1, line input    b ;; a  '' )
t( 1, line input  ; b ;; a  '' )
t( 1, line input    b ;;"T"    )
t( 1, line input  ; b ;;"T"    )
t( 1, line input    b ;;"T" '' )
t( 1, line input  ; b ;;"T" '' )
t( 1, line input    b ;; b     )
t( 1, line input  ; b ;; b     )
t( 1, line input    b ;; b  '' )
t( 1, line input  ; b ;; b  '' )
